import type { ShortcutDefinition } from "./registry";

export const defaultShortcuts: Omit<ShortcutDefinition, "scope">[] = [
  {
    id: "nav.command-palette",
    keys: "Ctrl+K",
    description: "打开命令面板",
    category: "navigation",
    handler: () => {},
  },
  {
    id: "nav.go-to-issues",
    keys: "",
    description: "前往 Issues 页面",
    category: "navigation",
    sequence: ["G", "I"],
    handler: () => {},
  },
  {
    id: "nav.go-to-projects",
    keys: "",
    description: "前往项目列表",
    category: "navigation",
    sequence: ["G", "P"],
    handler: () => {},
  },
  {
    id: "edit.save",
    keys: "Ctrl+S",
    description: "保存当前内容",
    category: "editing",
    handler: () => {},
  },
  {
    id: "edit.undo",
    keys: "Ctrl+Z",
    description: "撤销",
    category: "editing",
    handler: () => {},
  },
  {
    id: "edit.redo",
    keys: "Ctrl+Y",
    description: "重做",
    category: "editing",
    handler: () => {},
  },
  {
    id: "edit.rename",
    keys: "F2",
    description: "重命名选中项",
    category: "editing",
    handler: () => {},
  },
  {
    id: "edit.delete",
    keys: "Delete",
    description: "删除选中项",
    category: "editing",
    handler: () => {},
  },
  {
    id: "view.search",
    keys: "Ctrl+F",
    description: "搜索",
    category: "view",
    handler: () => {},
  },
  {
    id: "view.print",
    keys: "Ctrl+P",
    description: "打印",
    category: "view",
    handler: () => {},
  },
  {
    id: "tools.new-item",
    keys: "Ctrl+Shift+N",
    description: "新建项目",
    category: "tools",
    handler: () => {},
  },
  {
    id: "a11y.shortcut-help",
    keys: "?",
    description: "显示快捷键帮助",
    category: "accessibility",
    handler: () => {},
  },
  {
    id: "a11y.close-dismiss",
    keys: "Escape",
    description: "关闭/取消",
    category: "accessibility",
    handler: () => {},
  },
];