/**
 * YiAi · Dashboard data model
 * --------------------------------------------------------------------------
 * Generated by yry-init pipeline (detect → explore → generate → arch → verify)
 * The data is consumed by:
 *   - index.html (Vue 3 template references · v-cloak hides it until
 *     the Vue app + all CDN components resolve)
 *   - index.js  (reads window.HELP_CONFIG and creates the Vue app)
 */
window.HELP_CONFIG = {
  titleIcon:     "★",
  title:         "YiAi · FastAPI + MongoDB Backend",
  tagline:       "Async Python backend · 7 route groups · module execution engine · AI chat · RSS scheduler · OSS storage",
  backTopLabel:  "返回顶部",
  footerNote:    "由 yry-init 流水线生成 (detect → explore → generate → arch → verify) · 项目根: /Users/ruiyi/Downloads/YrY/YiAi/",

  breadcrumb: [
    { label: "YiDoc",    href: "../../index.html" },
    { label: "Projects", href: "../../dashboard/index.html" },
    { label: "YiAi" }
  ],

  stats: [
    { value: "20", label: "Runtime Deps", modifier: "cyan",   sub: "requirements.txt" },
    { value: "0",  label: "Dev Deps",     modifier: "cyan",   sub: "none pinned" },
    { value: "11", label: "Stories",      modifier: "accent", sub: "5 arch + 6 test" },
    { value: "69", label: "Source Files", modifier: "accent", sub: "Python modules" }
  ],

  panelHub: {
    label: { text: '📊', panel: 'reports', title: 'YiAi 文档导航' },
    targetBlank: false,
    buttons: [
      { icon: '🏛', name: 'Architecture', desc: '5 个架构场景',  color: 'var(--yry-accent)', panel: 'arch' },
      { icon: '✅', name: 'Self-Check',   desc: '6 个自检场景',  color: 'var(--yry-cyan)',  panel: 'test' },
      { icon: '📁', name: 'Files',        desc: '69 文件 · Python', color: 'var(--yry-info)', panel: 'files' },
      { icon: '🔌', name: 'APIs',         desc: '26 端点 · 7 路由组', color: 'var(--yry-warn)',  panel: 'apis' },
    ],
    flow: '架构分析 → 自检策略 → 文件体检 → API 审计',
    urls: {
      arch:  '../../templates/arch/index.html?project=YiAi',
      test:  '../../templates/test/index.html?project=YiAi',
      files: '../../templates/files/index.html?project=YiAi',
      apis:  '../../templates/apis/index.html?project=YiAi',
      daily: '../../templates/daily/cto-report.html?project=YiAi',
    },
  },

  reportsList: {
    daily: [],
    weekly: [],
    monthly: [],
  },

  sections: [
    // ── § 1 · Third-party dependencies & frameworks ────────────────────
    {
      id:    "section-dependencies",
      badge: "1",
      title: "Third-Party Dependencies / Frameworks",
      meta:  "20 runtime · 0 dev deps",
      groups: [
        {
          id:    "deps-runtime",
          kind:  "items",
          icon:  "📦",
          title: "Runtime Dependencies (20)",
          items: [
            { icon: "F", iconTone: "is-module", title: "FastAPI",          description: "Async Web 框架 · <strong>核心 API 引擎</strong> · 7 路由组注册", meta: "<span class=\"accent\">Runtime</span> · >=0.104.0" },
            { icon: "U", iconTone: "is-module", title: "Uvicorn",          description: "ASGI 服务器 · <strong>生产级并发</strong> · lifespan 管理",      meta: "<span class=\"accent\">Runtime</span> · >=0.24.0" },
            { icon: "P", iconTone: "is-module", title: "Pydantic",          description: "数据校验 · <strong>BaseModel 请求/响应模型</strong> · 全部 schema",  meta: "<span class=\"accent\">Runtime</span> · >=2.0.0" },
            { icon: "S", iconTone: "is-module", title: "pydantic-settings", description: "Settings 单例 · <strong>config.yaml 加载</strong>",             meta: "<span class=\"accent\">Runtime</span> · >=2.0.0" },
            { icon: "M", iconTone: "is-module", title: "Motor",             description: "Async MongoDB 驱动 · <strong>data/database.py</strong>",         meta: "<span class=\"accent\">Runtime</span> · >=3.3.0" },
            { icon: "O", iconTone: "is-module", title: "pymongo",           description: "MongoDB 同步客户端 · 配套 Motor 使用",                            meta: "<span class=\"accent\">Runtime</span> · >=4.6.0" },
            { icon: "D", iconTone: "is-module", title: "python-dotenv",     description: ".env 加载 · 配合 config.yaml",                                  meta: "<span class=\"accent\">Runtime</span> · >=1.0.0" },
            { icon: "A", iconTone: "is-module", title: "ollama",            description: "本地 LLM 客户端 · <strong>domain/ai/chat.py</strong>",         meta: "<span class=\"accent\">Runtime</span> · >=0.1.0" },
            { icon: "H", iconTone: "is-module", title: "aiohttp",           description: "Async HTTP · <strong>WeWork webhook</strong>",                 meta: "<span class=\"accent\">Runtime</span> · >=3.9.0" },
            { icon: "R", iconTone: "is-module", title: "feedparser",        description: "RSS 解析 · <strong>domain/rss/feed.py</strong>",              meta: "<span class=\"accent\">Runtime</span> · >=6.0.10" },
            { icon: "C", iconTone: "is-module", title: "APScheduler",       description: "AsyncIOScheduler · <strong>RSS 定时拉取</strong>",           meta: "<span class=\"accent\">Runtime</span> · >=3.10.0" },
            { icon: "Q", iconTone: "is-module", title: "qwen-vl-utils",     description: "Qwen 多模态工具 · 图像理解预处理",                              meta: "<span class=\"accent\">Runtime</span> · >=0.0.14" },
            { icon: "T", iconTone: "is-module", title: "transformers",       description: "HuggingFace 模型库 · 推理辅助",                                 meta: "<span class=\"accent\">Runtime</span> · >=4.37.0" },
            { icon: "Y", iconTone: "is-module", title: "PyYAML",             description: "YAML 解析 · <strong>config.yaml 加载</strong>",                meta: "<span class=\"accent\">Runtime</span> · >=6.0" },
            { icon: "X", iconTone: "is-module", title: "oss2",              description: "阿里云 OSS · <strong>domain/files/storage.py</strong>",       meta: "<span class=\"accent\">Runtime</span> · >=2.18.0" },
            { icon: "F", iconTone: "is-module", title: "python-multipart",  description: "Multipart 解析 · <strong>文件上传</strong>",                   meta: "<span class=\"accent\">Runtime</span> · >=0.0.9" },
            { icon: "I", iconTone: "is-module", title: "aiofiles",          description: "Async 文件 I/O · 配合文件路由",                                 meta: "<span class=\"accent\">Runtime</span> · >=23.2.1" },
            { icon: "N", iconTone: "is-module", title: "tenacity",          description: "重试装饰器 · 网络调用容错",                                      meta: "<span class=\"accent\">Runtime</span> · >=8.2.3" },
            { icon: "T", iconTone: "is-module", title: "typer",             description: "CLI 框架 · <strong>src/cli/state.py</strong>",                 meta: "<span class=\"accent\">Runtime</span> · >=0.9.0" },
            { icon: "R", iconTone: "is-module", title: "rich",             description: "终端富文本 · CLI 输出",                                          meta: "<span class=\"accent\">Runtime</span> · >=13.0.0" }
          ]
        },
        {
          id:    "deps-dev",
          kind:  "items",
          icon:  "🛠",
          title: "Dev Dependencies (0)",
          items: [
            { icon: "∅", iconTone: "is-module", title: "No dev deps pinned", description: "无 pytest / mypy / black 等开发依赖；当前无自动化测试框架", meta: "<span class=\"accent\">Dev</span> · none" }
          ]
        }
      ]
    },

    // ── § 2 · Story documents & scenes ──────────────────────────────────
    {
      id:    "section-stories",
      badge: "2",
      title: "Story Documents & Scenes",
      meta:  "2 stories · 11 scenes · architecture + self-check",
      groups: [
        {
          kind:  "stories",
          icon:  "📚",
          title: "Story Catalog (arch + test)",
          items: [
            {
              icon:        "🏛",
              title:       "System Architecture & Knowledge Codification",
              badge:       "5 scenes",
              description: "FastAPI lifespan 启动 → 7 路由组 → 服务层 → 域层 → Motor+OSS 持久化 · <strong>5 architecture scenes</strong> · module location, data flow, onboarding, dependency impact, security surface",
              sceneLinks: [
                { label: "1. Module Location",          href: "../../projects/YiAi/arch/scene-1-module-location/index.md" },
                { label: "2. Data Flow Tracing",         href: "../../projects/YiAi/arch/scene-2-data-flow-tracing/index.md" },
                { label: "3. Newcomer Onboarding",      href: "../../projects/YiAi/arch/scene-3-newcomer-onboarding/index.md" },
                { label: "4. Dependency Impact",         href: "../../projects/YiAi/arch/scene-4-dependency-change-impact/index.md" },
                { label: "5. Security Surface",         href: "../../projects/YiAi/arch/scene-5-trust-boundary-security-surface/index.md" }
              ],
              links: [
                { label: "Architecture Dashboard →", href: "../../templates/arch/index.html?project=YiAi" }
              ],
              meta: "5 scenes · risk: medium · covers FastAPI + MongoDB + Observer"
            },
            {
              icon:        "✅",
              title:       "Self-Check Strategy & Verification Suite",
              badge:       "6 scenes",
              description: "持续验证流水线 · <strong>6 test scenes</strong> · post-init, pre-commit, doc consistency, security regression, cross-story integration, third-party health",
              sceneLinks: [
                { label: "1. Post-Init Self-Check",    href: "../../projects/YiAi/test/scene-1-post-init-full-self-check/index.md" },
                { label: "2. Pre-Commit Self-Check",  href: "../../projects/YiAi/test/scene-2-pre-commit-incremental-self-check/index.md" },
                { label: "3. Doc Consistency",         href: "../../projects/YiAi/test/scene-3-doc-code-consistency/index.md" },
                { label: "4. Security Regression",     href: "../../projects/YiAi/test/scene-4-security-surface-regression/index.md" },
                { label: "5. Integration Regression",  href: "../../projects/YiAi/test/scene-5-cross-story-integration-regression/index.md" },
                { label: "6. Third-Party Services",   href: "../../projects/YiAi/test/scene-6-third-party-framework-service/index.md" }
              ],
              links: [
                { label: "Test Dashboard →", href: "../../templates/test/index.html?project=YiAi" }
              ],
              meta: "6 scenes · risk: low · covers all 7 verify checks"
            }
          ]
        }
      ]
    },

    // ── § 3 · Main source code ──────────────────────────────────────────
    {
      id:    "section-source",
      badge: "3",
      title: "Main Source Code",
      meta:  "8 packages · 26 endpoints · 69 Python modules",
      groups: [
        {
          id:    "src-app",
          kind:  "items",
          icon:  "🚀",
          title: "Application Entry (root)",
          items: [
            { icon: "🚀", iconTone: "is-module", title: "main.py",         description: "Root 启动脚本 · uvicorn run · 读取 config.yaml",     meta: "<span class=\"accent\">Entry</span> · /Users/ruiyi/Downloads/YrY/YiAi/main.py" },
            { icon: "🧩", iconTone: "is-module", title: "src/app.py",      description: "create_app 工厂 · lifespan · 路由注册 · CORS · 中间件", meta: "<span class=\"accent\">Factory</span> · src/app.py" },
            { icon: "⚙️", iconTone: "is-module", title: "src/__main__.py", description: "python -m src 入口",                                meta: "<span class=\"accent\">Entry</span> · src/__main__.py" },
            { icon: "📜", iconTone: "is-module", title: "config.yaml",     description: "YAML 配置 · server / mongo / oss / ollama / observer / rss", meta: "<span class=\"accent\">Config</span> · config.yaml" },
            { icon: "📦", iconTone: "is-module", title: "requirements.txt", description: "20 runtime 依赖 · FastAPI + Motor + Ollama + APScheduler", meta: "<span class=\"accent\">Manifest</span> · requirements.txt" }
          ]
        },
        {
          id:    "src-server",
          kind:  "items",
          icon:  "🌐",
          title: "HTTP Layer (src/server/)",
          items: [
            { icon: "🛡", iconTone: "is-module", title: "middleware.py",  description: "header_verification_middleware · auth_token 网关",      meta: "<span class=\"accent\">Auth</span> · src/server/middleware.py" },
            { icon: "❗", iconTone: "is-module", title: "errors.py",       description: "全局异常处理 · BusinessException → ErrorCode 响应",     meta: "<span class=\"accent\">Errors</span> · src/server/errors.py" },
            { icon: "📁", iconTone: "is-module", title: "routes/files.py",       description: "文件 CRUD · 上传 · OSS 上传 · 读/写/删/重命名 (9 端点)", meta: "<span class=\"accent\">Router</span> · 9 endpoints" },
            { icon: "⚡", iconTone: "is-module", title: "routes/execution.py",   description: "通用模块执行引擎 · SSE 流式 (2 端点)",                meta: "<span class=\"accent\">Router</span> · 2 endpoints" },
            { icon: "💬", iconTone: "is-module", title: "routes/wework.py",     description: "企业微信 webhook 发送消息 (1 端点)",                  meta: "<span class=\"accent\">Router</span> · 1 endpoint" },
            { icon: "🧹", iconTone: "is-module", title: "routes/maintenance.py", description: "未引用图片清理 · sessions 清理 (2 端点)",             meta: "<span class=\"accent\">Router</span> · 2 endpoints" },
            { icon: "🗃", iconTone: "is-module", title: "routes/state.py",       description: "状态记录 CRUD · 分页/标签过滤 (5 端点)",              meta: "<span class=\"accent\">Router</span> · 5 endpoints" },
            { icon: "🩺", iconTone: "is-module", title: "routes/health.py",      description: "Observer 健康检查 · throttle/sampler/sandbox/guard 状态", meta: "<span class=\"accent\">Router</span> · 1 endpoint" },
            { icon: "📖", iconTone: "is-module", title: "routes/story_panel.py", description: "故事任务面板 sync · overview/list/single/sync/help (6 端点)", meta: "<span class=\"accent\">Router</span> · 6 endpoints" }
          ]
        },
        {
          id:    "src-services-domain",
          kind:  "items",
          icon:  "🧠",
          title: "Business Logic (src/services/ + src/domain/)",
          items: [
            { icon: "🤖", iconTone: "is-module", title: "services/ai/chat_service.py",   description: "AI 对话服务 · 转发至 Ollama",                          meta: "<span class=\"accent\">Service</span> · src/services/ai/" },
            { icon: "🗄", iconTone: "is-module", title: "services/database/",             description: "data_service + mongo_store + session_service · MongoDB 包装", meta: "<span class=\"accent\">Service</span> · src/services/database/" },
            { icon: "⚙️", iconTone: "is-module", title: "services/execution/executor.py", description: "模块执行引擎 · allowlist · SSE 流式分发",          meta: "<span class=\"accent\">Service</span> · src/services/execution/" },
            { icon: "📡", iconTone: "is-module", title: "services/rss/",                 description: "feed_service + rss_scheduler · APScheduler 定时拉取",  meta: "<span class=\"accent\">Service</span> · src/services/rss/" },
            { icon: "🗃", iconTone: "is-module", title: "services/state/",               description: "skill_recorder + state_service · KV 记录服务",          meta: "<span class=\"accent\">Service</span> · src/services/state/" },
            { icon: "📦", iconTone: "is-module", title: "services/storage/oss_client.py", description: "阿里云 OSS 客户端 · 上传/删除",                      meta: "<span class=\"accent\">Service</span> · src/services/storage/" },
            { icon: "🏭", iconTone: "is-module", title: "domain/execution/executor.py",   description: "域层执行器 · 调用 allow-listed Python 模块/方法",      meta: "<span class=\"accent\">Domain</span> · src/domain/execution/" },
            { icon: "📥", iconTone: "is-module", title: "domain/files/storage.py",       description: "域层 OSS 上传 · upload_bytes_to_oss",                  meta: "<span class=\"accent\">Domain</span> · src/domain/files/" },
            { icon: "🔄", iconTone: "is-module", title: "domain/rss/",                   description: "feed + scheduler · RSS 拉取/解析/入库",                meta: "<span class=\"accent\">Domain</span> · src/domain/rss/" },
            { icon: "💾", iconTone: "is-module", title: "domain/state/",                 description: "adapters + recorder + store · 状态 KV 域层",           meta: "<span class=\"accent\">Domain</span> · src/domain/state/" },
            { icon: "🤖", iconTone: "is-module", title: "domain/ai/chat.py",            description: "AI chat 域逻辑 · Ollama 包装",                          meta: "<span class=\"accent\">Domain</span> · src/domain/ai/" }
          ]
        },
        {
          id:    "src-data-models-observer",
          kind:  "items",
          icon:  "🛠",
          title: "Data / Models / Observer / Shared",
          items: [
            { icon: "🔌", iconTone: "is-module", title: "data/database.py",     description: "Motor async MongoDB 单例 · db.initialize / db.close", meta: "<span class=\"accent\">Data</span> · src/data/database.py" },
            { icon: "📦", iconTone: "is-module", title: "data/repository.py",   description: "通用 Mongo repository 抽象",                          meta: "<span class=\"accent\">Data</span> · src/data/repository.py" },
            { icon: "🗂", iconTone: "is-module", title: "data/sessions.py",     description: "sessions 集合 CRUD",                                   meta: "<span class=\"accent\">Data</span> · src/data/sessions.py" },
            { icon: "📚", iconTone: "is-module", title: "data/store.py",         description: "通用存储抽象",                                          meta: "<span class=\"accent\">Data</span> · src/data/store.py" },
            { icon: "📐", iconTone: "is-module", title: "models/schemas.py",    description: "Pydantic BaseModel · ExecuteRequest / FileUploadRequest / StateRecord…", meta: "<span class=\"accent\">Schema</span> · src/models/schemas.py" },
            { icon: "🏷", iconTone: "is-module", title: "models/collections.py", description: "MongoDB 集合名常量 · chat_records / seeds / oss_file_tags…",     meta: "<span class=\"accent\">Schema</span> · src/models/collections.py" },
            { icon: "🛡", iconTone: "is-module", title: "observer/guard.py",    description: "ReentrancyGuard · max_depth=3 防递归爆炸",            meta: "<span class=\"accent\">Reliability</span> · src/observer/guard.py" },
            { icon: "⏱", iconTone: "is-module", title: "observer/throttle.py",  description: "ThrottleMiddleware · 限流 (max_requests / window_seconds)", meta: "<span class=\"accent\">Reliability</span> · src/observer/throttle.py" },
            { icon: "📊", iconTone: "is-module", title: "observer/sampler.py",   description: "TailSampler · 慢请求采样 (slow_threshold_ms)",        meta: "<span class=\"accent\">Reliability</span> · src/observer/sampler.py" },
            { icon: "🔲", iconTone: "is-module", title: "observer/sandbox.py",   description: "SandboxMiddleware · fs/network allowlist",            meta: "<span class=\"accent\">Reliability</span> · src/observer/sandbox.py" },
            { icon: "💤", iconTone: "is-module", title: "observer/lazy_start.py", description: "延迟初始化 · observer 组件按需启动",                   meta: "<span class=\"accent\">Reliability</span> · src/observer/lazy_start.py" },
            { icon: "🔧", iconTone: "is-module", title: "shared/config.py",      description: "Settings 单例 · 加载 config.yaml + .env",              meta: "<span class=\"accent\">Shared</span> · src/shared/config.py" },
            { icon: "❗", iconTone: "is-module", title: "shared/error_codes.py", description: "ErrorCode 枚举 · 业务错误码集中定义",                 meta: "<span class=\"accent\">Shared</span> · src/shared/error_codes.py" },
            { icon: "🚨", iconTone: "is-module", title: "shared/exceptions.py",  description: "BusinessException · 业务异常基类",                    meta: "<span class=\"accent\">Shared</span> · src/shared/exceptions.py" },
            { icon: "📝", iconTone: "is-module", title: "shared/logging.py",     description: "setup_logging · 统一日志配置",                          meta: "<span class=\"accent\">Shared</span> · src/shared/logging.py" },
            { icon: "✅", iconTone: "is-module", title: "shared/response.py",   description: "success / fail 响应包装",                              meta: "<span class=\"accent\">Shared</span> · src/shared/response.py" },
            { icon: "🧰", iconTone: "is-module", title: "shared/utils.py",       description: "get_current_time 等通用工具",                          meta: "<span class=\"accent\">Shared</span> · src/shared/utils.py" }
          ]
        }
      ]
    }
  ],

  footerLinks: [
    { label: "YiAi Project", href: "../../YiAi/index.html", targetBlank: true },
    { label: "CLAUDE.md",  href: "CLAUDE.md",        targetBlank: true },
    { label: "README.md",  href: "README.md",        targetBlank: true },
    { label: "Story Report →", href: "story/index.html" }
  ]
};
