/**
 * YiAi · Dashboard data model
 * Generated by rui-init pipeline (detect → explore → generate → arch → verify)
 */
window.HELP_CONFIG = {
  titleIcon:     "★",
  title:         "YiAi",
  tagline:       "YiPet AI 服务 API · FastAPI + MongoDB 后端 · 模块化执行引擎 + AI 对话 + RSS 订阅 + OSS 存储",
  backTopLabel:  "返回顶部",
  footerNote:    "由 rui-init 管道自动生成 · detect → explore → generate → arch → verify · 基于 YiAi v1.0.0",

  breadcrumb: [
    { label: "YiDoc",    href: "../../index.html" },
    { label: "Projects", href: "../index.html" },
    { label: "YiAi" }
  ],

  stats: [
    { value: "19", label: "Runtime Deps", modifier: "cyan",   sub: "dependencies" },
    { value: "0",  label: "Dev Deps",     modifier: "cyan",   sub: "dependencies" },
    { value: "11", label: "Stories",      modifier: "accent", sub: "scenes" },
    { value: "47", label: "Source Files", modifier: "accent", sub: "modules" }
  ],

  panelHub: {
    label: { text: '📊', panel: 'reports', title: 'Report Dashboards' },
    targetBlank: true,
    buttons: [
      { icon: '🏛', name: 'Architecture',  desc: '系统架构知识',   color: 'var(--rui-accent)', panel: 'arch' },
      { icon: '✅', name: 'Test',          desc: '自检策略',       color: 'var(--rui-cyan)',   panel: 'test', targetBlank: false },
    ],
    flow: 'Architecture Review → Self-Check → Code Review → Health Audit',
    urls: {
      arch: 'arch/index.html',
      'test': 'test/index.html',
    },
  },

  sections: [
    // ── § 1 · Third-party dependencies & frameworks ────────────────────
    {
      id:    "section-dependencies",
      badge: "1",
      title: "Third-Party Dependencies / Frameworks",
      meta:  "19 runtime · 0 dev deps",
      groups: [
        {
          id:    "deps-runtime",
          kind:  "items",
          icon:  "📦",
          title: "Runtime Dependencies (19)",
          items: [
            {
              icon:        "F",
              iconTone:    "is-module",
              title:       "FastAPI",
              description: "高性能 Web 框架 · <strong>核心 API 引擎</strong>",
              meta:        "<span class=\"accent\">Runtime</span> · >=0.104.0"
            },
            {
              icon:        "U",
              iconTone:    "is-module",
              title:       "Uvicorn",
              description: "ASGI 服务器 · <strong>生产级并发</strong>",
              meta:        "<span class=\"accent\">Runtime</span> · >=0.24.0"
            },
            {
              icon:        "P",
              iconTone:    "is-module",
              title:       "Pydantic",
              description: "数据验证与序列化 · <strong>请求/响应模型</strong>",
              meta:        "<span class=\"accent\">Runtime</span> · >=2.0.0"
            },
            {
              icon:        "S",
              iconTone:    "is-module",
              title:       "pydantic-settings",
              description: "配置管理 · <strong>YAML + 环境变量</strong>",
              meta:        "<span class=\"accent\">Runtime</span> · >=2.0.0"
            },
            {
              icon:        "M",
              iconTone:    "is-module",
              title:       "Motor",
              description: "MongoDB 异步驱动 · <strong>连接池 + 索引管理</strong>",
              meta:        "<span class=\"accent\">Runtime</span> · >=3.3.0"
            },
            {
              icon:        "P",
              iconTone:    "is-module",
              title:       "PyMongo",
              description: "MongoDB 同步驱动 · <strong>Motor 依赖</strong>",
              meta:        "<span class=\"accent\">Runtime</span> · >=4.6.0"
            },
            {
              icon:        "D",
              iconTone:    "is-module",
              title:       "python-dotenv",
              description: "环境变量加载 · <strong>.env 文件解析</strong>",
              meta:        "<span class=\"accent\">Runtime</span> · >=1.0.0"
            },
            {
              icon:        "O",
              iconTone:    "is-module",
              title:       "Ollama",
              description: "本地 LLM 客户端 · <strong>qwen3.5 / qwen3-vl 推理</strong>",
              meta:        "<span class=\"accent\">Runtime</span> · >=0.1.0"
            },
            {
              icon:        "A",
              iconTone:    "is-module",
              title:       "aiohttp",
              description: "异步 HTTP 客户端 · <strong>RSS 抓取 / Webhook / 图片下载</strong>",
              meta:        "<span class=\"accent\">Runtime</span> · >=3.9.0"
            },
            {
              icon:        "R",
              iconTone:    "is-module",
              title:       "feedparser",
              description: "RSS/Atom 解析 · <strong>信息聚合订阅</strong>",
              meta:        "<span class=\"accent\">Runtime</span> · >=6.0.10"
            },
            {
              icon:        "S",
              iconTone:    "is-module",
              title:       "APScheduler",
              description: "任务调度器 · <strong>RSS 定时抓取</strong>",
              meta:        "<span class=\"accent\">Runtime</span> · >=3.10.0"
            },
            {
              icon:        "Q",
              iconTone:    "is-module",
              title:       "qwen-vl-utils",
              description: "Qwen-VL 工具库 · <strong>多模态视觉模型</strong>",
              meta:        "<span class=\"accent\">Runtime</span> · >=0.0.14"
            },
            {
              icon:        "T",
              iconTone:    "is-module",
              title:       "Transformers",
              description: "HuggingFace 模型库 · <strong>ML 管线</strong>",
              meta:        "<span class=\"accent\">Runtime</span> · >=4.37.0"
            },
            {
              icon:        "Y",
              iconTone:    "is-module",
              title:       "PyYAML",
              description: "YAML 解析 · <strong>config.yaml 配置源</strong>",
              meta:        "<span class=\"accent\">Runtime</span> · >=6.0"
            },
            {
              icon:        "O",
              iconTone:    "is-module",
              title:       "oss2",
              description: "阿里云 OSS SDK · <strong>对象存储上传/删除</strong>",
              meta:        "<span class=\"accent\">Runtime</span> · >=2.18.0"
            },
            {
              icon:        "M",
              iconTone:    "is-module",
              title:       "python-multipart",
              description: "多部分表单解析 · <strong>文件上传支持</strong>",
              meta:        "<span class=\"accent\">Runtime</span> · >=0.0.9"
            },
            {
              icon:        "A",
              iconTone:    "is-module",
              title:       "aiofiles",
              description: "异步文件 I/O · <strong>非阻塞读写</strong>",
              meta:        "<span class=\"accent\">Runtime</span> · >=23.2.1"
            },
            {
              icon:        "T",
              iconTone:    "is-module",
              title:       "Tenacity",
              description: "重试库 · <strong>指数退避 + 重试策略</strong>",
              meta:        "<span class=\"accent\">Runtime</span> · >=8.2.3"
            },
            {
              icon:        "T",
              iconTone:    "is-module",
              title:       "Typer + Rich",
              description: "CLI 框架 + 终端美化 · <strong>state_query 命令行</strong>",
              meta:        "<span class=\"accent\">Runtime</span> · typer>=0.9.0 · rich>=13.0.0"
            }
          ]
        },
        {
          id:    "deps-dev",
          kind:  "items",
          icon:  "🛠",
          title: "Dev Dependencies (0)",
          items: []
        }
      ]
    },

    // ── § 2 · Story documents & scenes ─────────────────────────────────
    {
      id:    "section-stories",
      badge: "2",
      title: "Story Documents & Scenes",
      meta:  "2 stories · 11 scenes · arch + test",
      groups: [
        {
          kind:  "stories",
          icon:  "📚",
          title: "Story Catalog (arch + test)",
          items: [
            {
              icon:        "🏛",
              title:       "System Architecture & Knowledge Codification",
              badge:       "5 scenes",
              description: "FastAPI 端到端请求追踪 · <strong>5 个验证场景</strong> · 模块定位 · 数据流 · 新人入职 · 依赖影响 · 安全边界",
              sceneLinks: [
                { label: "1. Module Location",          href: "arch/scene-1-module-location/index.md" },
                { label: "2. Data Flow Tracing",         href: "arch/scene-2-data-flow-tracing/index.md" },
                { label: "3. Newcomer Onboarding",      href: "arch/scene-3-newcomer-onboarding/index.md" },
                { label: "4. Dependency Impact",         href: "arch/scene-4-dependency-change-impact/index.md" },
                { label: "5. Security Surface",         href: "arch/scene-5-trust-boundary-security-surface/index.md" }
              ],
              links: [
                { label: "Architecture Dashboard →", href: "arch/index.html" }
              ],
              meta: "5 scenes · risk: medium · Python/FastAPI/MongoDB"
            },
            {
              icon:        "✅",
              title:       "Automation Self-Check Suite",
              badge:       "6 scenes",
              description: "项目自检策略 · <strong>6 个测试场景</strong> · 全量自检 · 增量提交 · 文档一致性 · 安全回归 · 跨故事集成 · 第三方服务",
              sceneLinks: [
                { label: "1. Post-Init Self-Check",    href: "test/scene-1-post-init-full-self-check/index.md" },
                { label: "2. Pre-Commit Self-Check",  href: "test/scene-2-pre-commit-incremental-self-check/index.md" },
                { label: "3. Doc Consistency",         href: "test/scene-3-doc-code-consistency/index.md" },
                { label: "4. Security Regression",     href: "test/scene-4-security-surface-regression/index.md" },
                { label: "5. Integration Regression",  href: "test/scene-5-cross-story-integration-regression/index.md" },
                { label: "6. Third-Party Services",   href: "test/scene-6-third-party-framework-service/index.md" }
              ],
              links: [
                { label: "Test Dashboard →", href: "test/index.html" }
              ],
              meta: "6 scenes · risk: low · 无自动化测试框架 · 需手动验证"
            }
          ]
        }
      ]
    },

    // ── § 3 · Main source code ─────────────────────────────────────────
    {
      id:    "section-source",
      badge: "3",
      title: "Main Source Code",
      meta:  "47 Python modules across 5 top-level packages",
      groups: [
        {
          id:    "src-api",
          kind:  "items",
          icon:  "🌐",
          title: "API Layer — Routes & Endpoints (9 files)",
          items: [
            { icon: "📁", iconTone: "is-module", title: "api/__init__.py",        description: "API 层包入口 · <strong>routes 与依赖</strong>",          meta: "<span class=\"accent\">API</span> · src/api/__init__.py" },
            { icon: "📁", iconTone: "is-module", title: "routes/__init__.py",     description: "路由子包入口",                                               meta: "<span class=\"accent\">API</span> · src/api/routes/__init__.py" },
            { icon: "⚙️",  iconTone: "is-module", title: "routes/execution.py",    description: "模块执行 API · <strong>GET/POST 通用执行入口 + SSE 流</strong>", meta: "<span class=\"accent\">API</span> · src/api/routes/execution.py" },
            { icon: "📤", iconTone: "is-module", title: "routes/upload.py",       description: "文件上传/读写/删除/重命名 · <strong>磁盘 + MongoDB 双持久化</strong>", meta: "<span class=\"accent\">API</span> · src/api/routes/upload.py" },
            { icon: "🔧", iconTone: "is-module", title: "routes/maintenance.py",  description: "系统维护 API · <strong>图片清理 + session 清理</strong>",    meta: "<span class=\"accent\">API</span> · src/api/routes/maintenance.py" },
            { icon: "📊", iconTone: "is-module", title: "routes/state.py",        description: "状态存储 CRUD API · <strong>结构化状态记录管理</strong>",     meta: "<span class=\"accent\">API</span> · src/api/routes/state.py" },
            { icon: "🤖", iconTone: "is-module", title: "routes/wework.py",       description: "企业微信 Webhook · <strong>消息推送</strong>",              meta: "<span class=\"accent\">API</span> · src/api/routes/wework.py" },
            { icon: "❤️",  iconTone: "is-module", title: "routes/observer_health.py", description: "Observer 健康检查 API · <strong>限流/采样/沙箱状态</strong>", meta: "<span class=\"accent\">API</span> · src/api/routes/observer_health.py" },
            { icon: "📋", iconTone: "is-module", title: "routes/story_panel.py",  description: "故事面板 API · <strong>Markdown 文档 CRUD + git 同步</strong>", meta: "<span class=\"accent\">API</span> · src/api/routes/story_panel.py" }
          ]
        },
        {
          id:    "src-cli",
          kind:  "items",
          icon:  "🖥",
          title: "CLI Layer — 命令行工具 (2 files)",
          items: [
            { icon: "📁", iconTone: "is-module", title: "cli/__init__.py",       description: "CLI 工具包入口",                                            meta: "<span class=\"accent\">CLI</span> · src/cli/__init__.py" },
            { icon: "🔍", iconTone: "is-module", title: "cli/state_query.py",    description: "状态查询 CLI · <strong>Typer + Rich 表格/json/csv 输出</strong>", meta: "<span class=\"accent\">CLI</span> · src/cli/state_query.py" }
          ]
        },
        {
          id:    "src-core",
          kind:  "items",
          icon:  "⚙️",
          title: "Core Infrastructure — 配置/数据库/中间件 (16 files)",
          items: [
            { icon: "📁", iconTone: "is-module", title: "core/__init__.py",             description: "核心基础设施包入口",                                          meta: "<span class=\"accent\">Core</span> · src/core/__init__.py" },
            { icon: "⚙️",  iconTone: "is-module", title: "core/config.py",              description: "配置管理 · <strong>YAML + env + pydantic-settings</strong>", meta: "<span class=\"accent\">Core</span> · src/core/config.py" },
            { icon: "🗄",  iconTone: "is-module", title: "core/database.py",            description: "MongoDB 单例 · <strong>连接池 + 索引 + CRUD 包装</strong>",   meta: "<span class=\"accent\">Core</span> · src/core/database.py" },
            { icon: "🔐", iconTone: "is-module", title: "core/middleware.py",           description: "X-Token 认证中间件 · <strong>白名单 + CORS</strong>",        meta: "<span class=\"accent\">Core</span> · src/core/middleware.py" },
            { icon: "⚠️",  iconTone: "is-module", title: "core/exceptions.py",          description: "BusinessException · <strong>统一异常定义</strong>",            meta: "<span class=\"accent\">Core</span> · src/core/exceptions.py" },
            { icon: "🔢", iconTone: "is-module", title: "core/error_codes.py",          description: "ErrorCode 枚举 · <strong>标准化错误码</strong>",               meta: "<span class=\"accent\">Core</span> · src/core/error_codes.py" },
            { icon: "🛡",  iconTone: "is-module", title: "core/exception_handler.py",   description: "全局异常处理器 · <strong>FastAPI exception_handlers</strong>", meta: "<span class=\"accent\">Core</span> · src/core/exception_handler.py" },
            { icon: "📝", iconTone: "is-module", title: "core/logger.py",               description: "日志配置 · <strong>uvicorn propagation 控制</strong>",        meta: "<span class=\"accent\">Core</span> · src/core/logger.py" },
            { icon: "📬", iconTone: "is-module", title: "core/response.py",             description: "统一响应格式 · <strong>success/fail 包装</strong>",            meta: "<span class=\"accent\">Core</span> · src/core/response.py" },
            { icon: "🧰", iconTone: "is-module", title: "core/utils.py",                description: "工具函数 · <strong>时间格式化等</strong>",                    meta: "<span class=\"accent\">Core</span> · src/core/utils.py" },
            { icon: "📁", iconTone: "is-module", title: "observer/__init__.py",        description: "Observer 组件包 · <strong>限流/采样/沙箱/守卫/懒启动</strong>", meta: "<span class=\"accent\">Core</span> · src/core/observer/__init__.py" },
            { icon: "🚦", iconTone: "is-module", title: "observer/throttle.py",         description: "IP 限流中间件 · <strong>滑动窗口 + 白名单</strong>",          meta: "<span class=\"accent\">Core</span> · src/core/observer/throttle.py" },
            { icon: "📊", iconTone: "is-module", title: "observer/sampler.py",          description: "请求采样器 · <strong>TailSampler + 慢请求阈值</strong>",       meta: "<span class=\"accent\">Core</span> · src/core/observer/sampler.py" },
            { icon: "🏖",  iconTone: "is-module", title: "observer/sandbox.py",         description: "代码沙箱 · <strong>文件系统 + 网络隔离</strong>",              meta: "<span class=\"accent\">Core</span> · src/core/observer/sandbox.py" },
            { icon: "🛡",  iconTone: "is-module", title: "observer/guard.py",           description: "重入守卫 · <strong>调用深度限制</strong>",                     meta: "<span class=\"accent\">Core</span> · src/core/observer/guard.py" },
            { icon: "🐢", iconTone: "is-module", title: "observer/lazy_start.py",      description: "懒启动管理器 · <strong>延迟初始化</strong>",                    meta: "<span class=\"accent\">Core</span> · src/core/observer/lazy_start.py" }
          ]
        },
        {
          id:    "src-models",
          kind:  "items",
          icon:  "📐",
          title: "Data Models — Pydantic Schemas (3 files)",
          items: [
            { icon: "📁", iconTone: "is-module", title: "models/__init__.py",     description: "数据模型包入口 · <strong>schemas + collections 导出</strong>", meta: "<span class=\"accent\">Models</span> · src/models/__init__.py" },
            { icon: "📋", iconTone: "is-module", title: "models/schemas.py",      description: "Pydantic 请求模型 · <strong>Execute/Upload/State/WeWork 请求</strong>", meta: "<span class=\"accent\">Models</span> · src/models/schemas.py" },
            { icon: "🗂",  iconTone: "is-module", title: "models/collections.py",  description: "MongoDB 集合名常量 · <strong>8 个业务集合</strong>",          meta: "<span class=\"accent\">Models</span> · src/models/collections.py" }
          ]
        },
        {
          id:    "src-services",
          kind:  "items",
          icon:  "🔧",
          title: "Business Services — 业务逻辑层 (14 files)",
          items: [
            { icon: "📁", iconTone: "is-module", title: "services/__init__.py",              description: "业务服务包入口",                                               meta: "<span class=\"accent\">Services</span> · src/services/__init__.py" },
            { icon: "🤖", iconTone: "is-module", title: "ai/chat_service.py",                description: "Ollama AI 聊天服务 · <strong>文本生成 + 多模态 + SSE 流</strong>", meta: "<span class=\"accent\">Services</span> · src/services/ai/chat_service.py" },
            { icon: "🗄",  iconTone: "is-module", title: "database/data_service.py",         description: "通用数据服务",                                                 meta: "<span class=\"accent\">Services</span> · src/services/database/data_service.py" },
            { icon: "🗄",  iconTone: "is-module", title: "database/mongo_store.py",          description: "MongoDB 存储抽象",                                             meta: "<span class=\"accent\">Services</span> · src/services/database/mongo_store.py" },
            { icon: "🚀", iconTone: "is-module", title: "execution/executor.py",             description: "模块执行引擎 · <strong>白名单校验 + 沙箱 + 重入守卫</strong>",   meta: "<span class=\"accent\">Services</span> · src/services/execution/executor.py" },
            { icon: "🔧", iconTone: "is-module", title: "maintenance/session_service.py",    description: "Session 管理服务 · <strong>CRUD + 清理</strong>",              meta: "<span class=\"accent\">Services</span> · src/services/maintenance/session_service.py" },
            { icon: "📡", iconTone: "is-module", title: "rss/feed_service.py",               description: "RSS 解析服务 · <strong>aiohttp 抓取 + feedparser 解析</strong>", meta: "<span class=\"accent\">Services</span> · src/services/rss/feed_service.py" },
            { icon: "⏰", iconTone: "is-module", title: "rss/rss_scheduler.py",              description: "RSS 调度器 · <strong>APScheduler 定时任务</strong>",          meta: "<span class=\"accent\">Services</span> · src/services/rss/rss_scheduler.py" },
            { icon: "📁", iconTone: "is-module", title: "state/__init__.py",                 description: "状态服务子包入口",                                             meta: "<span class=\"accent\">Services</span> · src/services/state/__init__.py" },
            { icon: "💾", iconTone: "is-module", title: "state/state_service.py",            description: "状态存储服务 · <strong>CRUD + 分页查询 + TTL</strong>",        meta: "<span class=\"accent\">Services</span> · src/services/state/state_service.py" },
            { icon: "📝", iconTone: "is-module", title: "state/skill_recorder.py",           description: "技能调用记录器 · <strong>执行追踪</strong>",                    meta: "<span class=\"accent\">Services</span> · src/services/state/skill_recorder.py" },
            { icon: "🔗", iconTone: "is-module", title: "state/session_adapters.py",         description: "Session 适配器",                                               meta: "<span class=\"accent\">Services</span> · src/services/state/session_adapters.py" },
            { icon: "☁️",  iconTone: "is-module", title: "storage/oss_client.py",            description: "阿里云 OSS 客户端 · <strong>文件上传/删除/标签</strong>",       meta: "<span class=\"accent\">Services</span> · src/services/storage/oss_client.py" },
            { icon: "📄", iconTone: "is-module", title: "static/static_files.py",            description: "静态文件服务 · <strong>磁盘 + OSS 双层存储</strong>",          meta: "<span class=\"accent\">Services</span> · src/services/static/static_files.py" }
          ]
        },
        {
          id:    "src-entry",
          kind:  "items",
          icon:  "🚀",
          title: "Entry Points (3 files)",
          items: [
            { icon: "🟢", iconTone: "is-module", title: "src/__init__.py",         description: "包版本声明 · <strong>__version__ = 1.0.0</strong>",           meta: "<span class=\"accent\">Entry</span> · src/__init__.py" },
            { icon: "🟢", iconTone: "is-module", title: "src/main.py",             description: "FastAPI 应用工厂 · <strong>create_app + lifespan + CORS</strong>", meta: "<span class=\"accent\">Entry</span> · src/main.py" },
            { icon: "🟢", iconTone: "is-module", title: "src/__main__.py",         description: "python -m 入口 · <strong>uvicorn.run</strong>",              meta: "<span class=\"accent\">Entry</span> · src/__main__.py" }
          ]
        }
      ]
    }
  ],

  footerLinks: [
    { label: "YiDoc Home",  href: "../../index.html",   targetBlank: false },
    { label: "Projects",    href: "../index.html",      targetBlank: false },
    { label: "YiAi Root",   href: "../../../YiAi/",     targetBlank: true },
    { label: "CLAUDE.md",   href: "../../../YiAi/CLAUDE.md", targetBlank: true }
  ]
};
