/**
 * YiPet · Dashboard data model
 * --------------------------------------------------------------------------
 * Generated by yry-init pipeline (steps 01-05).
 * Consumed by the yry-init standalone dashboard template.
 * Exposed as window.HELP_CONFIG.
 *
 * Rebuild: 2026-07-24 · full yry-init rebuild.
 */

window.HELP_CONFIG = {
  titleIcon:     "🐾",
  title:         "YiPet · AI Chrome Extension",
  tagline:       "温柔陪伴助手 · Manifest V3 Content Script · IIFE 模块化 · 共享原型工具方法 · 26 CDN 组件 · 49 第三方库 · 275 源文件 · 全量自托管",
  backTopLabel:  "返回顶部",
  footerNote:    "由 yry-init 流水线生成 (detect → explore → generate → arch → verify) · 项目根: /Users/ruiyi/Downloads/YrY/YiDoc/projects/YiPet/ · 代码已消除重复冗余",

  breadcrumb: [
    { label: "YiDoc", href: "../../index.html" },
    { label: "Projects", href: "../../dashboard/index.html" },
    { label: "YiPet" }
  ],

  stats: [
    { value: "26",  label: "CDN 组件",  modifier: "accent", sub: "yry-* + Yi* + business" },
    { value: "49",  label: "第三方库",  modifier: "cyan",   sub: "vendored under libs/" },
    { value: "4",   label: "业务模块",  modifier: "accent", sub: "core / extension / pet / faq" },
    { value: "275", label: "源文件",    modifier: "accent", sub: "205 JS + 70 CSS" }
  ],

  panelHub: {
    label: { text: '📊', panel: 'reports', title: 'YiPet 文档导航' },
    targetBlank: false,
    buttons: [
      { icon: '🏛', name: 'Architecture', desc: '6 个架构场景',    color: 'var(--yry-accent)', panel: 'arch' },
      { icon: '✅', name: 'Self-Check',    desc: '6 个自检场景',   color: 'var(--yry-cyan)',   panel: 'test' },
      { icon: '📁', name: 'Files',          desc: '563 文件 · 21.8 MB', color: 'var(--yry-info)', panel: 'files' },
      { icon: '🔌', name: 'APIs',           desc: '33 端点 · 48 分',   color: 'var(--yry-warn)',  panel: 'apis' },
    ],
    flow: '架构分析 → 自检策略 → 文件体检 → API 审计',
    urls: {
      arch:  '../../templates/arch/index.html?project=YiPet',
      test:  '../../templates/test/index.html?project=YiPet',
      files: '../../templates/files/index.html?project=YiPet',
      apis:  '../../templates/apis/index.html?project=YiPet',
      daily: '../../templates/daily/cto-report.html?project=YiPet',
    },
  },

  reportsList: {
    daily: [],
    weekly: [],
    monthly: [],
  },

  // ── § 1 · Third-party dependencies & frameworks ────────────────────
  sections: [
    {
      id:    "section-dependencies",
      badge: "1",
      title: "Third-Party Dependencies / Frameworks",
      meta:  "49 libraries · 26 CDN components · all self-hosted",
      groups: [
        {
          id:    "deps-runtime",
          kind:  "items",
          icon:  "📦",
          title: "Core Runtime Libraries (12)",
          items: [
            {
              icon:        "V",
              iconTone:    "is-module",
              title:       "Vue 3",
              description: "Progressive UI framework · <strong>驱动 ChatWindow 等组件</strong> · 通过 vue.global.js 全局引入",
              meta:        "<span class=\"accent\">Runtime</span> · ^3.x"
            },
            {
              icon:        "J",
              iconTone:    "is-module",
              title:       "jQuery",
              description: "DOM 操作 & 事件处理 · <strong>多个 jQuery 插件的基础依赖</strong>",
              meta:        "<span class=\"accent\">Runtime</span> · 3.7.1"
            },
            {
              icon:        "B",
              iconTone:    "is-module",
              title:       "Bootstrap 5",
              description: "CSS 框架 · <strong>栅格 + 组件样式</strong> · bootstrap.bundle.min.js",
              meta:        "<span class=\"accent\">Runtime</span> · 5.2.3"
            },
            {
              icon:        "M",
              iconTone:    "is-module",
              title:       "Mermaid",
              description: "图表渲染引擎 · <strong>流程图 / 时序图 / ER 图</strong> · 聊天消息内动态渲染",
              meta:        "<span class=\"accent\">Runtime</span> · 11.x"
            },
            {
              icon:        "m",
              iconTone:    "is-module",
              title:       "marked",
              description: "Markdown 解析器 · <strong>CDN markdown 渲染引擎的基础</strong>",
              meta:        "<span class=\"accent\">Runtime</span> · 最新"
            },
            {
              icon:        "T",
              iconTone:    "is-module",
              title:       "Turndown",
              description: "HTML → Markdown 转换 · <strong>富文本消息的标准化处理</strong>",
              meta:        "<span class=\"accent\">Runtime</span> · 最新"
            },
            {
              icon:        "A",
              iconTone:    "is-module",
              title:       "ApexCharts",
              description: "SVG 图表库 · <strong>数据可视化</strong>",
              meta:        "<span class=\"accent\">Runtime</span> · 3.46.0"
            },
            {
              icon:        "G",
              iconTone:    "is-module",
              title:       "GSAP",
              description: "高性能动画引擎 · <strong>宠物动画 & 过渡效果</strong>",
              meta:        "<span class=\"accent\">Runtime</span> · 最新"
            },
            {
              icon:        "S",
              iconTone:    "is-module",
              title:       "Swiper",
              description: "触摸滑块 · <strong>轮播组件</strong>",
              meta:        "<span class=\"accent\">Runtime</span> · 7.0.3"
            },
            {
              icon:        "X",
              iconTone:    "is-module",
              title:       "XLSX (SheetJS)",
              description: "Excel 文件读写 · <strong>数据导出</strong>",
              meta:        "<span class=\"accent\">Runtime</span> · 0.20.3"
            },
            {
              icon:        "H",
              iconTone:    "is-module",
              title:       "html2canvas",
              description: "DOM → Canvas 截图 · <strong>页面截图功能</strong>",
              meta:        "<span class=\"accent\">Runtime</span> · 1.4.1"
            },
            {
              icon:        "L",
              iconTone:    "is-module",
              title:       "Leaflet",
              description: "交互地图 · <strong>位置相关功能</strong>",
              meta:        "<span class=\"accent\">Runtime</span> · 1.1.1"
            }
          ]
        },
        {
          id:    "deps-extra",
          kind:  "items",
          icon:  "🧩",
          title: "Additional UI & Utility Libraries (37)",
          items: [
            {
              icon:        "F",
              iconTone:    "is-module",
              title:       "Font Awesome",
              description: "矢量图标字体 · <strong>UI 图标</strong>",
              meta:        "<span class=\"accent\">Runtime</span> · 4.7.0"
            },
            {
              icon:        "O",
              iconTone:    "is-module",
              title:       "Owl Carousel",
              description: "jQuery 轮播插件",
              meta:        "<span class=\"accent\">Runtime</span> · 2.2.1"
            },
            {
              icon:        "A",
              iconTone:    "is-module",
              title:       "Animate.css",
              description: "CSS 动画库 · <strong>预设动画类</strong>",
              meta:        "<span class=\"accent\">Runtime</span> · 3.5.1"
            },
            {
              icon:        "A",
              iconTone:    "is-module",
              title:       "Anime.js",
              description: "JS 动画引擎 · <strong>轻量级补间动画</strong>",
              meta:        "<span class=\"accent\">Runtime</span> · 3.0.0"
            },
            {
              icon:        "A",
              iconTone:    "is-module",
              title:       "AOS",
              description: "滚动动画库 · <strong>视口触发动画</strong>",
              meta:        "<span class=\"accent\">Runtime</span>"
            },
            {
              icon:        "W",
              iconTone:    "is-module",
              title:       "WOW.js",
              description: "滚动时触发 CSS 动画",
              meta:        "<span class=\"accent\">Runtime</span> · 1.1.3"
            },
            {
              icon:        "T",
              iconTone:    "is-module",
              title:       "Typed.js",
              description: "打字机效果 · <strong>逐字显示文本</strong>",
              meta:        "<span class=\"accent\">Runtime</span> · 2.0.11"
            },
            {
              icon:        "I",
              iconTone:    "is-module",
              title:       "Isotope",
              description: "过滤 & 排序布局 · <strong>网格布局</strong>",
              meta:        "<span class=\"accent\">Runtime</span> · 3.0.6"
            },
            {
              icon:        "P",
              iconTone:    "is-module",
              title:       "Perfect Scrollbar",
              description: "自定义滚动条",
              meta:        "<span class=\"accent\">Runtime</span> · 1.5.0"
            },
            {
              icon:        "F",
              iconTone:    "is-module",
              title:       "Fancybox",
              description: "灯箱效果 · <strong>图片/视频弹窗</strong>",
              meta:        "<span class=\"accent\">Runtime</span> · 3.5.7"
            },
            {
              icon:        "V",
              iconTone:    "is-module",
              title:       "Venobox",
              description: "响应式灯箱插件",
              meta:        "<span class=\"accent\">Runtime</span> · 1.7.3"
            },
            {
              icon:        "W",
              iconTone:    "is-module",
              title:       "Waypoints",
              description: "滚动触发的回调",
              meta:        "<span class=\"accent\">Runtime</span> · 4.0.0"
            }
          ]
        }
      ]
    },

    // ── § 2 · Story documents & scenes ─────────────────────────────────
    {
      id:    "section-stories",
      badge: "2",
      title: "Story Documents & Scenes",
      meta:  "2 stories · 12 scenes · 架构 & 自检全覆盖",
      groups: [
        {
          kind:  "stories",
          icon:  "📚",
          title: "Story Catalog (arch + test)",
          items: [
            {
              icon:        "🏛",
              title:       "System Architecture & Knowledge Codification",
              badge:       "6 scenes",
              description: "模块定位 · 数据流追踪 · 新人引导 · 依赖影响评估 · 安全边界 · <strong>CDN 组件生命周期</strong>",
              sceneLinks: [
                { label: "1. Module Location",          href: "../../projects/YiPet/arch/scene-1-module-location/index.md" },
                { label: "2. Data Flow Tracing",         href: "../../projects/YiPet/arch/scene-2-data-flow-tracing/index.md" },
                { label: "3. Newcomer Onboarding",      href: "../../projects/YiPet/arch/scene-3-newcomer-onboarding/index.md" },
                { label: "4. Dependency Impact",         href: "../../projects/YiPet/arch/scene-4-dependency-change-impact/index.md" },
                { label: "5. Security Surface",         href: "../../projects/YiPet/arch/scene-5-trust-boundary-security-surface/index.md" },
                { label: "6. CDN Component Lifecycle",  href: "../../projects/YiPet/arch/scene-6-cdn-component-lifecycle/index.md" }
              ],
              links: [
                { label: "Architecture Dashboard →", href: "../../templates/arch/index.html?project=YiPet" }
              ],
              meta: "6 scenes · risk: medium · Chrome MV3 架构"
            },
            {
              icon:        "✅",
              title:       "Self-Check Strategy Suite",
              badge:       "6 scenes",
              description: "全量自检 · 增量提交检查 · 文档一致性 · 安全回归 · <strong>跨场景集成回归</strong> · 第三方服务健康度",
              sceneLinks: [
                { label: "1. Post-Init Self-Check",    href: "../../projects/YiPet/test/scene-1-post-init-full-self-check/index.md" },
                { label: "2. Pre-Commit Self-Check",  href: "../../projects/YiPet/test/scene-2-pre-commit-incremental-self-check/index.md" },
                { label: "3. Doc Consistency",         href: "../../projects/YiPet/test/scene-3-doc-code-consistency/index.md" },
                { label: "4. Security Regression",     href: "../../projects/YiPet/test/scene-4-security-surface-regression/index.md" },
                { label: "5. Integration Regression",  href: "../../projects/YiPet/test/scene-5-cross-story-integration-regression/index.md" },
                { label: "6. Third-Party Services",   href: "../../projects/YiPet/test/scene-6-third-party-framework-service/index.md" }
              ],
              links: [
                { label: "Test Dashboard →", href: "../../templates/test/index.html?project=YiPet" }
              ],
              meta: "6 scenes · risk: low · 全量自检覆盖"
            }
          ]
        }
      ]
    },

    // ── § 3 · Main source code ─────────────────────────────────────────
    {
      id:    "section-source",
      badge: "3",
      title: "Main Source Code",
      meta:  "205 JS · 70 CSS · 4 模块 · 26 CDN 组件",
      groups: [
        {
          id:    "src-core",
          kind:  "items",
          icon:  "⚙️",
          title: "Core 核心基础设施 (18)",
          items: [
            { icon: "⚙️", iconTone: "is-module", title: "config.js",              description: "全局配置 PET_CONFIG · <strong>环境/API/UI 常量</strong>", meta: "<span class=\"accent\">Core</span> · core/config.js" },
            { icon: "🔗", iconTone: "is-module", title: "ApiManager.js",          description: "API 管理器基类 · <strong>拦截器链 + Token + 重试</strong>", meta: "<span class=\"accent\">Core</span> · core/api/core/ApiManager.js" },
            { icon: "📡", iconTone: "is-module", title: "SessionService.js",       description: "会话后端服务 · CRUD + 同步", meta: "<span class=\"accent\">Core</span> · core/api/services/SessionService.js" },
            { icon: "📡", iconTone: "is-module", title: "FaqService.js",          description: "FAQ 后端服务 · 标签 & 排序管理", meta: "<span class=\"accent\">Core</span> · core/api/services/FaqService.js" },
            { icon: "🚀", iconTone: "is-module", title: "bootstrap.js",          description: "StorageHelper + 默认位置工具", meta: "<span class=\"accent\">Core</span> · core/bootstrap/bootstrap.js" },
            { icon: "🚀", iconTone: "is-module", title: "index.js (bootstrap)",  description: "PetManager 实例化 & 生命周期", meta: "<span class=\"accent\">Core</span> · core/bootstrap/index.js" },
            { icon: "📋", iconTone: "is-module", title: "endpoints.js",          description: "API 端点常量 · RESTful 路由", meta: "<span class=\"accent\">Core</span> · core/constants/endpoints.js" },
            { icon: "🔐", iconTone: "is-module", title: "token.js",              description: "Token 管理器 · X-Token 注入", meta: "<span class=\"accent\">Core</span> · core/utils/api/token.js" },
            { icon: "📝", iconTone: "is-module", title: "logger.js",             description: "API 日志器 · mute logger 支持", meta: "<span class=\"accent\">Core</span> · core/utils/api/logger.js" },
            { icon: "❌", iconTone: "is-module", title: "error.js",              description: "API 错误处理器 · 重试策略", meta: "<span class=\"accent\">Core</span> · core/utils/api/error.js" },
            { icon: "🌐", iconTone: "is-module", title: "request.js",            description: "RequestClient · fetch 封装", meta: "<span class=\"accent\">Core</span> · core/utils/api/request.js" },
            { icon: "🖼", iconTone: "is-module", title: "imageResourceManager.js", description: "图片资源加载 & 缓存", meta: "<span class=\"accent\">Core</span> · core/utils/media/imageResourceManager.js" },
            { icon: "🪄", iconTone: "is-module", title: "loadingAnimation.js",   description: "加载动画基础组件", meta: "<span class=\"accent\">Core</span> · core/utils/ui/loadingAnimation.js" }
          ]
        },
        {
          id:    "src-modules",
          kind:  "items",
          icon:  "🧩",
          title: "Modules 业务模块 (核心)",
          items: [
            { icon: "🐾", iconTone: "is-module", title: "petManager.core.js",    description: "PetManager 类定义 · <strong>状态初始化 & 生命周期</strong>", meta: "<span class=\"accent\">Pet</span> · modules/pet/content/core/" },
            { icon: "💬", iconTone: "is-module", title: "petManager.chat.js",    description: "聊天消息发送 & 流式接收", meta: "<span class=\"accent\">Pet</span> · modules/pet/content/" },
            { icon: "🖥", iconTone: "is-module", title: "petManager.ui.js",      description: "宠物 DOM 创建 & UI 更新", meta: "<span class=\"accent\">Pet</span> · modules/pet/content/" },
            { icon: "🖱", iconTone: "is-module", title: "petManager.drag.js",    description: "宠物拖拽交互", meta: "<span class=\"accent\">Pet</span> · modules/pet/content/" },
            { icon: "📊", iconTone: "is-module", title: "petManager.mermaid.js", description: "Mermaid 渲染门面", meta: "<span class=\"accent\">Pet</span> · modules/pet/content/mermaid/" },
            { icon: "🤖", iconTone: "is-module", title: "petManager.ai.api.js",  description: "AI API 调用 · 流式 prompt", meta: "<span class=\"accent\">Pet</span> · modules/pet/content/ai/" },
            { icon: "📝", iconTone: "is-module", title: "petManager.editor.js",  description: "会话编辑器 · 标题/描述修改", meta: "<span class=\"accent\">Pet</span> · modules/pet/content/editor/" },
            { icon: "🏷", iconTone: "is-module", title: "petManager.tags.js",    description: "标签管理 · 过滤 & 排序", meta: "<span class=\"accent\">Pet</span> · modules/pet/content/modules/" },
            { icon: "📦", iconTone: "is-module", title: "ChatWindow/index.js",   description: "聊天窗口 Vue 组件 · <strong>hooks 模式</strong>", meta: "<span class=\"accent\">Pet</span> · modules/pet/components/chat/" },
            { icon: "🎛", iconTone: "is-module", title: "extension/background/", description: "Service Worker · <strong>消息路由 & 注入</strong>", meta: "<span class=\"accent\">Extension</span> · modules/extension/background/" },
            { icon: "ℹ️", iconTone: "is-module", title: "extension/popup/",      description: "工具栏弹窗 · 控制面板入口", meta: "<span class=\"accent\">Extension</span> · modules/extension/popup/" },
            { icon: "❓", iconTone: "is-module", title: "faq/content/faq.js",    description: "FAQ 管理 · 问答对 CRUD", meta: "<span class=\"accent\">FAQ</span> · modules/faq/content/" }
          ]
        },
        {
          id:    "src-cdn",
          kind:  "items",
          icon:  "📦",
          title: "CDN 自建组件库 (26)",
          items: [
            { icon: "📊", iconTone: "is-module", title: "yry-scene-card",        description: "场景卡片组件 · <strong>仪表盘核心元素</strong>", meta: "<span class=\"accent\">CDN</span> · cdn/components/yry-scene-card/" },
            { icon: "📊", iconTone: "is-module", title: "yry-stats-grid",        description: "统计数据网格 · KPI 卡片", meta: "<span class=\"accent\">CDN</span> · cdn/components/yry-stats-grid/" },
            { icon: "🧭", iconTone: "is-module", title: "yry-breadcrumb",        description: "面包屑导航组件", meta: "<span class=\"accent\">CDN</span> · cdn/components/yry-breadcrumb/" },
            { icon: "🏷", iconTone: "is-module", title: "yry-tag-chip",          description: "标签芯片组件", meta: "<span class=\"accent\">CDN</span> · cdn/components/yry-tag-chip/" },
            { icon: "🔝", iconTone: "is-module", title: "yry-back-top",          description: "返回顶部按钮", meta: "<span class=\"accent\">CDN</span> · cdn/components/yry-back-top/" },
            { icon: "🎯", iconTone: "is-module", title: "yry-panel-hub",         description: "多面板导航中心", meta: "<span class=\"accent\">CDN</span> · cdn/components/yry-panel-hub/" },
            { icon: "📊", iconTone: "is-module", title: "yry-score-bar",         description: "评分进度条组件", meta: "<span class=\"accent\">CDN</span> · cdn/components/yry-score-bar/" },
            { icon: "📈", iconTone: "is-module", title: "yry-progress-bar",      description: "进度条组件", meta: "<span class=\"accent\">CDN</span> · cdn/components/yry-progress-bar/" },
            { icon: "🪟", iconTone: "is-module", title: "YiModal",               description: "模态框组件 · <strong>设置/AI配置</strong>", meta: "<span class=\"accent\">CDN</span> · cdn/components/common/modals/YiModal/" },
            { icon: "📝", iconTone: "is-module", title: "YiInput / YiTextarea",  description: "表单输入组件 · 聊天输入框基础", meta: "<span class=\"accent\">CDN</span> · cdn/components/common/forms/" },
            { icon: "🏗", iconTone: "is-module", title: "HeaderActions",         description: "页面头部操作按钮组", meta: "<span class=\"accent\">CDN</span> · cdn/components/business/HeaderActions/" },
            { icon: "📄", iconTone: "is-module", title: "MarkdownView",          description: "Markdown 预览组件", meta: "<span class=\"accent\">CDN</span> · cdn/components/business/MarkdownView/" }
          ]
        },
        {
          id:    "src-assets",
          kind:  "items",
          icon:  "🎨",
          title: "Assets & Styles",
          items: [
            { icon: "🎨", iconTone: "is-module", title: "content.css",           description: "Content Script 主样式", meta: "<span class=\"accent\">Styles</span> · assets/styles/content.css" },
            { icon: "🎨", iconTone: "is-module", title: "tailwind.css",          description: "Tailwind CSS 工具类", meta: "<span class=\"accent\">Styles</span> · assets/styles/tailwind.css" },
            { icon: "🐾", iconTone: "is-module", title: "pet.css",               description: "宠物元素样式", meta: "<span class=\"accent\">Styles</span> · assets/styles/components/pet.css" },
            { icon: "💬", iconTone: "is-module", title: "chat.css",              description: "聊天窗口样式", meta: "<span class=\"accent\">Styles</span> · assets/styles/components/chat.css" },
            { icon: "❓", iconTone: "is-module", title: "faq.css",               description: "FAQ 面板样式", meta: "<span class=\"accent\">Styles</span> · assets/styles/components/faq.css" },
            { icon: "🏷", iconTone: "is-module", title: "tags.css",              description: "标签组件样式", meta: "<span class=\"accent\">Styles</span> · assets/styles/components/tags.css" },
            { icon: "🎨", iconTone: "is-module", title: "theme.css (cdn)",       description: "CDN 主主题 · Code Dark", meta: "<span class=\"accent\">Styles</span> · cdn/theme.css" },
            { icon: "🖼", iconTone: "is-module", title: "Icons & Images",        description: "扩展图标 + 角色图片 (4 种角色)", meta: "<span class=\"accent\">Assets</span> · assets/icons/ & assets/images/" }
          ]
        }
      ]
    }
  ],

  // ── § 4 · Refactoring & Code Quality ─────────────────────────────────
  footerLinks: [
    { label: "CLAUDE.md",  href: "CLAUDE.md",  targetBlank: true },
    { label: "README.md",  href: "README.md",  targetBlank: true },
    { label: "Architecture", href: "arch/",    targetBlank: true },
    { label: "Self-Check",   href: "test/",    targetBlank: true },
    { label: "Story Report →", href: "story/index.html" }
  ]
};
