/**
 * YiWeb · AI Code Review Web Application
 * --------------------------------------------------------------------------
 * Generated by yry-init pipeline (steps 01-03) from the YiWeb source tree.
 * The data is consumed by:
 *   - index.html (Vue 3 template references · v-cloak hides it until
 *     the Vue app + all CDN components resolve)
 *   - index.js  (reads window.HELP_CONFIG and creates the Vue app)
 */
window.HELP_CONFIG = {
  titleIcon:     "🔍",
  title:         "YiWeb · AI Code Review Web Application",
  tagline:       "Vue 3 SPA · three views (aicr / claude / story) · hook-pattern state management · CDN-based component system",
  backTopLabel:  "返回顶部",
  footerNote:    "由 yry-init 流水线生成 (detect → explore → generate → arch → verify) · 项目根: /Users/yi/YrY/YiWeb/",

  breadcrumb: [
    { label: "YiDoc", href: "../../index.html" },
    { label: "Projects", href: "../../dashboard/index.html" },
    { label: "YiWeb" }
  ],

  stats: [
    { value: "3",  label: "Views",          modifier: "accent", sub: "aicr / claude / story" },
    { value: "20", label: "Components",      modifier: "cyan",   sub: "UI modules" },
    { value: "66", label: "Hooks",           modifier: "accent", sub: "store + computed + methods" },
    { value: "95", label: "Source Files",    modifier: "info",   sub: "JavaScript modules" }
  ],

  panelHub: {
    label: { text: '📊', panel: 'reports', title: 'YiWeb 文档导航' },
    targetBlank: false,
    buttons: [
        {icon: '🏛', name: 'Architecture', desc: '6 个架构场景', color: 'var(--yry-accent)', panel: 'arch'},
        {icon: '✅', name: 'Self-Check',   desc: '6 个自检场景', color: 'var(--yry-cyan)',  panel: 'test'},
        {icon: '📁', name: 'Files',         desc: '95 文件 · 906 KB', color: 'var(--yry-info)', panel: 'files'},
        {icon: '🔌', name: 'APIs',          desc: '20 端点 · 47 分', color: 'var(--yry-warn)',  panel: 'apis'},
    ],
    flow: '架构分析 → 自检策略 → 文件体检 → API 审计',
    urls: {
        arch:  '../../templates/arch/index.html?project=YiWeb',
        test:  '../../templates/test/index.html?project=YiWeb',
        files: '../../templates/files/index.html?project=YiWeb',
        apis:  '../../templates/apis/index.html?project=YiWeb',
        daily: '../../templates/daily/cto-report.html?project=YiWeb',
    },
  },

  reportsList: {
    daily: [],
    weekly: [],
    monthly: [],
  },

  sections: [
    {
      id:    "section-dependencies",
      badge: "1",
      title: "Third-Party Dependencies / Frameworks",
      meta:  "0 runtime · 0 dev deps · CDN-loaded",
      groups: [
        {
          id:    "deps-runtime",
          kind:  "items",
          icon:  "📦",
          title: "Runtime Dependencies (CDN-loaded, no package.json)",
          items: [
            {
              icon:        "V",
              iconTone:    "is-module",
              title:       "Vue 3",
              description: "Progressive framework · Composition API · reactive data-driven views",
              meta:        "<span class=\"accent\">CDN</span> · injected via shared/loader.js"
            },
            {
              icon:        "B",
              iconTone:    "is-module",
              title:       "baseView.js",
              description: "Custom view bootstrap · dynamic component loader · createBaseView factory",
              meta:        "<span class=\"accent\">CDN</span> · /cdn/utils/view/baseView.js"
            },
            {
              icon:        "C",
              iconTone:    "is-module",
              title:       "Component Loader",
              description: "Dynamic HTML/CSS/JS component system · registerGlobalComponent",
              meta:        "<span class=\"accent\">CDN</span> · /cdn/utils/view/componentLoader.js"
            },
            {
              icon:        "L",
              iconTone:    "is-module",
              title:       "Log System",
              description: "Structured logging (logInfo / logWarn / logError) with browser integration",
              meta:        "<span class=\"accent\">CDN</span> · /cdn/utils/core/log.js"
            },
            {
              icon:        "E",
              iconTone:    "is-module",
              title:       "Error Handling",
              description: "Error codes, safe execution wrappers, browser extension error filter",
              meta:        "<span class=\"accent\">CDN</span> · /cdn/utils/core/error.js"
            },
            {
              icon:        "F",
              iconTone:    "is-module",
              title:       "Fetch API",
              description: "Native fetch wrapper with timeout, abort, retry, caching, auth headers",
              meta:        "<span class=\"accent\">Native</span> · window.fetch + AbortController"
            },
            {
              icon:        "M",
              iconTone:    "is-module",
              title:       "Markdown Renderer",
              description: "Streaming + static markdown-to-HTML rendering",
              meta:        "<span class=\"accent\">CDN</span> · /cdn/markdown/index.js"
            },
            {
              icon:        "S",
              iconTone:    "is-module",
              title:       "Storage Utils",
              description: "localStorage / sessionStorage / cookie wrappers",
              meta:        "<span class=\"accent\">CDN</span> · /cdn/utils/core/storage.js"
            }
          ]
        },
        {
          id:    "deps-dev",
          kind:  "items",
          icon:  "🛠",
          title: "Build & Infrastructure (server-side)",
          items: [
            {
              icon:        "N",
              iconTone:    "is-module",
              title:       "Nginx",
              description: "Reverse proxy · static file serving · CORS configuration",
              meta:        "<span class=\"accent\">Infra</span> · serves /cdn/ static assets"
            },
            {
              icon:        "O",
              iconTone:    "is-module",
              title:       "Ollama",
              description: "Local LLM inference · model list fetching · API proxy",
              meta:        "<span class=\"accent\">Service</span> · ollama.effiy.cn"
            }
          ]
        }
      ]
    },

    {
      id:    "section-stories",
      badge: "2",
      title: "Story Documents & Scenes",
      meta:  "2 stories · 12 scenes · architecture + self-check",
      groups: [
        {
          kind:  "stories",
          icon:  "📚",
          title: "Story Catalog (arch + test)",
          items: [
            {
              icon:        "🏛",
              title:       "System Architecture & Knowledge Codification",
              badge:       "6 scenes",
              description: "End-to-end request trace from aicr entry to API persistence · <strong>6 architecture scenes</strong> · module location, data flow, onboarding, dependency impact, security surface, <strong>view & hook lifecycle</strong>",
              sceneLinks: [
                { label: "1. Module Location",          href: "../../projects/YiWeb/arch/scene-1-module-location/index.md" },
                { label: "2. Data Flow Tracing",         href: "../../projects/YiWeb/arch/scene-2-data-flow-tracing/index.md" },
                { label: "3. Newcomer Onboarding",      href: "../../projects/YiWeb/arch/scene-3-newcomer-onboarding/index.md" },
                { label: "4. Dependency Impact",         href: "../../projects/YiWeb/arch/scene-4-dependency-change-impact/index.md" },
                { label: "5. Security Surface",         href: "../../projects/YiWeb/arch/scene-5-trust-boundary-security-surface/index.md" },
                { label: "6. View & Hook Lifecycle",    href: "../../projects/YiWeb/arch/scene-6-view-hook-lifecycle/index.md" }
              ],
              links: [
                { label: "Architecture Dashboard →", href: "../../templates/arch/index.html?project=YiWeb" }
              ],
              meta: "6 scenes · risk: medium · covers aicr / claude / story views"
            },
            {
              icon:        "✅",
              title:       "Self-Check Strategy & Verification Suite",
              badge:       "6 scenes",
              description: "Continuous verification pipeline · <strong>6 test scenes</strong> · post-init, pre-commit, doc consistency, security regression, cross-story integration, third-party health",
              sceneLinks: [
                { label: "1. Post-Init Self-Check",    href: "../../projects/YiWeb/test/scene-1-post-init-full-self-check/index.md" },
                { label: "2. Pre-Commit Self-Check",  href: "../../projects/YiWeb/test/scene-2-pre-commit-incremental-self-check/index.md" },
                { label: "3. Doc Consistency",         href: "../../projects/YiWeb/test/scene-3-doc-code-consistency/index.md" },
                { label: "4. Security Regression",     href: "../../projects/YiWeb/test/scene-4-security-surface-regression/index.md" },
                { label: "5. Integration Regression",  href: "../../projects/YiWeb/test/scene-5-cross-story-integration-regression/index.md" },
                { label: "6. Third-Party Services",   href: "../../projects/YiWeb/test/scene-6-third-party-framework-service/index.md" }
              ],
              links: [
                { label: "Test Dashboard →", href: "../../templates/test/index.html?project=YiWeb" }
              ],
              meta: "6 scenes · risk: low · covers all 7 verify checks"
            }
          ]
        }
      ]
    },

    {
      id:    "section-source",
      badge: "3",
      title: "Main Source Code",
      meta:  "3 views · 20 components · 66 hooks · 95 source files",
      groups: [
        {
          id:    "src-views-aicr",
          kind:  "items",
          icon:  "🔬",
          title: "AI Code Review View (views/aicr/)",
          items: [
            { icon: "🚀", iconTone: "is-module", title: "aicr/index.js",       description: "Main entry · createStore + useComputed + useMethods + createBaseView bootstrap", meta: "<span class=\"accent\">Entry</span> · src/views/aicr/index.js" },
            { icon: "🧩", iconTone: "is-module", title: "aicr/hooks/store.js",  description: "Central reactive state · sessions, fileTree, selectedKey, sidebar state", meta: "<span class=\"accent\">State</span> · src/views/aicr/hooks/store.js" },
            { icon: "📐", iconTone: "is-module", title: "useComputed.js",        description: "Derived state · storyTags, skillTags, templateTags, filteredFileCount", meta: "<span class=\"accent\">Computed</span> · src/views/aicr/hooks/useComputed.js" },
            { icon: "⚡", iconTone: "is-module", title: "useMethods.js",         description: "All methods · search, chat, fileTree CRUD, session management, streaming", meta: "<span class=\"accent\">Methods</span> · src/views/aicr/hooks/useMethods.js" },
            { icon: "📋", iconTone: "is-module", title: "aicrPage component",    description: "Shell layout · keyboard shortcuts · view mode switching (tree/cards/graph)", meta: "<span class=\"accent\">Component</span> · src/views/aicr/components/aicrPage/" },
            { icon: "🗂", iconTone: "is-module", title: "fileTree component",    description: "File tree with batch ops · expand/collapse · drag sort · search filter", meta: "<span class=\"accent\">Component</span> · src/views/aicr/components/fileTree/" },
            { icon: "💬", iconTone: "is-module", title: "SessionChatContext",    description: "AI chat panel · streaming responses · context editing · scroll sync", meta: "<span class=\"accent\">Hooks</span> · sessionChatContextMethods.js" },
            { icon: "🏷", iconTone: "is-module", title: "Tag & Filter System",   description: "Multi-level tag filtering · skills/templates/rules/agents cross-filter", meta: "<span class=\"accent\">Hooks</span> · tagFilterMethods.js" }
          ]
        },
        {
          id:    "src-views-story",
          kind:  "items",
          icon:  "📖",
          title: "Story Management View (views/story/)",
          items: [
            { icon: "🚀", iconTone: "is-module", title: "story/index.js",       description: "Main entry · createStore + useComputed + useMethods pattern", meta: "<span class=\"accent\">Entry</span> · src/views/story/index.js" },
            { icon: "🧩", iconTone: "is-module", title: "hooks/state/store.js",  description: "Reactive state · stories, fileTree, filters, editing, deps", meta: "<span class=\"accent\">State</span> · src/views/story/hooks/state/store.js" },
            { icon: "📐", iconTone: "is-module", title: "useComputed.js",        description: "Derived state · filteredStories, statusCounts, projectTags", meta: "<span class=\"accent\">Computed</span> · src/views/story/hooks/computed/useComputed.js" },
            { icon: "⚡", iconTone: "is-module", title: "useMethods.js",         description: "Story CRUD, deps management, filter/sort, knowledge graph", meta: "<span class=\"accent\">Methods</span> · src/views/story/hooks/useMethods.js" },
            { icon: "📊", iconTone: "is-module", title: "storyPanelPage",        description: "Main panel · story list + detail · status filtering · panel view", meta: "<span class=\"accent\">Component</span> · src/views/story/components/storyPanelPage/" },
            { icon: "🔗", iconTone: "is-module", title: "depEditor",             description: "Dependency editor · add/remove bidirectional deps between stories", meta: "<span class=\"accent\">Component</span> · src/views/story/components/depEditor/" }
          ]
        },
        {
          id:    "src-views-claude",
          kind:  "items",
          icon:  "🤖",
          title: "Claude Panel View (views/claude/)",
          items: [
            { icon: "🚀", iconTone: "is-module", title: "claude/index.js",      description: "Main entry · createStore pattern, project list + detail drill-down", meta: "<span class=\"accent\">Entry</span> · src/views/claude/index.js" },
            { icon: "🧩", iconTone: "is-module", title: "hooks/store.js",        description: "Projects state · loading, error, selectedProject, fetchProjects", meta: "<span class=\"accent\">State</span> · src/views/claude/hooks/store.js" },
            { icon: "📋", iconTone: "is-module", title: "claudePanelPage",       description: "Project list with card grid · search, sort, select", meta: "<span class=\"accent\">Component</span> · src/views/claude/components/claudePanelPage/" },
            { icon: "📄", iconTone: "is-module", title: "claudeDetailCard",      description: "Project detail view · skills, templates, rules, agents info", meta: "<span class=\"accent\">Component</span> · src/views/claude/components/claudeDetailCard/" }
          ]
        },
        {
          id:    "src-core-services",
          kind:  "items",
          icon:  "⚙️",
          title: "Core Services Layer (core/services/)",
          items: [
            { icon: "🔗", iconTone: "is-module", title: "services/index.js",    description: "API module aggregator · re-exports all service functions", meta: "<span class=\"accent\">Aggregator</span> · src/core/services/index.js" },
            { icon: "📡", iconTone: "is-module", title: "requestHelper.js",      description: "HTTP client · fetch wrapper, timeout, CORS, retry, caching, auth", meta: "<span class=\"accent\">Network</span> · src/core/services/helper/requestHelper.js" },
            { icon: "🔐", iconTone: "is-module", title: "authUtils.js",          description: "X-Token management · localStorage persistence · API settings dialog", meta: "<span class=\"accent\">Auth</span> · src/core/services/helper/authUtils.js" },
            { icon: "📋", iconTone: "is-module", title: "crud.js",               description: "Generic CRUD operations · streamPrompt, streamPromptJSON, batchOps", meta: "<span class=\"accent\">Data</span> · src/core/services/modules/crud.js" },
            { icon: "🏢", iconTone: "is-module", title: "business/",             description: "Business logic · process manager, scenario analyzer, requirement analysis", meta: "<span class=\"accent\">Domain</span> · src/core/services/business/" },
            { icon: "📡", iconTone: "is-module", title: "sessionSyncService.js", description: "Session sync between aicr view and backend · data consistency", meta: "<span class=\"accent\">Sync</span> · src/core/services/aicr/sessionSyncService.js" }
          ]
        },
        {
          id:    "src-utils",
          kind:  "items",
          icon:  "🛠",
          title: "Utility Layer",
          items: [
            { icon: "⚙️", iconTone: "is-module", title: "core/config.js",        description: "Environment config · local/prod endpoint switching · debug mode", meta: "<span class=\"accent\">Config</span> · src/core/config.js" },
            { icon: "🔧", iconTone: "is-module", title: "core/utils/index.js",    description: "Utility re-exports · CDN storage, eventBus, http, animation, validation", meta: "<span class=\"accent\">Utils</span> · src/core/utils/index.js" },
            { icon: "🗺", iconTone: "is-module", title: "fileToStoryMapper.js",   description: "File-to-story knowledge graph mapper · cross-view integration utility", meta: "<span class=\"accent\">Mapper</span> · src/utils/fileToStoryMapper.js" }
          ]
        }
      ]
    }
  ],

  footerLinks: [
    { label: "YiWeb Project", href: "../../YiWeb/index.html", targetBlank: true },
    { label: "CLAUDE.md",  href: "CLAUDE.md",        targetBlank: true },
    { label: "README.md",  href: "README.md",        targetBlank: true },
    { label: "Story Report →", href: "story/index.html" }
  ]
};
