import globals from 'globals'

export default [
  {
    ignores: [
      'node_modules/',
      'coverage/',
      'dist/',
      'test-results/',
      '.claude/',
      'cdn/',
      'libs/',
      'docs/',
      'eslint.config.js',
      'vitest.config.js',
      '**/*.zip',
      '**/*.crx',
      '**/*.pem',
    ],
  },
  {
    files: ['**/*.js'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'script',
      globals: {
        ...globals.browser,
        ...globals.webextensions,
        globalThis: 'readonly',
        Vue: 'readonly',
        marked: 'readonly',
        turndown: 'readonly',
        TurndownService: 'readonly',
        mermaid: 'readonly',
        md5: 'readonly',
        PetManager: 'readonly',
        RequestClient: 'readonly',
        createRequestClient: 'readonly',
        requestClient: 'readonly',
        ApiManager: 'readonly',
        SessionService: 'readonly',
        FaqService: 'readonly',
        TokenManager: 'readonly',
        ConfigManager: 'readonly',
        StorageHelper: 'readonly',
        ErrorHandler: 'readonly',
        ImageResourceManager: 'readonly',
        LoadingAnimation: 'readonly',
        LoadingAnimationMixin: 'readonly',
        ChatWindow: 'readonly',
        DomUtils: 'readonly',
        PositionCalculator: 'readonly',
        buildDatabaseUrl: 'readonly',
        PET_CONFIG: 'readonly',
        getPetDefaultPosition: 'readonly',
        getChatWindowDefaultPosition: 'readonly',
        getCenterPosition: 'readonly',
        DomHelper: 'readonly',
        TimeUtils: 'readonly',
        NotificationUtils: 'readonly',
        LoggerUtils: 'readonly',
        StorageUtils: 'readonly',
        TokenUtils: 'readonly',
        MessageHelper: 'readonly',
        GlobalAccessor: 'readonly',
        showNotification: 'readonly',
        ExtensionHandler: 'readonly',
        PetHandler: 'readonly',
        MessageRouter: 'readonly',
        MessageForwardHandler: 'readonly',
        WeWorkHandler: 'readonly',
        TabHandler: 'readonly',
        InjectionService: 'readonly',
        WeWorkService: 'readonly',
        SessionManager: 'readonly',
        MarkdownRenderer: 'readonly',
        MermaidRenderer: 'readonly',
        YipDemo: 'readonly',
        Logger: 'readonly',
        sanitizePathSegment: 'readonly',
        parseImageDataUrl: 'readonly',
        imageResourceManager: 'readonly',
        petManager: 'readonly',
        petLoadingAnimation: 'readonly',
        initSession: 'readonly',
        PET_ENV: 'readonly',
        Levenshtein: 'readonly',
        cytoscape: 'readonly',
        html2canvas: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': [
        'warn',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_|^e$|^err$|^error$' },
      ],
      'no-console': 'off',
      'no-undef': 'error',
      'no-extra-semi': 'off',
      curly: ['warn', 'multi-line'],
      eqeqeq: ['error', 'always', { null: 'ignore' }],
      'no-var': 'warn',
      'prefer-const': 'warn',
      'no-throw-literal': 'error',
      'no-self-compare': 'error',
      'no-extend-native': 'error',
      'no-obj-calls': 'error',
      'no-prototype-builtins': 'error',
      'no-unsafe-negation': 'error',
      'no-unsafe-finally': 'error',
      'no-useless-escape': 'warn',
      'object-shorthand': 'warn',
      'prefer-template': 'warn',
      'no-useless-catch': 'error',
      'no-irregular-whitespace': 'error',
      radix: 'error',
    },
  },
  {
    files: ['core/**/*.js', 'modules/**/*.js'],
    languageOptions: {
      globals: {
        module: 'readonly',
        process: 'readonly',
        global: 'readonly',
        exports: 'readonly',
        define: 'readonly',
        setImmediate: 'readonly',
      },
    },
  },
  {
    files: ['modules/extension/background/**/*.js'],
    languageOptions: {
      globals: {
        importScripts: 'readonly',
      },
    },
  },
  {
    files: ['**/*.mjs', 'vitest.config.js'],
    languageOptions: {
      sourceType: 'module',
    },
  },
  {
    files: ['tests/**/*.{js,mjs}'],
    languageOptions: {
      globals: {
        ...globals.node,
        describe: 'readonly',
        it: 'readonly',
        expect: 'readonly',
        beforeEach: 'readonly',
        afterEach: 'readonly',
        vi: 'readonly',
        beforeAll: 'readonly',
        afterAll: 'readonly',
      },
    },
  },
]
