import os
import yaml
from typing import List, Union, Dict, Any
from pydantic import Field
from pydantic_settings import BaseSettings, SettingsConfigDict, PydanticBaseSettingsSource, InitSettingsSource


class YamlConfigSettingsSource(InitSettingsSource):
    """
    A settings source that reads from a nested config.yaml file,
    flattening the structure to match flat Settings fields.
    e.g., {"server": {"host": "..."}} -> {"server_host": "..."}
    """

    def __init__(self, settings_cls: type[BaseSettings]):
        config_file = "config.yaml"
        yaml_data: Dict[str, Any] = {}
        if os.path.exists(config_file):
            with open(config_file, encoding='utf-8') as f:
                data = yaml.safe_load(f) or {}
                yaml_data = self._flatten(data)
        yaml_data = {k: os.path.expanduser(v) if isinstance(v, str) else v for k, v in yaml_data.items()}
        super().__init__(settings_cls, yaml_data)

    @staticmethod
    def _flatten(d: Dict[str, Any], parent_key: str = '', sep: str = '_') -> Dict[str, Any]:
        items = []
        for k, v in d.items():
            new_key = f"{parent_key}{sep}{k}" if parent_key else k
            if isinstance(v, dict):
                items.extend(YamlConfigSettingsSource._flatten(v, new_key, sep=sep).items())
            else:
                items.append((new_key, v))
        return dict(items)


class Settings(BaseSettings):
    _MB = 1024 * 1024

    # Server
    server_host: str = Field("0.0.0.0", validation_alias="server_host")
    server_port: int = Field(8000, validation_alias="server_port")
    server_reload: bool = Field(True, validation_alias="server_reload")
    uvicorn_limit_concurrency: int = Field(1000, validation_alias="uvicorn_limit_concurrency")
    uvicorn_limit_max_requests: int = Field(10000, validation_alias="uvicorn_limit_max_requests")
    uvicorn_timeout_keep_alive: int = Field(5, validation_alias="uvicorn_timeout_keep_alive")

    # CORS
    cors_origins: Union[str, List[str]] = Field(["*"], validation_alias="cors_origins")
    cors_allow_any_origin: bool = Field(True, validation_alias="cors_allow_any_origin")

    # Pagination
    pagination_default_size: int = Field(2000, validation_alias="pagination_default_size")
    pagination_max_size: int = Field(100000000, validation_alias="pagination_max_size")
    pagination_min_size: int = Field(1, validation_alias="pagination_min_size")

    # User
    default_user_id: str = Field("default_user", validation_alias="default_user_id")

    # Static
    static_base_dir: str = Field("./static", validation_alias="static_base_dir")
    static_base_url: str = Field("https://api.effiy.cn/static", validation_alias="static_base_url")
    static_max_zip_size_mb: int = Field(100, validation_alias="static_max_zip_size_mb")

    # Project sources root (cross-project file reads via /read-project-file)
    projects_root: str = Field("..", validation_alias="projects_root")

    # Knowledge base (~/YiKnowledge-style markdown tree with YAML frontmatter)
    knowledge_base_dir: str = Field("../YiKnowledge", validation_alias="knowledge_base_dir")
    knowledge_watcher_enabled: bool = Field(True, validation_alias="knowledge_watcher_enabled")
    knowledge_watcher_poll_seconds: int = Field(60, validation_alias="knowledge_watcher_poll_seconds")

    # Menu — auto-generated by scanning YiVad src/views
    menu_views_base_dir: str = Field("../YiVad/src/views", validation_alias="menu_views_base_dir")

    # Database
    mongodb_url: str = Field("mongodb://localhost:27017", validation_alias="mongodb_url")
    mongodb_db_name: str = Field("ruiyi", validation_alias="mongodb_db_name")
    mongodb_pool_size: int = Field(10, validation_alias="mongodb_pool_size")
    mongodb_max_pool_size: int = Field(50, validation_alias="mongodb_max_pool_size")

    collection_sessions: str = Field("sessions", validation_alias="collection_sessions")
    collection_rss: str = Field("rss", validation_alias="collection_rss")
    collection_chat_records: str = Field("chat_records", validation_alias="collection_chat_records")
    collection_pet_data_sync: str = Field("pet_data_sync", validation_alias="collection_pet_data_sync")
    collection_seeds: str = Field("seeds", validation_alias="collection_seeds")
    collection_oss_file_tags: str = Field("oss_file_tags", validation_alias="collection_oss_file_tags")
    collection_oss_file_info: str = Field("oss_file_info", validation_alias="collection_oss_file_info")
    collection_static_files: str = Field("static_files", validation_alias="collection_static_files")
    collection_knowledge_files: str = Field("knowledge_files", validation_alias="collection_knowledge_files")

    # OSS
    oss_access_key: str = Field("", validation_alias="oss_access_key")
    oss_secret_key: str = Field("", validation_alias="oss_secret_key")
    oss_endpoint: str = Field("", validation_alias="oss_endpoint")
    oss_bucket: str = Field("", validation_alias="oss_bucket")
    oss_domain: str = Field("", validation_alias="oss_domain")
    oss_max_file_size_mb: int = Field(50, validation_alias="oss_max_file_size_mb")
    oss_allowed_extensions: List[str] = Field(
        [".jpg", ".jpeg", ".png", ".gif", ".pdf", ".doc", ".docx", ".epub", ".md"],
        validation_alias="oss_allowed_extensions"
    )

    # RSS
    rss_scheduler_enabled: bool = Field(True, validation_alias="rss_scheduler_enabled")
    rss_scheduler_interval: int = Field(3600, validation_alias="rss_scheduler_interval")

    # Startup
    startup_init_database: bool = Field(True, validation_alias="startup_init_database")
    startup_init_rss_system: bool = Field(True, validation_alias="startup_init_rss_system")

    # Middleware
    middleware_auth_enabled: bool = Field(False, validation_alias="middleware_auth_enabled")
    middleware_auth_token: str = Field("", validation_alias="middleware_auth_token")

    # JWT
    jwt_secret: str = Field("yi-ai-jwt-secret-change-in-production", validation_alias="jwt_secret")
    jwt_expire_minutes: int = Field(1440, validation_alias="jwt_expire_minutes")

    # Module
    module_allowlist: Union[str, List[str]] = Field(["*"], validation_alias="module_allowlist")

    # State Store
    state_store_enabled: bool = Field(True, validation_alias="state_store_enabled")
    state_store_default_ttl: int = Field(0, validation_alias="state_store_default_ttl")
    state_store_query_max_limit: int = Field(100000000, validation_alias="state_store_query_max_limit")
    collection_state_records: str = Field("state_records", validation_alias="collection_state_records")

    # Observer
    observer_enabled: bool = Field(True, validation_alias="observer_enabled")
    observer_throttle_enabled: bool = Field(True, validation_alias="observer_throttle_enabled")
    observer_throttle_max_requests: int = Field(100, validation_alias="observer_throttle_max_requests")
    observer_throttle_window_seconds: int = Field(60, validation_alias="observer_throttle_window_seconds")
    observer_throttle_whitelist: Union[str, List[str]] = Field("", validation_alias="observer_throttle_whitelist")
    observer_sampler_enabled: bool = Field(True, validation_alias="observer_sampler_enabled")
    observer_sampler_max_size: int = Field(1000, validation_alias="observer_sampler_max_size")
    observer_sampler_slow_threshold_ms: float = Field(5000.0, validation_alias="observer_sampler_slow_threshold_ms")
    observer_sandbox_enabled: bool = Field(False, validation_alias="observer_sandbox_enabled")
    observer_sandbox_fs_allowlist: Union[str, List[str]] = Field("", validation_alias="observer_sandbox_fs_allowlist")
    observer_sandbox_network_allowlist: Union[str, List[str]] = Field("", validation_alias="observer_sandbox_network_allowlist")
    observer_lazy_start: bool = Field(True, validation_alias="observer_lazy_start")
    observer_guard_enabled: bool = Field(True, validation_alias="observer_guard_enabled")
    observer_guard_max_depth: int = Field(3, validation_alias="observer_guard_max_depth")

    # Ollama
    ollama_url: str = Field("http://localhost:11434", validation_alias="ollama_url")
    ollama_auth: str = Field("", validation_alias="ollama_auth")
    ollama_chat_timeout: int = Field(600, validation_alias="ollama_chat_timeout")
    ollama_num_ctx: int = Field(16384, validation_alias="ollama_num_ctx")
    ollama_num_predict: int = Field(8192, validation_alias="ollama_num_predict")

    # DeepSeek (OpenAI-compatible API)
    deepseek_api_key: str = Field("", validation_alias="deepseek_api_key")
    deepseek_base_url: str = Field("https://api.deepseek.com/v1", validation_alias="deepseek_base_url")
    deepseek_default_model: str = Field("deepseek-chat", validation_alias="deepseek_default_model")
    deepseek_chat_timeout: int = Field(300, validation_alias="deepseek_chat_timeout")

    # LLM Provider Router
    llm_chat_provider: str = Field("", validation_alias="llm_chat_provider")
    llm_embed_provider: str = Field("", validation_alias="llm_embed_provider")

    # Default AI provider: ollama | deepseek
    ai_provider: str = Field("ollama", validation_alias="ai_provider")

    # RAG (llama_index)
    rag_embed_model: str = Field("nomic-embed-text", validation_alias="rag_embed_model")
    rag_llm_model: str = Field("qwen3.5:4b", validation_alias="rag_llm_model")
    rag_persist_dir: str = Field("./data/rag_store", validation_alias="rag_persist_dir")
    rag_top_k: int = Field(3, validation_alias="rag_top_k")
    rag_chunk_size: int = Field(512, validation_alias="rag_chunk_size")
    rag_chunk_overlap: int = Field(40, validation_alias="rag_chunk_overlap")
    rag_auto_rebuild_enabled: bool = Field(True, validation_alias="rag_auto_rebuild_enabled")
    rag_auto_rebuild_debounce_seconds: int = Field(30, validation_alias="rag_auto_rebuild_debounce_seconds")
    rag_hybrid_retrieval_enabled: bool = Field(True, validation_alias="rag_hybrid_retrieval_enabled")
    rag_rerank_enabled: bool = Field(True, validation_alias="rag_rerank_enabled")
    rag_inline_citations_enabled: bool = Field(True, validation_alias="rag_inline_citations_enabled")
    rag_chat_timeout: int = Field(180, validation_alias="rag_chat_timeout")
    rag_llm_request_timeout: int = Field(120, validation_alias="rag_llm_request_timeout")
    rag_num_predict: int = Field(512, validation_alias="rag_num_predict")
    rag_temperature: float = Field(0.0, validation_alias="rag_temperature")
    rag_context_chunks: int = Field(4, validation_alias="rag_context_chunks")
    rag_snippet_chars: int = Field(600, validation_alias="rag_snippet_chars")
    rag_history_msgs: int = Field(6, validation_alias="rag_history_msgs")
    rag_history_chars: int = Field(500, validation_alias="rag_history_chars")
    rag_hyde_enabled: bool = Field(True, validation_alias="rag_hyde_enabled")
    rag_sentence_window_enabled: bool = Field(True, validation_alias="rag_sentence_window_enabled")
    rag_sentence_window_size: int = Field(3, validation_alias="rag_sentence_window_size")

    # Logging
    logging_level: str = Field("INFO", validation_alias="logging_level")
    logging_format: str = Field("%(asctime)s - %(name)s - %(levelname)s - %(message)s", validation_alias="logging_format")
    logging_datefmt: str = Field("%Y-%m-%d %H:%M:%S", validation_alias="logging_datefmt")
    logging_propagate_uvicorn: bool = Field(False, validation_alias="logging_propagate_uvicorn")

    # Audit
    audit_enabled: bool = Field(True, validation_alias="audit_enabled")
    audit_retention_days: int = Field(90, validation_alias="audit_retention_days")
    audit_large_field_max_chars: int = Field(2000, validation_alias="audit_large_field_max_chars")
    audit_collection: str = Field("audit_logs", validation_alias="audit_collection")

    # Backup
    backup_enabled: bool = Field(False, validation_alias="backup_enabled")
    backup_local_dir: str = Field("./backups/mongodb", validation_alias="backup_local_dir")
    backup_remote_dir: str = Field("", validation_alias="backup_remote_dir")
    backup_local_retention_days: int = Field(7, validation_alias="backup_local_retention_days")
    backup_remote_retention_days: int = Field(30, validation_alias="backup_remote_retention_days")

    # Redis cache
    redis_url: str = Field("", validation_alias="redis_url")

    # Migrations
    migrations_dir: str = Field("./migrations", validation_alias="migrations_dir")

    # Alert
    alert_wework_webhook: str = Field("", validation_alias="alert_wework_webhook")

    model_config = SettingsConfigDict(extra="ignore", populate_by_name=True, yaml_file=[])

    @classmethod
    def settings_customise_sources(
        cls,
        settings_cls: type[BaseSettings],
        init_settings: PydanticBaseSettingsSource,
        env_settings: PydanticBaseSettingsSource,
        dotenv_settings: PydanticBaseSettingsSource,
        file_secret_settings: PydanticBaseSettingsSource,
    ) -> tuple[PydanticBaseSettingsSource, ...]:
        return (
            init_settings,
            YamlConfigSettingsSource(settings_cls),
            env_settings,
            dotenv_settings,
            file_secret_settings,
        )

    @property
    def static_max_zip_size(self) -> int:
        return self.static_max_zip_size_mb * Settings._MB

    @property
    def oss_max_file_size(self) -> int:
        return self.oss_max_file_size_mb * Settings._MB

    def get_cors_origins(self) -> List[str]:
        if isinstance(self.cors_origins, str) and self.cors_origins == "*":
            return ["*"]
        return Settings._to_list(self.cors_origins)

    @staticmethod
    def _to_list(value: Union[str, List[str]]) -> List[str]:
        if isinstance(value, str):
            return [item.strip() for item in value.split(',') if item.strip()]
        return value

    def get_throttle_whitelist(self) -> List[str]:
        return Settings._to_list(self.observer_throttle_whitelist)

    def get_sandbox_fs_allowlist(self) -> List[str]:
        return Settings._to_list(self.observer_sandbox_fs_allowlist)

    def get_sandbox_network_allowlist(self) -> List[str]:
        return Settings._to_list(self.observer_sandbox_network_allowlist)

    @property
    def auth_token(self) -> str:
        return os.getenv("API_X_TOKEN", self.middleware_auth_token)


settings = Settings()