/**
 * YiH5 · Dashboard data model
 * Generated by rui-init pipeline (steps 01–05)
 */
window.HELP_CONFIG = {
  titleIcon:     "★",
  title:         "YiH5 · H5 Frontend Application",
  tagline:       "Vanilla JS SPA · Session management + AI Chat + News feed · Powered by api.effiy.cn",
  backTopLabel:  "Back to Top",
  footerNote:    "Generated by rui-init pipeline · detect → explore → generate → arch → verify",

  breadcrumb: [
    { label: "YiH5", href: "../index.html" },
    { label: "Dashboard" }
  ],

  stats: [
    { value: "3",  label: "External Libs", modifier: "cyan",   sub: "libs" },
    { value: "9",  label: "Components",    modifier: "accent", sub: "modules" },
    { value: "7",  label: "Services",      modifier: "accent", sub: "modules" },
    { value: "38", label: "Source Files",   modifier: "accent", sub: "JS files" }
  ],

  crossLinks: [
    { icon: "🏛", title: "Architecture Scenes", description: "5 system architecture reference scenes", href: "arch/index.html", targetBlank: true },
    { icon: "✅", title: "Test Scenes", description: "6 self-check strategy scenes", href: "test/index.html", targetBlank: true },
    { icon: "📊", title: "Mermaid Integration", description: "Diagram rendering with 5 plugins", href: "../../../YiH5/mermaid/" }
  ],

  panelHub: {
    label: { text: '📊', panel: 'reports', title: 'Report Dashboards' },
    targetBlank: true,
    buttons: [
      { icon: '🏛', name: 'Architecture', desc: 'Markdown scenes', color: 'var(--rui-accent)', panel: 'arch' },
      { icon: '📁', name: 'Files Report', desc: 'Codebase analysis', color: 'var(--rui-accent)', panel: 'files' },
      { icon: '✅', name: 'test', desc: 'Self-check strategy', color: 'var(--rui-cyan)', panel: 'test', targetBlank: false },
    ],
    flow: 'File Analysis → Code Review → Health Audit → Tech Trends',
    urls: {
      arch:  'arch/index.html',
      files: 'files/index.html',
      'test': 'test/index.html',
    },
  },

  reportsList: {
    daily: [],
    weekly: [],
    monthly: [],
  },

  // ── § 1 · Third-party dependencies & frameworks ────────────────────
  sections: [
    {
      id:    "section-dependencies",
      badge: "1",
      title: "Third-Party Dependencies / Frameworks",
      meta:  "3 runtime libs · 0 dev deps",
      groups: [
        {
          id:    "deps-runtime",
          kind:  "items",
          icon:  "📦",
          title: "Runtime Libraries (3)",
          items: [
            {
              icon:        "M",
              iconTone:    "is-module",
              title:       "marked",
              description: "Markdown parser and compiler · <strong>chat message rendering</strong>",
              meta:        "<span class=\"accent\">Runtime</span> · libs/marked.min.js"
            },
            {
              icon:        "D",
              iconTone:    "is-module",
              title:       "Mermaid",
              description: "Diagram rendering engine · <strong>flowchart / sequence / class</strong>",
              meta:        "<span class=\"accent\">Runtime</span> · libs/mermaid.min.js"
            },
            {
              icon:        "H",
              iconTone:    "is-module",
              title:       "md5",
              description: "MD5 hash for session ID generation · <strong>URL-based dedup</strong>",
              meta:        "<span class=\"accent\">Runtime</span> · libs/md5.js"
            }
          ]
        },
        {
          id:    "deps-dev",
          kind:  "items",
          icon:  "🛠",
          title: "Dev Dependencies (0)",
          items: []
        }
      ]
    },

    // ── § 2 · Story documents & scenes ─────────────────────────────────
    {
      id:    "section-stories",
      badge: "2",
      title: "Story Documents & Scenes",
      meta:  "2 stories · 11 scenes · all self-checks passed",
      groups: [
        {
          kind:  "stories",
          icon:  "📚",
          title: "Story Catalog (arch + test)",
          items: [
            {
              icon:        "🏛",
              title:       "System Architecture & Knowledge Codification",
              badge:       "5 scenes",
              description: "Module location · data flow tracing · newcomer onboarding · dependency impact · <strong>trust boundary / security surface</strong>",
              sceneLinks: [
                { label: "1. Module Location",                href: "arch/scene-1-module-location/index.md" },
                { label: "2. Data Flow Tracing",               href: "arch/scene-2-data-flow-tracing/index.md" },
                { label: "3. Newcomer Onboarding",            href: "arch/scene-3-newcomer-onboarding/index.md" },
                { label: "4. Dependency Impact",               href: "arch/scene-4-dependency-change-impact/index.md" },
                { label: "5. Security Surface",               href: "arch/scene-5-trust-boundary-security-surface/index.md" }
              ],
              links: [
                { label: "Architecture Dashboard →", href: "arch/index.html" }
              ],
              meta: "5 scenes · risk: medium · vanilla JS SPA"
            },
            {
              icon:        "✅",
              title:       "Self-Check Strategy Suite",
              badge:       "6 scenes",
              description: "Post-init · pre-commit · doc-code consistency · <strong>security regression · integration regression · third-party</strong>",
              sceneLinks: [
                { label: "1. Post-Init Self-Check",          href: "test/scene-1-post-init-full-self-check/index.md" },
                { label: "2. Pre-Commit Self-Check",         href: "test/scene-2-pre-commit-incremental-self-check/index.md" },
                { label: "3. Doc Consistency",               href: "test/scene-3-doc-code-consistency/index.md" },
                { label: "4. Security Regression",            href: "test/scene-4-security-surface-regression/index.md" },
                { label: "5. Integration Regression",         href: "test/scene-5-cross-story-integration-regression/index.md" },
                { label: "6. Third-Party Services",          href: "test/scene-6-third-party-framework-service/index.md" }
              ],
              links: [
                { label: "test Dashboard →", href: "test/index.html" }
              ],
              meta: "6 scenes · risk: low · vanilla JS manual check"
            }
          ]
        }
      ]
    },

    // ── § 3 · Main source code ─────────────────────────────────────────
    {
      id:    "section-source",
      badge: "3",
      title: "Main Source Code",
      meta:  "9 components · 7 services · 6 utils · 1 view · 10 mermaid",
      groups: [
        {
          id:    "src-components",
          kind:  "items",
          icon:  "🧩",
          title: "UI Components (9)",
          items: [
            { icon: "📋", iconTone: "is-module", title: "BaseList",           description: "Base list with virtual scroll · sorting / filtering",    meta: "<span class=\"accent\">Component</span> · components/BaseList/" },
            { icon: "💬", iconTone: "is-module", title: "Chat",               description: "Chat UI · message bubbles + streaming rendering",       meta: "<span class=\"accent\">Component</span> · components/Chat/" },
            { icon: "📄", iconTone: "is-module", title: "Content",            description: "Content display wrapper · styles only",                  meta: "<span class=\"accent\">Component</span> · components/Content/" },
            { icon: "📰", iconTone: "is-module", title: "NewsList",           description: "News list with virtual scroll + read tracking",          meta: "<span class=\"accent\">Component</span> · components/NewsList/" },
            { icon: "🖼", iconTone: "is-module", title: "Preview",            description: "Image preview · click to zoom / long press to save",     meta: "<span class=\"accent\">Component</span> · components/Preview/" },
            { icon: "🔍", iconTone: "is-module", title: "Search",             description: "Search bar with query binding + clear",                  meta: "<span class=\"accent\">Component</span> · components/Search/" },
            { icon: "📂", iconTone: "is-module", title: "SessionList",        description: "Session list with swipe-to-delete / favorite",           meta: "<span class=\"accent\">Component</span> · components/SessionList/" },
            { icon: "📜", iconTone: "is-module", title: "VirtualList",        description: "Virtual scroll engine · windowed rendering",            meta: "<span class=\"accent\">Component</span> · components/VirtualList/" },
            { icon: "👆", iconTone: "is-module", title: "SwipeScrollController", description: "Swipe gesture handler · delete / favorite actions",  meta: "<span class=\"accent\">Component</span> · components/SwipeScrollController.js" }
          ]
        },
        {
          id:    "src-services",
          kind:  "items",
          icon:  "🔌",
          title: "API Services (7)",
          items: [
            { icon: "🔑", iconTone: "is-module", title: "auth.js",       description: "Token storage · localStorage X-Token management",        meta: "<span class=\"accent\">Service</span> · services/auth.js" },
            { icon: "🌐", iconTone: "is-module", title: "client.js",     description: "HTTP client · fetchWithAuth + RequestClient class",      meta: "<span class=\"accent\">Service</span> · services/client.js" },
            { icon: "❓", iconTone: "is-module", title: "faq.js",        description: "FAQ API · query_documents from faqs collection",        meta: "<span class=\"accent\">Service</span> · services/faq.js" },
            { icon: "📡", iconTone: "is-module", title: "news.js",       description: "News API · query_documents from rss collection",         meta: "<span class=\"accent\">Service</span> · services/news.js" },
            { icon: "🤖", iconTone: "is-module", title: "prompt.js",     description: "AI Prompt API · streaming SSE + think-tag stripping",    meta: "<span class=\"accent\">Service</span> · services/prompt.js" },
            { icon: "💾", iconTone: "is-module", title: "session.js",    description: "Session CRUD · query/upsert/delete via executeModule",   meta: "<span class=\"accent\">Service</span> · services/session.js" },
            { icon: "📦", iconTone: "is-module", title: "index.js",      description: "Service barrel export · unified API URL constants",      meta: "<span class=\"accent\">Service</span> · services/index.js" }
          ]
        },
        {
          id:    "src-utils",
          kind:  "items",
          icon:  "🛠",
          title: "Utility Modules (6)",
          items: [
            { icon: "📊", iconTone: "is-module", title: "data.js",        description: "Data utilities · deep merge / object helpers",          meta: "<span class=\"accent\">Util</span> · utils/data.js" },
            { icon: "🔧", iconTone: "is-module", title: "index.js",       description: "Core util barrel · dateUtil / escapeHtml / logger",     meta: "<span class=\"accent\">Util</span> · utils/index.js" },
            { icon: "📝", iconTone: "is-module", title: "markdown.js",    description: "Markdown rendering · marked wrapper + Mermaid hook",    meta: "<span class=\"accent\">Util</span> · utils/markdown.js" },
            { icon: "💬", iconTone: "is-module", title: "msg.js",         description: "Message normalization · role / text helpers",            meta: "<span class=\"accent\">Util</span> · utils/msg.js" },
            { icon: "📜", iconTone: "is-module", title: "scroll.js",      description: "Scroll utilities · preserve position / near-bottom",     meta: "<span class=\"accent\">Util</span> · utils/scroll.js" },
            { icon: "📱", iconTone: "is-module", title: "viewport.js",    description: "Viewport helpers · iOS visualViewport bottom inset",    meta: "<span class=\"accent\">Util</span> · utils/viewport.js" }
          ]
        },
        {
          id:    "src-styles",
          kind:  "items",
          icon:  "🎨",
          title: "Stylesheets (6)",
          items: [
            { icon: "🎯", iconTone: "is-module", title: "reset.css",       description: "CSS reset · normalize + box-sizing",                    meta: "<span class=\"accent\">Style</span> · styles/base/reset.css" },
            { icon: "🎨", iconTone: "is-module", title: "variables.css",   description: "CSS custom properties · color / spacing / radius",       meta: "<span class=\"accent\">Style</span> · styles/base/variables.css" },
            { icon: "📐", iconTone: "is-module", title: "app.css",         description: "Application shell layout · topbar / main / bottomNav",   meta: "<span class=\"accent\">Style</span> · styles/layout/app.css" },
            { icon: "⬇", iconTone: "is-module", title: "footer.css",      description: "Footer bar styles · safe-area insets",                   meta: "<span class=\"accent\">Style</span> · styles/layout/footer.css" },
            { icon: "⬆", iconTone: "is-module", title: "topbar.css",      description: "Topbar styles · date nav / title / back button",         meta: "<span class=\"accent\">Style</span> · styles/layout/topbar.css" },
            { icon: "📋", iconTone: "is-module", title: "index.css",       description: "Style barrel import · @import all module styles",       meta: "<span class=\"accent\">Style</span> · styles/index.css" }
          ]
        },
        {
          id:    "src-views",
          kind:  "items",
          icon:  "🏠",
          title: "Views & Entry (6 + 1)",
          items: [
            { icon: "🚀", iconTone: "is-module", title: "index.js",         description: "App entry · IIFE wiring all modules together",         meta: "<span class=\"accent\">View</span> · views/home/index.js" },
            { icon: "🧭", iconTone: "is-module", title: "router.js",        description: "Hash-based router · parseRoute / navigateToChat",       meta: "<span class=\"accent\">View</span> · views/home/router.js" },
            { icon: "📊", iconTone: "is-module", title: "state.js",         description: "Global state · reactive session/news/filter/chat state", meta: "<span class=\"accent\">View</span> · views/home/state.js" },
            { icon: "💬", iconTone: "is-module", title: "chat.js",          description: "Chat factory · message rendering + streaming + persist", meta: "<span class=\"accent\">View</span> · views/home/chat.js" },
            { icon: "📄", iconTone: "is-module", title: "page-context.js",  description: "Page context panel · optimize / translate / save",      meta: "<span class=\"accent\">View</span> · views/home/page-context.js" },
            { icon: "🌐", iconTone: "is-module", title: "index.html",       description: "HTML shell · SVG sprite + debug panel + CDN libs",     meta: "<span class=\"accent\">View</span> · views/home/index.html" },
            { icon: "⚙️", iconTone: "is-module", title: "config.js",        description: "App config · apiBase / endpoints / news / ui settings", meta: "<span class=\"accent\">Config</span> · config.js" }
          ]
        },
        {
          id:    "src-mermaid",
          kind:  "items",
          icon:  "📊",
          title: "Mermaid Integration (10)",
          items: [
            { icon: "⚙️", iconTone: "is-module", title: "MermaidConfig.js",   description: "Mermaid default config · theme / security / font",    meta: "<span class=\"accent\">Mermaid</span> · mermaid/core/" },
            { icon: "🎨", iconTone: "is-module", title: "MermaidRenderer.js", description: "Mermaid render pipeline · render + error handling",  meta: "<span class=\"accent\">Mermaid</span> · mermaid/core/" },
            { icon: "🔧", iconTone: "is-module", title: "AIFixPlugin.js",     description: "AI-powered diagram fix · prompt-based correction",    meta: "<span class=\"accent\">Mermaid</span> · mermaid/plugins/" },
            { icon: "📋", iconTone: "is-module", title: "ClipboardPlugin.js", description: "Copy diagram to clipboard · PNG/SVG export",          meta: "<span class=\"accent\">Mermaid</span> · mermaid/plugins/" },
            { icon: "⬇", iconTone: "is-module", title: "DownloadPlugin.js",   description: "Download diagram as file · PNG/SVG format",           meta: "<span class=\"accent\">Mermaid</span> · mermaid/plugins/" },
            { icon: "🖥", iconTone: "is-module", title: "FullscreenPlugin.js",description: "Fullscreen toggle · diagram maximized view",           meta: "<span class=\"accent\">Mermaid</span> · mermaid/plugins/" },
            { icon: "🧰", iconTone: "is-module", title: "ToolbarPlugin.js",   description: "Diagram toolbar · zoom / reset / fit controls",       meta: "<span class=\"accent\">Mermaid</span> · mermaid/plugins/" }
          ]
        }
      ]
    }
  ],

  footerLinks: [
    { label: "CLAUDE.md",  href: "../CLAUDE.md",  targetBlank: true },
    { label: "README.md",  href: "../README.md",  targetBlank: true },
    { label: "YiH5 Repo",  href: "../../../YiH5/", targetBlank: true }
  ]
};
