/**
 * YiH5 · Dashboard data model
 * Generated by yry-init pipeline (steps 01–05)
 */
window.HELP_CONFIG = {
  titleIcon:     "★",
  title:         "YiH5 · H5 Frontend Application",
  tagline:       "Vanilla JS ES-module SPA · Chat + News + Session · Powered by api.effiy.cn",
  backTopLabel:  "返回顶部",
  footerNote:    "由 yry-init 流水线生成 (detect → explore → generate → arch → verify) · 项目根: /Users/ruiyi/Downloads/YrY/YiH5/",

  breadcrumb: [
    { label: "YiDoc", href: "../../index.html" },
    { label: "Projects", href: "../../dashboard/index.html" },
    { label: "YiH5" }
  ],

  stats: [
    { value: "0",  label: "Runtime Deps",  modifier: "cyan",   sub: "libs" },
    { value: "0",  label: "Dev Deps",      modifier: "cyan",   sub: "libs" },
    { value: "11", label: "Source Files",  modifier: "accent", sub: "top-level src" },
    { value: "11", label: "Scenes",         modifier: "accent", sub: "arch + test" }
  ],

  panelHub: {
    label: { text: '📊', panel: 'reports', title: 'YiH5 文档导航' },
    targetBlank: false,
    buttons: [
      { icon: '🏛', name: 'Architecture', desc: '5 个架构场景',  color: 'var(--yry-accent)', panel: 'arch' },
      { icon: '✅', name: 'Self-Check',    desc: '6 个自检场景',  color: 'var(--yry-cyan)',  panel: 'test' },
      { icon: '📁', name: 'Files',         desc: '文件体检',       color: 'var(--yry-info)', panel: 'files' },
      { icon: '🔌', name: 'APIs',          desc: 'API 审计',       color: 'var(--yry-warn)',  panel: 'apis' }
    ],
    flow: '架构分析 → 自检策略 → 文件体检 → API 审计',
    urls: {
      arch:  '../../templates/arch/index.html?project=YiH5',
      test:  '../../templates/test/index.html?project=YiH5',
      files: '../../templates/files/index.html?project=YiH5',
      apis:  '../../templates/apis/index.html?project=YiH5',
      daily: '../../templates/daily/cto-report.html?project=YiH5',
    },
  },

  reportsList: {
    daily: [],
    weekly: [],
    monthly: []
  },

  // ── § 1 · Third-party dependencies & frameworks ────────────────────
  sections: [
    {
      id:    "section-dependencies",
      badge: "1",
      title: "Third-Party Dependencies / Frameworks",
      meta:  "0 runtime libs · 0 dev deps · vanilla JS",
      groups: [
        {
          id:    "deps-runtime",
          kind:  "items",
          icon:  "📦",
          title: "Runtime Libraries (0)",
          items: []
        },
        {
          id:    "deps-dev",
          kind:  "items",
          icon:  "🛠",
          title: "Dev Dependencies (0)",
          items: []
        }
      ]
    },

    // ── § 2 · Story documents & scenes ─────────────────────────────────
    {
      id:    "section-stories",
      badge: "2",
      title: "Story Documents & Scenes",
      meta:  "2 stories · 11 scenes · self-check oriented",
      groups: [
        {
          kind:  "stories",
          icon:  "📚",
          title: "Story Catalog (arch + test)",
          items: [
            {
              icon:        "🏛",
              title:       "System Architecture & Knowledge Codification",
              badge:       "5 scenes",
              description: "Module location · data flow tracing · newcomer onboarding · dependency impact · <strong>trust boundary / security surface</strong>",
              sceneLinks: [
                { label: "1. Module Location",                href: "../../projects/YiH5/arch/scene-1-module-location/index.md" },
                { label: "2. Data Flow Tracing",               href: "../../projects/YiH5/arch/scene-2-data-flow-tracing/index.md" },
                { label: "3. Newcomer Onboarding",            href: "../../projects/YiH5/arch/scene-3-newcomer-onboarding/index.md" },
                { label: "4. Dependency Impact",               href: "../../projects/YiH5/arch/scene-4-dependency-change-impact/index.md" },
                { label: "5. Security Surface",               href: "../../projects/YiH5/arch/scene-5-trust-boundary-security-surface/index.md" }
              ],
              links: [
                { label: "Architecture Dashboard →", href: "../../templates/arch/index.html?project=YiH5" }
              ],
              meta: "5 scenes · risk: medium · vanilla JS ES-module SPA"
            },
            {
              icon:        "✅",
              title:       "Self-Check Strategy Suite",
              badge:       "6 scenes",
              description: "Post-init · pre-commit · doc-code consistency · <strong>security regression · integration regression · third-party</strong>",
              sceneLinks: [
                { label: "1. Post-Init Self-Check",          href: "../../projects/YiH5/test/scene-1-post-init-full-self-check/index.md" },
                { label: "2. Pre-Commit Self-Check",         href: "../../projects/YiH5/test/scene-2-pre-commit-incremental-self-check/index.md" },
                { label: "3. Doc Consistency",               href: "../../projects/YiH5/test/scene-3-doc-code-consistency/index.md" },
                { label: "4. Security Regression",            href: "../../projects/YiH5/test/scene-4-security-surface-regression/index.md" },
                { label: "5. Integration Regression",         href: "../../projects/YiH5/test/scene-5-cross-story-integration-regression/index.md" },
                { label: "6. Third-Party Services",          href: "../../projects/YiH5/test/scene-6-third-party-framework-service/index.md" }
              ],
              links: [
                { label: "Test Dashboard →", href: "../../templates/test/index.html?project=YiH5" }
              ],
              meta: "6 scenes · risk: low · manual self-check"
            }
          ]
        }
      ]
    },

    // ── § 3 · Main source code ─────────────────────────────────────────
    {
      id:    "section-source",
      badge: "3",
      title: "Main Source Code",
      meta:  "1 entry · 1 App · 4 components · 3 views · 7 services · 2 composables · 2 utils · 1 store · 1 router",
      groups: [
        {
          id:    "src-entry",
          kind:  "items",
          icon:  "🚀",
          title: "Entry & Config (3)",
          items: [
            { icon: "🚀", iconTone: "is-module", title: "main.js",         description: "App entry · ES-module bootstrap · mounts #app",                       meta: "<span class=\"accent\">Entry</span> · src/main.js" },
            { icon: "⚙️", iconTone: "is-module", title: "config.js",       description: "App config · apiBase / endpoints / news / ui settings",                meta: "<span class=\"accent\">Config</span> · config.js" },
            { icon: "🌐", iconTone: "is-module", title: "index.html",      description: "HTML shell · #app mount point · viewport meta",                        meta: "<span class=\"accent\">Shell</span> · index.html" }
          ]
        },
        {
          id:    "src-app",
          kind:  "items",
          icon:  "🧩",
          title: "App Shell (1)",
          items: [
            { icon: "🧩", iconTone: "is-module", title: "App",     description: "Root app component · fetches own template · wires router + store",  meta: "<span class=\"accent\">App</span> · src/App/" }
          ]
        },
        {
          id:    "src-components",
          kind:  "items",
          icon:  "🧱",
          title: "UI Components (4)",
          items: [
            { icon: "🔍", iconTone: "is-module", title: "FilterBar",   description: "Filter bar · query binding + clear",                       meta: "<span class=\"accent\">Component</span> · src/components/FilterBar/" },
            { icon: "💬", iconTone: "is-module", title: "ChatMessage", description: "Chat message bubble · markdown + mermaid render",           meta: "<span class=\"accent\">Component</span> · src/components/ChatMessage/" },
            { icon: "🦶", iconTone: "is-module", title: "AppFooter",   description: "App footer · nav + safe-area inset",                        meta: "<span class=\"accent\">Component</span> · src/components/AppFooter/" },
            { icon: "❓", iconTone: "is-module", title: "FaqPopup",    description: "FAQ popup · query_documents from faqs collection",          meta: "<span class=\"accent\">Component</span> · src/components/FaqPopup/" }
          ]
        },
        {
          id:    "src-views",
          kind:  "items",
          icon:  "🏠",
          title: "Views (3)",
          items: [
            { icon: "💬", iconTone: "is-module", title: "ChatView",   description: "Chat view · message rendering + streaming + persist",       meta: "<span class=\"accent\">View</span> · src/views/ChatView/" },
            { icon: "📜", iconTone: "is-module", title: "SessionList", description: "Session list · swipe-to-delete / favorite",                   meta: "<span class=\"accent\">View</span> · src/views/SessionList/" },
            { icon: "📰", iconTone: "is-module", title: "NewsList",   description: "News list · virtual scroll + read tracking",                meta: "<span class=\"accent\">View</span> · src/views/NewsList/" }
          ]
        },
        {
          id:    "src-services",
          kind:  "items",
          icon:  "🔌",
          title: "API Services (7)",
          items: [
            { icon: "🌐", iconTone: "is-module", title: "client.js",   description: "HTTP client · fetchWithAuth + executeModule + extractList",  meta: "<span class=\"accent\">Service</span> · src/services/client.js" },
            { icon: "🔑", iconTone: "is-module", title: "auth.js",     description: "Token storage · X-Token via localStorage",                     meta: "<span class=\"accent\">Service</span> · src/services/auth.js" },
            { icon: "🤖", iconTone: "is-module", title: "prompt.js",   description: "AI Prompt API · streaming SSE + think-tag stripping",        meta: "<span class=\"accent\">Service</span> · src/services/prompt.js" },
            { icon: "📡", iconTone: "is-module", title: "news.js",      description: "News API · query_documents from rss collection",              meta: "<span class=\"accent\">Service</span> · src/services/news.js" },
            { icon: "❓", iconTone: "is-module", title: "faq.js",       description: "FAQ API · query_documents from faqs collection",               meta: "<span class=\"accent\">Service</span> · src/services/faq.js" },
            { icon: "💾", iconTone: "is-module", title: "session.js",   description: "Session CRUD · query / upsert / delete via executeModule",    meta: "<span class=\"accent\">Service</span> · src/services/session.js" },
            { icon: "📦", iconTone: "is-module", title: "index.js",    description: "Service barrel export · unified API surface",                meta: "<span class=\"accent\">Service</span> · src/services/index.js" }
          ]
        },
        {
          id:    "src-composables",
          kind:  "items",
          icon:  "🧰",
          title: "Composables (2)",
          items: [
            { icon: "💬", iconTone: "is-module", title: "useChat",      description: "Chat composable · message state + streaming + persist",   meta: "<span class=\"accent\">Composable</span> · src/composables/useChat.js" },
            { icon: "📋", iconTone: "is-module", title: "useListPage",  description: "List-page composable · pagination + filter + sort",       meta: "<span class=\"accent\">Composable</span> · src/composables/useListPage.js" }
          ]
        },
        {
          id:    "src-utils",
          kind:  "items",
          icon:  "🔧",
          title: "Utility Modules (2)",
          items: [
            { icon: "🧭", iconTone: "is-module", title: "defineView.js", description: "View factory · template cache + async component",      meta: "<span class=\"accent\">Util</span> · src/utils/defineView.js" },
            { icon: "⏱", iconTone: "is-module", title: "time.js",        description: "Time helpers · format + relative + ISO",                meta: "<span class=\"accent\">Util</span> · src/utils/time.js" }
          ]
        },
        {
          id:    "src-store-router",
          kind:  "items",
          icon:  "🗃",
          title: "Store & Router (2)",
          items: [
            { icon: "🗃", iconTone: "is-module", title: "store",  description: "Global store · reactive session/news/filter/chat state",  meta: "<span class=\"accent\">Store</span> · src/store/index.js" },
            { icon: "🧭", iconTone: "is-module", title: "router", description: "Hash-based router · route table + view switch",            meta: "<span class=\"accent\">Router</span> · src/router/index.js" }
          ]
        },
        {
          id:    "src-styles",
          kind:  "items",
          icon:  "🎨",
          title: "Styles (1)",
          items: [
            { icon: "🎨", iconTone: "is-module", title: "style.css", description: "Global stylesheet · layout / typography / theme",  meta: "<span class=\"accent\">Style</span> · src/styles/style.css" }
          ]
        }
      ]
    }
  ],

  footerLinks: [
    { label: "CLAUDE.md",  href: "CLAUDE.md",  targetBlank: true },
    { label: "README.md",  href: "README.md",  targetBlank: true },
    { label: "YiH5 Repo",  href: "../../../YiH5/", targetBlank: true },
    { label: "Story Report →", href: "story/index.html" }
  ]
};
