/**
 * Websites · Static HTML Template Collection · Dashboard data model
 * --------------------------------------------------------------------------
 * Generated by rui-init-generate (step ③ of the rui-init pipeline).
 * Consumed by index.html (Vue 3) via window.HELP_CONFIG.
 */

window.HELP_CONFIG = {
  titleIcon:     "★",
  title:         "Websites · Static HTML Template Collection",
  tagline:       "14 independent static HTML website templates · Bootstrap / Tailwind / jQuery / Swiper · standalone HTML / CSS / JS",
  backTopLabel:  "Back to Top",
  footerNote:    "Generated by rui-init pipeline · detect → explore → generate → arch → verify",

  breadcrumb: [
    { label: "YiDoc", href: "../../index.html" },
    { label: "Websites" }
  ],

  stats: [
    { value: "14",  label: "Templates",       modifier: "accent", sub: "websites" },
    { value: "282", label: "HTML Pages",      modifier: "cyan",   sub: "pages" },
    { value: "39",  label: "CSS Stylesheets", modifier: "cyan",   sub: "stylesheets" },
    { value: "89",  label: "JS Scripts",      modifier: "accent", sub: "scripts" }
  ],

  panelHub: {
    label: { text: '📊', panel: 'reports', title: 'Report Dashboards' },
    targetBlank: true,
    buttons: [
      { icon: '🏛', name: 'Architecture', desc: 'Markdown scenes', color: 'var(--rui-accent)', panel: 'arch' },
      { icon: '✅', name: 'test', desc: 'Self-check strategy', color: 'var(--rui-cyan)', panel: 'test', targetBlank: false },
    ],
    flow: 'Module Map → Dependency Audit → Security Surface → Self-Check',
    urls: {
      arch: 'arch/index.html',
      'test': 'test/index.html',
    },
  },

  reportsList: {
    daily: [],
    weekly: [],
    monthly: [],
  },

  sections: [
    // ── § 1 · Third-party dependencies & frameworks ────────────────────
    {
      id:    "section-dependencies",
      badge: "1",
      title: "Third-Party Dependencies / Frameworks",
      meta:  "11 runtime · 2 dev deps · shared across 14 template websites",
      groups: [
        {
          id:    "deps-runtime",
          kind:  "items",
          icon:  "📦",
          title: "Runtime Dependencies (11)",
          items: [
            {
              icon:        "B",
              iconTone:    "is-module",
              title:       "Bootstrap",
              description: "Responsive CSS framework · <strong>grid system + components</strong> · used by Arter, Kasy, Corporato, Prompt, News, Mortal",
              meta:        "<span class=\"accent\">Runtime</span> · ^4.x / ^5.x"
            },
            {
              icon:        "T",
              iconTone:    "is-module",
              title:       "Tailwind CSS",
              description: "Utility-first CSS framework · <strong>atomic classes</strong> · used by Adminto, Mortal",
              meta:        "<span class=\"accent\">Runtime</span> · ^3.x"
            },
            {
              icon:        "J",
              iconTone:    "is-module",
              title:       "jQuery",
              description: "DOM manipulation library · <strong>cross-browser compatibility</strong> · used by Arter, Blog, Corporato, Duck, Adminto",
              meta:        "<span class=\"accent\">Runtime</span> · ^3.x"
            },
            {
              icon:        "S",
              iconTone:    "is-module",
              title:       "Swiper",
              description: "Touch slider / carousel · <strong>mobile-first gestures</strong> · used by Arter, Kasy, Adminto",
              meta:        "<span class=\"accent\">Runtime</span> · ^8.x"
            },
            {
              icon:        "A",
              iconTone:    "is-module",
              title:       "AOS",
              description: "Animate On Scroll library · <strong>scroll-triggered animations</strong> · used by Prompt, Mortal",
              meta:        "<span class=\"accent\">Runtime</span> · ^2.x"
            },
            {
              icon:        "F",
              iconTone:    "is-module",
              title:       "Fancybox",
              description: "Lightbox gallery · <strong>image/video zoom</strong> · used by Arter, Blog",
              meta:        "<span class=\"accent\">Runtime</span> · ^3.x / ^4.x"
            },
            {
              icon:        "C",
              iconTone:    "is-module",
              title:       "Chart.js",
              description: "Canvas-based charting · <strong>bar / line / pie</strong> · used by Adminto",
              meta:        "<span class=\"accent\">Runtime</span> · ^3.x"
            },
            {
              icon:        "P",
              iconTone:    "is-module",
              title:       "ApexCharts",
              description: "Interactive SVG charts · <strong>area / donut / radar</strong> · used by Adminto, DpMarket, Kasy",
              meta:        "<span class=\"accent\">Runtime</span> · ^3.x"
            },
            {
              icon:        "V",
              iconTone:    "is-module",
              title:       "Vue 3",
              description: "Progressive JavaScript framework · <strong>Composition API</strong> · used by Flow",
              meta:        "<span class=\"accent\">Runtime</span> · ^3.4.x"
            },
            {
              icon:        "E",
              iconTone:    "is-module",
              title:       "Element Plus",
              description: "Vue 3 UI component library · <strong>desktop-first</strong> · used by Flow",
              meta:        "<span class=\"accent\">Runtime</span> · ^2.x"
            },
            {
              icon:        "R",
              iconTone:    "is-module",
              title:       "React",
              description: "Declarative UI library · <strong>JSX components</strong> · used by Duck (CDN)",
              meta:        "<span class=\"accent\">Runtime</span> · ^16.x (CDN)"
            }
          ]
        },
        {
          id:    "deps-dev",
          kind:  "items",
          icon:  "🛠",
          title: "Dev Dependencies (2)",
          items: [
            {
              icon:        "G",
              iconTone:    "is-module",
              title:       "Gulp",
              description: "Task runner · <strong>Sass compilation + minification</strong> · used by Adminto build pipeline",
              meta:        "<span class=\"accent\">Dev</span> · ^4.x"
            },
            {
              icon:        "☁",
              iconTone:    "is-module",
              title:       "http-server",
              description: "Zero-config static file server · <strong>quick local preview</strong> · used by Prompt for development",
              meta:        "<span class=\"accent\">Dev</span> · ^14.x"
            }
          ]
        }
      ]
    },

    // ── § 2 · Story documents & scenes ─────────────────────────────────
    {
      id:    "section-stories",
      badge: "2",
      title: "Story Documents & Scenes",
      meta:  "2 stories · 11 scenes · all self-checks pending",
      groups: [
        {
          kind:  "stories",
          icon:  "📚",
          title: "Story Catalog (arch + test)",
          items: [
            {
              icon:        "🏛",
              title:       "System Architecture & Knowledge Codification",
              badge:       "5 scenes",
              description: "Module location map · data-flow from HTML to browser render · dependency impact analysis · <strong>trust boundary audit</strong>",
              sceneLinks: [
                { label: "1. Module Location",          href: "arch/scene-1-module-location/index.md" },
                { label: "2. Data Flow Tracing",         href: "arch/scene-2-data-flow-tracing/index.md" },
                { label: "3. Newcomer Onboarding",      href: "arch/scene-3-newcomer-onboarding/index.md" },
                { label: "4. Dependency Impact",         href: "arch/scene-4-dependency-change-impact/index.md" },
                { label: "5. Security Surface",         href: "arch/scene-5-trust-boundary-security-surface/index.md" }
              ],
              meta: "5 scenes · risk: low · static HTML = minimal surface"
            },
            {
              icon:        "✅",
              title:       "Self-Check Strategy Suite",
              badge:       "6 scenes",
              description: "Full post-init verification · pre-commit incremental check · <strong>doc-code consistency scan</strong> · security + integration regression",
              sceneLinks: [
                { label: "1. Post-Init Self-Check",    href: "test/scene-1-post-init-full-self-check/index.md" },
                { label: "2. Pre-Commit Self-Check",  href: "test/scene-2-pre-commit-incremental-self-check/index.md" },
                { label: "3. Doc Consistency",         href: "test/scene-3-doc-code-consistency/index.md" },
                { label: "4. Security Regression",     href: "test/scene-4-security-surface-regression/index.md" },
                { label: "5. Integration Regression",  href: "test/scene-5-cross-story-integration-regression/index.md" },
                { label: "6. Third-Party Services",   href: "test/scene-6-third-party-framework-service/index.md" }
              ],
              meta: "6 scenes · risk: low · static HTML template collection"
            }
          ]
        }
      ]
    },

    // ── § 3 · Main source code ─────────────────────────────────────────
    {
      id:    "section-source",
      badge: "3",
      title: "Main Source Code",
      meta:  "14 websites · 282 HTML pages · 39 CSS stylesheets · 89 JS scripts",
      groups: [
        {
          id:    "src-adminto",
          kind:  "items",
          icon:  "🧩",
          title: "Adminto · Tailwind Admin Dashboard (104 pages)",
          items: [
            { icon: "🏠", iconTone: "is-module", title: "Adminto/Admin/dist/", description: "Tailwind CSS admin dashboard · <strong>ApexCharts + Chart.js + Swiper</strong> · gulp build pipeline", meta: "<span class=\"accent\">Adminto</span> · Admin/dist/" },
            { icon: "📄", iconTone: "is-module", title: "Adminto/Admin/src/",   description: "Gulp source · partials (main.html, menu.html) · tailwind config", meta: "<span class=\"accent\">Adminto</span> · Admin/src/" }
          ]
        },
        {
          id:    "src-arter",
          kind:  "items",
          icon:  "🎨",
          title: "Arter · Portfolio Template (14 pages)",
          items: [
            { icon: "🖼", iconTone: "is-module", title: "Arter/", description: "Creative portfolio · <strong>Bootstrap + Swiper + Fancybox</strong> · SCSS source · isotope filtering", meta: "<span class=\"accent\">Arter</span> · /" }
          ]
        },
        {
          id:    "src-blog",
          kind:  "items",
          icon:  "📝",
          title: "Blog · Chinese Blog Theme (12 pages)",
          items: [
            { icon: "📰", iconTone: "is-module", title: "Blog/", description: "Chinese-style blog · <strong>jQuery + Fancybox</strong> · custom photo-text viewer", meta: "<span class=\"accent\">Blog</span> · /" }
          ]
        },
        {
          id:    "src-blogez",
          kind:  "items",
          icon:  "✍️",
          title: "Blogez · Minimal Blog (1 page)",
          items: [
            { icon: "📋", iconTone: "is-module", title: "Blogez/", description: "Single-page blog layout · <strong>pure CSS</strong> · clean typography design", meta: "<span class=\"accent\">Blogez</span> · /" }
          ]
        },
        {
          id:    "src-cards",
          kind:  "items",
          icon:  "🃏",
          title: "Cards · Card UI Template (1 page)",
          items: [
            { icon: "💳", iconTone: "is-module", title: "Cards/", description: "Single-page card layout · <strong>custom CSS + vanilla JS</strong> · minimalist design", meta: "<span class=\"accent\">Cards</span> · /" }
          ]
        },
        {
          id:    "src-corporato",
          kind:  "items",
          icon:  "🏢",
          title: "Corporato · Business Landing (1 page)",
          items: [
            { icon: "🏛", iconTone: "is-module", title: "Corporato/", description: "Corporate landing page · <strong>Bootstrap + jQuery + Owl Carousel</strong> · video lightbox", meta: "<span class=\"accent\">Corporato</span> · /" }
          ]
        },
        {
          id:    "src-dpmarket",
          kind:  "items",
          icon:  "🛒",
          title: "DpMarket · Digital Marketplace (26 pages)",
          items: [
            { icon: "🏪", iconTone: "is-module", title: "DpMarket/", description: "Digital product marketplace · <strong>SASS + ApexCharts + Slick</strong> · cart + dashboard flow", meta: "<span class=\"accent\">DpMarket</span> · /" }
          ]
        },
        {
          id:    "src-duck",
          kind:  "items",
          icon:  "🦆",
          title: "Duck · React Animation Demo (1 page)",
          items: [
            { icon: "⚛", iconTone: "is-module", title: "Duck/", description: "React CDN animation demo · <strong>React + TweenMax</strong> · single-page interactive", meta: "<span class=\"accent\">Duck</span> · /" }
          ]
        },
        {
          id:    "src-flow",
          kind:  "items",
          icon:  "🌊",
          title: "Flow · Vue 3 Flow Designer (1 page)",
          items: [
            { icon: "🔀", iconTone: "is-module", title: "Flow/", description: "Vue 3 + Vite flow designer · <strong>LogicFlow + Element Plus + Ant Design Vue</strong> · TypeScript", meta: "<span class=\"accent\">Flow</span> · /" }
          ]
        },
        {
          id:    "src-kasy",
          kind:  "items",
          icon:  "📱",
          title: "Kasy · App Landing (2 pages)",
          items: [
            { icon: "📲", iconTone: "is-module", title: "Kasy/", description: "Mobile app landing page · <strong>Bootstrap + Swiper + ApexCharts</strong> · SCSS source", meta: "<span class=\"accent\">Kasy</span> · /" }
          ]
        },
        {
          id:    "src-mortal",
          kind:  "items",
          icon:  "🤖",
          title: "Mortal · AI/Startup Template (18 pages)",
          items: [
            { icon: "🧠", iconTone: "is-module", title: "Mortal/", description: "AI/startup multi-page · <strong>Tailwind CSS + Bootstrap</strong> · auth + blog + pricing", meta: "<span class=\"accent\">Mortal</span> · /" }
          ]
        },
        {
          id:    "src-news",
          kind:  "items",
          icon:  "📰",
          title: "News · Magazine Portal (20 pages)",
          items: [
            { icon: "📡", iconTone: "is-module", title: "News/", description: "News magazine layout · <strong>Slick + WOW.js</strong> · multiple category layouts", meta: "<span class=\"accent\">News</span> · /" }
          ]
        },
        {
          id:    "src-prompt",
          kind:  "items",
          icon:  "💬",
          title: "Prompt · Multi-Purpose Landing (30 pages)",
          items: [
            { icon: "🚀", iconTone: "is-module", title: "Prompt/", description: "Multi-purpose landing pages · <strong>Bootstrap + AOS + Leaflet</strong> · agency / SaaS / crypto / startup", meta: "<span class=\"accent\">Prompt</span> · /" }
          ]
        },
        {
          id:    "src-socialite",
          kind:  "items",
          icon:  "👥",
          title: "Socialite · Social Network UI (31 pages)",
          items: [
            { icon: "🌐", iconTone: "is-module", title: "Socialite/", description: "Social network template · <strong>custom CSS + vanilla JS</strong> · feed / groups / market / events", meta: "<span class=\"accent\">Socialite</span> · /" }
          ]
        }
      ]
    }
  ],

  footerLinks: [
    { label: "CLAUDE.md",  href: "../CLAUDE.md",  targetBlank: true },
    { label: "README.md",  href: "../README.md",  targetBlank: true }
  ]
};
