/**
 * YiPot · Dashboard data model
 * --------------------------------------------------------------------------
 * Generated by rui-init pipeline (step ③) for the YiPot Tauri desktop
 * translation tool. The data model mirrors the HELP_CONFIG shape consumed
 * by the rui-init standalone dashboard template.
 */
window.HELP_CONFIG = {
  titleIcon:     "★",
  title:         "YiPot · Tauri Desktop Translation Tool",
  tagline:       "Cross-platform desktop translator & OCR — 21 translation engines · 15 recognize backends · TTS & collection services · Tauri + React fullstack architecture",
  backTopLabel:  "Back to Top",
  footerNote:    "Generated by rui-init pipeline · detect → explore → generate → arch → verify",

  breadcrumb: [
    { label: "YiDoc", href: "../index.html" },
    { label: "YiPot · Dashboard" }
  ],

  // High-level KPIs
  stats: [
    { value: "21", label: "Translate Services", modifier: "cyan",   sub: "translation engines" },
    { value: "15", label: "Recognize Services", modifier: "cyan",   sub: "OCR backends" },
    { value: "1",  label: "TTS Services",       modifier: "accent", sub: "text-to-speech" },
    { value: "55+", label: "Source Files",       modifier: "accent", sub: "frontend + Rust backend" }
  ],

  panelHub: {
    label: { text: '📊', panel: 'reports', title: 'Report Dashboards' },
    targetBlank: true,
    buttons: [
      { icon: '🏛', name: 'Architecture', desc: 'Architecture scenes', color: 'var(--rui-accent)', panel: 'arch' },
      { icon: '✅', name: 'Test',          desc: 'Self-check strategy',  color: 'var(--rui-cyan)',    panel: 'test', targetBlank: false },
    ],
    flow: 'File Analysis → Architecture Review → Self-Check Strategy',
    urls: {
      arch: 'arch/index.html',
      test: 'test/index.html',
    },
  },

  reportsList: {
    daily: [],
    weekly: [],
    monthly: [],
  },

  // ── § 1 · Third-party dependencies & frameworks ────────────────────
  sections: [
    {
      id:    "section-dependencies",
      badge: "1",
      title: "Third-Party Dependencies / Frameworks",
      meta:  "29 npm runtime · 9 npm dev · 20+ Rust crates",
      groups: [
        {
          id:    "deps-runtime",
          kind:  "items",
          icon:  "📦",
          title: "NPM Runtime Dependencies (29)",
          items: [
            { icon: "R", iconTone: "is-module", title: "React 18",        description: "Declarative UI framework · <strong>Tauri desktop shell</strong>",                meta: "<span class=\"accent\">Runtime</span> · ^18.3.1" },
            { icon: "R", iconTone: "is-module", title: "React Router",    description: "Client-side routing for multi-window navigation · <strong>BrowserRouter</strong>",  meta: "<span class=\"accent\">Runtime</span> · ^6.27.0" },
            { icon: "T", iconTone: "is-module", title: "Tauri API",       description: "Bridge to native Rust backend · <strong>IPC + window APIs</strong>",                meta: "<span class=\"accent\">Runtime</span> · ^1.6.0" },
            { icon: "N", iconTone: "is-module", title: "NextUI",          description: "React component library · <strong>Desktop-styled UI kit</strong>",                   meta: "<span class=\"accent\">Runtime</span> · ^2.4.8" },
            { icon: "N", iconTone: "is-module", title: "Next Themes",     description: "Dark/light/system theme switching · <strong>ThemeProvider</strong>",               meta: "<span class=\"accent\">Runtime</span> · ^0.3.0" },
            { icon: "J", iconTone: "is-module", title: "Jotai",           description: "Atomic state management · <strong>primitive React state</strong>",                   meta: "<span class=\"accent\">Runtime</span> · ^2.10.1" },
            { icon: "F", iconTone: "is-module", title: "Framer Motion",   description: "Declarative animation library · <strong>enter/exit transitions</strong>",            meta: "<span class=\"accent\">Runtime</span> · ^11.11.10" },
            { icon: "I", iconTone: "is-module", title: "i18next",         description: "Internationalization framework · <strong>multi-language UI</strong>",               meta: "<span class=\"accent\">Runtime</span> · ^23.16.4" },
            { icon: "I", iconTone: "is-module", title: "react-i18next",   description: "React bindings for i18next · <strong>useTranslation hook</strong>",                 meta: "<span class=\"accent\">Runtime</span> · ^15.1.0" },
            { icon: "M", iconTone: "is-module", title: "React Markdown",  description: "Markdown rendering in translate results · <strong>LLM output</strong>",             meta: "<span class=\"accent\">Runtime</span> · ^9.0.1" },
            { icon: "C", iconTone: "is-module", title: "CryptoJS",        description: "Encryption/hashing for API signing · <strong>AES + MD5</strong>",                   meta: "<span class=\"accent\">Runtime</span> · ^4.2.0" },
            { icon: "J", iconTone: "is-module", title: "jose",            description: "JWT/JWS/JWE for OAuth flows · <strong>API authentication</strong>",                meta: "<span class=\"accent\">Runtime</span> · ^5.9.6" },
            { icon: "O", iconTone: "is-module", title: "ollama (JS)",     description: "Ollama LLM client for local translation · <strong>local LLM</strong>",              meta: "<span class=\"accent\">Runtime</span> · ^0.5.9" },
            { icon: "T", iconTone: "is-module", title: "Tesseract.js",    description: "Browser-side OCR engine · <strong>WASM-based</strong>",                             meta: "<span class=\"accent\">Runtime</span> · ^5.1.1" },
            { icon: "Q", iconTone: "is-module", title: "jsQR",            description: "QR code detection · <strong>recognize service</strong>",                          meta: "<span class=\"accent\">Runtime</span> · ^1.4.0" },
            { icon: "D", iconTone: "is-module", title: "react-beautiful-dnd", description: "Drag-and-drop for service ordering · <strong>Config panel</strong>",            meta: "<span class=\"accent\">Runtime</span> · ^13.1.1" },
          ]
        },
        {
          id:    "deps-dev",
          kind:  "items",
          icon:  "🛠",
          title: "NPM Dev Dependencies (9)",
          items: [
            { icon: "V", iconTone: "is-module", title: "Vite",              description: "Frontend build tool · <strong>fast HMR + bundling</strong>",                     meta: "<span class=\"accent\">Dev</span> · ^5.4.10" },
            { icon: "T", iconTone: "is-module", title: "Tailwind CSS",      description: "Utility-first CSS framework · <strong>NextUI dependency</strong>",               meta: "<span class=\"accent\">Dev</span> · ^3.4.14" },
            { icon: "P", iconTone: "is-module", title: "Prettier",          description: "Code formatter · <strong>consistent style</strong>",                             meta: "<span class=\"accent\">Dev</span> · 3.3.2" },
            { icon: "T", iconTone: "is-module", title: "TypeScript",        description: "Type-checking · <strong>info.ts service descriptors</strong>",                   meta: "<span class=\"accent\">Dev</span> · ^5.6.3" },
            { icon: "P", iconTone: "is-module", title: "PostCSS",           description: "CSS post-processor · <strong>autoprefixer + tailwind</strong>",                  meta: "<span class=\"accent\">Dev</span> · ^8.4.47" },
            { icon: "T", iconTone: "is-module", title: "Tauri CLI",         description: "Tauri build pipeline · <strong>desktop bundling</strong>",                      meta: "<span class=\"accent\">Dev</span> · ^1.6.3" },
          ]
        },
        {
          id:    "deps-rust",
          kind:  "items",
          icon:  "🦀",
          title: "Rust Crates (20+)",
          items: [
            { icon: "T", iconTone: "is-module", title: "tauri",               description: "Desktop app framework · <strong>webview + native shell</strong>",               meta: "<span class=\"accent\">Runtime</span> · 1.8" },
            { icon: "S", iconTone: "is-module", title: "serde / serde_json",  description: "Serialization · <strong>config + IPC data</strong>",                             meta: "<span class=\"accent\">Runtime</span> · 1.0" },
            { icon: "R", iconTone: "is-module", title: "reqwest",             description: "Async HTTP client · <strong>update checks + WebDAV</strong>",                    meta: "<span class=\"accent\">Runtime</span> · 0.12" },
            { icon: "H", iconTone: "is-module", title: "tiny_http",           description: "Embedded HTTP server · <strong>external tool bridge</strong>",                  meta: "<span class=\"accent\">Runtime</span> · 0.12.0" },
            { icon: "L", iconTone: "is-module", title: "lingua",              description: "Language detection · <strong>21-language support</strong>",                     meta: "<span class=\"accent\">Runtime</span> · 1.6.2" },
            { icon: "S", iconTone: "is-module", title: "screenshots",         description: "Screen capture · <strong>cross-platform screenshots</strong>",                  meta: "<span class=\"accent\">Runtime</span> · 0.7.2" },
            { icon: "C", iconTone: "is-module", title: "arboard",             description: "Clipboard access · <strong>copy/paste bridge</strong>",                         meta: "<span class=\"accent\">Runtime</span> · 3.4" },
            { icon: "B", iconTone: "is-module", title: "base64",              description: "Image encoding · <strong>OCR image transport</strong>",                         meta: "<span class=\"accent\">Runtime</span> · 0.22" },
            { icon: "Z", iconTone: "is-module", title: "zip",                 description: "Archive handling · <strong>backup service</strong>",                             meta: "<span class=\"accent\">Runtime</span> · 2.2.0" },
            { icon: "F", iconTone: "is-module", title: "font-kit",            description: "System font enumeration · <strong>font list API</strong>",                      meta: "<span class=\"accent\">Runtime</span> · 0.14.2" },
          ]
        }
      ]
    },

    // ── § 2 · Story documents & scenes ─────────────────────────────────
    {
      id:    "section-stories",
      badge: "2",
      title: "Story Documents & Scenes",
      meta:  "2 stories · 12 scenes · architecture + self-check",
      groups: [
        {
          kind:  "stories",
          icon:  "📚",
          title: "Story Catalog (arch + test)",
          items: [
            {
              icon:        "🏛",
              title:       "System Architecture & Knowledge Codification",
              badge:       "6 scenes",
              description: "Module location map · data flow tracing (clipboard → translate → output) · newcomer onboarding · dependency change impact · Tauri trust boundary + IPC security surface · <strong>IPC & window lifecycle</strong>",
              sceneLinks: [
                { label: "1. Module Location",          href: "arch/scene-1-module-location/index.md" },
                { label: "2. Data Flow Tracing",         href: "arch/scene-2-data-flow-tracing/index.md" },
                { label: "3. Newcomer Onboarding",      href: "arch/scene-3-newcomer-onboarding/index.md" },
                { label: "4. Dependency Impact",         href: "arch/scene-4-dependency-change-impact/index.md" },
                { label: "5. Security Surface",         href: "arch/scene-5-trust-boundary-security-surface/index.md" },
                { label: "6. IPC & Window Lifecycle",   href: "arch/scene-6-ipc-window-lifecycle/index.md" }
              ],
              meta: "6 scenes · risk: medium · Tauri + React fullstack"
            },
            {
              icon:        "✅",
              title:       "Self-Check Strategy",
              badge:       "6 scenes",
              description: "Post-init full check · pre-commit incremental check · doc-code consistency · security regression · cross-story integration · third-party service health monitoring",
              sceneLinks: [
                { label: "1. Post-Init Self-Check",    href: "test/scene-1-post-init-full-self-check/index.md" },
                { label: "2. Pre-Commit Self-Check",  href: "test/scene-2-pre-commit-incremental-self-check/index.md" },
                { label: "3. Doc Consistency",         href: "test/scene-3-doc-code-consistency/index.md" },
                { label: "4. Security Regression",     href: "test/scene-4-security-surface-regression/index.md" },
                { label: "5. Integration Regression",  href: "test/scene-5-cross-story-integration-regression/index.md" },
                { label: "6. Third-Party Services",   href: "test/scene-6-third-party-framework-service/index.md" }
              ],
              meta: "6 scenes · risk: low · all pass"
            }
          ]
        }
      ]
    },

    // ── § 3 · Main source code ─────────────────────────────────────────
    {
      id:    "section-source",
      badge: "3",
      title: "Main Source Code",
      meta:  "4 service categories · 5 window panels · 14 Rust modules · 7 utility modules",
      groups: [
        {
          id:    "src-services",
          kind:  "items",
          icon:  "🔌",
          title: "Frontend Services (4 categories × 39 engines)",
          items: [
            { icon: "🌐", iconTone: "is-module", title: "services/translate/",   description: "21 translation engines · DeepL, Google, OpenAI, Ollama, Bing, Yandex…",             meta: "<span class=\"accent\">Service</span> · src/services/translate/" },
            { icon: "👁", iconTone: "is-module", title: "services/recognize/",   description: "15 OCR backends · Tesseract, Baidu, iFlytek, Tencent, Volcengine, QR code…",         meta: "<span class=\"accent\">Service</span> · src/services/recognize/" },
            { icon: "🔊", iconTone: "is-module", title: "services/tts/",         description: "Text-to-speech via Lingva · voice synthesis",                                       meta: "<span class=\"accent\">Service</span> · src/services/tts/" },
            { icon: "📁", iconTone: "is-module", title: "services/collection/",  description: "Collection backends · Anki flashcard + Eudic dictionary export",                     meta: "<span class=\"accent\">Service</span> · src/services/collection/" },
          ]
        },
        {
          id:    "src-window",
          kind:  "items",
          icon:  "🪟",
          title: "Window Panels (5 views)",
          items: [
            { icon: "🌍", iconTone: "is-module", title: "window/Translate/",    description: "Main translate panel · Source/Target/Language areas with action bars",               meta: "<span class=\"accent\">Window</span> · src/window/Translate/" },
            { icon: "🔍", iconTone: "is-module", title: "window/Recognize/",     description: "OCR recognize panel · Image/Text/Control area triad",                               meta: "<span class=\"accent\">Window</span> · src/window/Recognize/" },
            { icon: "📸", iconTone: "is-module", title: "window/Screenshot/",    description: "Screenshot capture overlay · region selection + OCR trigger",                        meta: "<span class=\"accent\">Window</span> · src/window/Screenshot/" },
            { icon: "⚙️", iconTone: "is-module", title: "window/Config/",        description: "Settings panel · Service config, hotkeys, backup, history, about",                  meta: "<span class=\"accent\">Window</span> · src/window/Config/" },
            { icon: "🔄", iconTone: "is-module", title: "window/Updater/",       description: "Version update panel · download & install",                                         meta: "<span class=\"accent\">Window</span> · src/window/Updater/" },
          ]
        },
        {
          id:    "src-tauri-modules",
          kind:  "items",
          icon:  "⚙️",
          title: "Rust Backend (src-tauri/src/ · 14 modules)",
          items: [
            { icon: "🚀", iconTone: "is-module", title: "main.rs",             description: "Tauri entry · plugin wiring, setup, invoke handler, system tray",                  meta: "<span class=\"accent\">Rust</span> · src-tauri/src/main.rs" },
            { icon: "⚙️", iconTone: "is-module", title: "config.rs",           description: "Config store · JSON persistence, service availability check",                       meta: "<span class=\"accent\">Rust</span> · src-tauri/src/config.rs" },
            { icon: "🌐", iconTone: "is-module", title: "server.rs",           description: "tiny_http server · external tool bridge (translate/OCR/config endpoints)",           meta: "<span class=\"accent\">Rust</span> · src-tauri/src/server.rs" },
            { icon: "📋", iconTone: "is-module", title: "clipboard.rs",        description: "Clipboard monitor · auto-detect copied text",                                       meta: "<span class=\"accent\">Rust</span> · src-tauri/src/clipboard.rs" },
            { icon: "⌨️", iconTone: "is-module", title: "hotkey.rs",           description: "Global shortcut registration · per-window hotkeys",                                  meta: "<span class=\"accent\">Rust</span> · src-tauri/src/hotkey.rs" },
            { icon: "📸", iconTone: "is-module", title: "screenshot.rs",       description: "Screen capture · cross-platform screenshot",                                        meta: "<span class=\"accent\">Rust</span> · src-tauri/src/screenshot.rs" },
            { icon: "👁", iconTone: "is-module", title: "system_ocr.rs",       description: "System-level OCR · macOS Vision / Windows OCR integration",                         meta: "<span class=\"accent\">Rust</span> · src-tauri/src/system_ocr.rs" },
            { icon: "🔤", iconTone: "is-module", title: "lang_detect.rs",      description: "Language detection via lingua crate · 21 languages",                                 meta: "<span class=\"accent\">Rust</span> · src-tauri/src/lang_detect.rs" },
            { icon: "📂", iconTone: "is-module", title: "backup.rs",           description: "Config backup/restore · zip archive handling",                                      meta: "<span class=\"accent\">Rust</span> · src-tauri/src/backup.rs" },
            { icon: "🔄", iconTone: "is-module", title: "updater.rs",          description: "Version update polling · download + verify",                                        meta: "<span class=\"accent\">Rust</span> · src-tauri/src/updater.rs" },
          ]
        },
        {
          id:    "src-utils",
          kind:  "items",
          icon:  "🧰",
          title: "Frontend Utilities & Core (src/)",
          items: [
            { icon: "📄", iconTone: "is-module", title: "App.jsx",             description: "Root component · window routing via windowMap + Tauri label",                       meta: "<span class=\"accent\">Entry</span> · src/App.jsx" },
            { icon: "🔌", iconTone: "is-module", title: "main.jsx",            description: "Application bootstrap · NextUI/Theme provider + store init",                        meta: "<span class=\"accent\">Entry</span> · src/main.jsx" },
            { icon: "💾", iconTone: "is-module", title: "utils/store.js",      description: "Tauri Store wrapper · config.json persistence + fs-watch",                          meta: "<span class=\"accent\">Util</span> · src/utils/store.js" },
            { icon: "🎣", iconTone: "is-module", title: "hooks/",              description: "React hooks · useConfig, useGetState, useSyncAtom, useVoice, useTtsPluginInfo…",     meta: "<span class=\"accent\">Hook</span> · src/hooks/" },
            { icon: "🌍", iconTone: "is-module", title: "i18n/",              description: "Internationalization · en_US + es_ES locale bundles",                               meta: "<span class=\"accent\">I18n</span> · src/i18n/" },
            { icon: "🧩", iconTone: "is-module", title: "components/",         description: "Shared UI components · WindowControl (traffic-light buttons)",                      meta: "<span class=\"accent\">Component</span> · src/components/" },
          ]
        }
      ]
    }
  ],

  footerLinks: [
    { label: "CLAUDE.md",  href: "../CLAUDE.md",  targetBlank: true },
    { label: "README.md",  href: "../README.md",  targetBlank: true }
  ]
};
