/**
 * YiPot · Dashboard data model
 * --------------------------------------------------------------------------
 * Generated by yry-init pipeline (step ③) for the YiPot Tauri desktop
 * translation tool. The data model mirrors the HELP_CONFIG shape consumed
 * by the yry-init standalone dashboard template.
 *
 * Source root: /Users/ruiyi/Downloads/YrY/YiPot/
 * Catalog entry: /Users/ruiyi/Downloads/YrY/YiDoc/projects/YiPot/
 */
window.HELP_CONFIG = {
  titleIcon:     "★",
  title:         "YiPot · Tauri Desktop Translation Tool",
  tagline:       "Cross-platform desktop translator & OCR — 21 translation engines · 16 recognize backends · TTS & collection services · Tauri 1.8 + React 18 fullstack architecture",
  backTopLabel:  "返回顶部",
  footerNote:    "由 yry-init 流水线生成 (detect → explore → generate → arch → verify) · 项目根: /Users/ruiyi/Downloads/YrY/YiPot/",

  breadcrumb: [
    { label: "YiDoc", href: "../../index.html" },
    { label: "Projects", href: "../../dashboard/index.html" },
    { label: "YiPot" }
  ],

  // High-level KPIs
  stats: [
    { value: "21",  label: "Translate Services", modifier: "cyan",   sub: "translation engines" },
    { value: "16",  label: "Recognize Services", modifier: "cyan",   sub: "OCR backends" },
    { value: "5",   label: "Window Panels",      modifier: "accent", sub: "Tauri windows" },
    { value: "187+", label: "JS Source Files",   modifier: "accent", sub: "frontend (src/)" },
    { value: "14",  label: "Rust Modules",       modifier: "info",   sub: "backend (src-tauri/)" }
  ],

  panelHub: {
    label: { text: '📊', panel: 'reports', title: 'YiPot 文档导航' },
    targetBlank: false,
    buttons: [
      { icon: '🏛', name: 'Architecture', desc: '6 个架构场景',  color: 'var(--yry-accent)', panel: 'arch' },
      { icon: '✅', name: 'Self-Check',    desc: '6 个自检场景',  color: 'var(--yry-cyan)',   panel: 'test' },
      { icon: '📁', name: 'Files',         desc: '文件体检',        color: 'var(--yry-info)',   panel: 'files' },
      { icon: '🔌', name: 'APIs',          desc: 'API 审计',        color: 'var(--yry-warn)',   panel: 'apis' }
    ],
    flow: '架构分析 → 自检策略 → 文件体检 → API 审计',
    urls: {
      arch:  '../../templates/arch/index.html?project=YiPot',
      test:  '../../templates/test/index.html?project=YiPot',
      files: '../../templates/files/index.html?project=YiPot',
      apis:  '../../templates/apis/index.html?project=YiPot',
      daily: '../../templates/daily/cto-report.html?project=YiPot',
    }
  },

  reportsList: {
    daily:   [],
    weekly:  [],
    monthly: []
  },

  // ── § 1 · Third-party dependencies & frameworks ────────────────────
  sections: [
    {
      id:    "section-dependencies",
      badge: "1",
      title: "Third-Party Dependencies / Frameworks",
      meta:  "33 npm runtime · 9 npm dev · 14 Rust crates",
      groups: [
        {
          id:    "deps-runtime",
          kind:  "items",
          icon:  "📦",
          title: "Runtime Dependencies (npm)",
          items: [
            {
              icon:        "R",
              iconTone:    "is-module",
              title:       "React 18",
              description: "UI library · hooks · concurrent rendering · powers every window panel",
              meta:        "<span class=\"accent\">Runtime</span> · ^18.3.1"
            },
            {
              icon:        "T",
              iconTone:    "is-module",
              title:       "@tauri-apps/api 1.6",
              description: "Tauri 1.8 IPC bridge · invoke / event / appWindow · the JS↔Rust boundary",
              meta:        "<span class=\"accent\">Runtime</span> · ^1.6.0"
            },
            {
              icon:        "N",
              iconTone:    "is-module",
              title:       "@nextui-org/react 2.4",
              description: "Component library · Config + Translate + Recognize UI widgets",
              meta:        "<span class=\"accent\">Runtime</span> · ^2.4.8"
            },
            {
              icon:        "V",
              iconTone:    "is-module",
              title:       "Vite 5",
              description: "Dev server + production bundler · @vitejs/plugin-react · HMR",
              meta:        "<span class=\"accent\">Dev</span> · ^5.4.10"
            },
            {
              icon:        "J",
              iconTone:    "is-module",
              title:       "Jotai 2.10",
              description: "Atomic state · per-window UI state atoms",
              meta:        "<span class=\"accent\">Runtime</span> · ^2.10.1"
            },
            {
              icon:        "I",
              iconTone:    "is-module",
              title:       "i18next 23 + react-i18next 15",
              description: "Internationalization · en_US + es_ES locales",
              meta:        "<span class=\"accent\">Runtime</span> · ^23.16.4"
            },
            {
              icon:        "O",
              iconTone:    "is-module",
              title:       "ollama 0.5",
              description: "Ollama SDK · local LLM as a translate engine",
              meta:        "<span class=\"accent\">Runtime</span> · ^0.5.9"
            },
            {
              icon:        "T",
              iconTone:    "is-module",
              title:       "tesseract.js 5.1",
              description: "In-browser OCR fallback when Rust-side system_ocr returns nothing",
              meta:        "<span class=\"accent\">Runtime</span> · ^5.1.1"
            },
            {
              icon:        "J",
              iconTone:    "is-module",
              title:       "jose 5.9",
              description: "JWT / JWS / JWE toolkit for engine auth flows",
              meta:        "<span class=\"accent\">Runtime</span> · ^5.9.6"
            },
            {
              icon:        "C",
              iconTone:    "is-module",
              title:       "crypto-js 4.2",
              description: "Hashing / HMAC for engine request signing",
              meta:        "<span class=\"accent\">Runtime</span> · ^4.2.0"
            },
            {
              icon:        "F",
              iconTone:    "is-module",
              title:       "flag-icons 7.2",
              description: "Locale flag CSS for engine picker",
              meta:        "<span class=\"accent\">Runtime</span> · ^7.2.3"
            },
            {
              icon:        "R",
              iconTone:    "is-module",
              title:       "react-router-dom 6.27",
              description: "In-window sub-routing for Config tabs",
              meta:        "<span class=\"accent\">Runtime</span> · ^6.27.0"
            },
            {
              icon:        "M",
              iconTone:    "is-module",
              title:       "react-markdown 9 + framer-motion 11",
              description: "Markdown render for engine output · animation primitives",
              meta:        "<span class=\"accent\">Runtime</span> · ^9.0.1 / ^11.11.10"
            },
            {
              icon:        "P",
              iconTone:    "is-module",
              title:       "6× tauri-plugin-*-api (v1 GitHub pins)",
              description: "store · sql · fs-watch · log · autostart — all pinned to Tauri v1 revisions",
              meta:        "<span class=\"accent\">Runtime</span> · github:tauri-apps/...#v1"
            },
            {
              icon:        "U",
              iconTone:    "is-module",
              title:       "uuid 11 · nanoid 5 · md5 2 · jsqr 1.4",
              description: "ID + QR + hashing utilities for engine flows",
              meta:        "<span class=\"accent\">Runtime</span> · ^11.0.2 / ^5.0.8 / ^2.3.0 / ^1.4.0"
            }
          ]
        },
        {
          id:    "deps-dev",
          kind:  "items",
          icon:  "🔧",
          title: "Dev Dependencies (npm)",
          items: [
            {
              icon:        "V",
              iconTone:    "is-module",
              title:       "Vite 5 + @vitejs/plugin-react 4.3",
              description: "Bundler + React fast-refresh transform",
              meta:        "<span class=\"accent\">Dev</span> · ^5.4.10"
            },
            {
              icon:        "T",
              iconTone:    "is-module",
              title:       "Tailwind CSS 3.4 + postcss 8.4 + autoprefixer 10.4",
              description: "Utility CSS pipeline · NextUI preset on top",
              meta:        "<span class=\"accent\">Dev</span> · ^3.4.14"
            },
            {
              icon:        "P",
              iconTone:    "is-module",
              title:       "Prettier 3.3",
              description: "Code formatter · no ESLint config present",
              meta:        "<span class=\"accent\">Dev</span> · 3.3.2"
            },
            {
              icon:        "T",
              iconTone:    "is-module",
              title:       "TypeScript 5.6",
              description: "Type-checking only (no tsc emit; Vite handles bundling)",
              meta:        "<span class=\"accent\">Dev</span> · ^5.6.3"
            },
            {
              icon:        "T",
              iconTone:    "is-module",
              title:       "@tauri-apps/cli 1.6",
              description: "Tauri desktop CLI · `tauri dev` / `tauri build`",
              meta:        "<span class=\"accent\">Dev</span> · ^1.6.3"
            },
            {
              icon:        "N",
              iconTone:    "is-module",
              title:       "node-fetch 3.3",
              description: "Fetch polyfill used by updater/*.mjs scripts",
              meta:        "<span class=\"accent\">Dev</span> · ^3.3.2"
            }
          ]
        },
        {
          id:    "deps-rust",
          kind:  "items",
          icon:  "🦀",
          title: "Rust Crates (src-tauri/Cargo.toml)",
          items: [
            {
              icon:        "T",
              iconTone:    "is-module",
              title:       "tauri 1.8",
              description: "Desktop shell · windows · tray · IPC · single-instance",
              meta:        "<span class=\"accent\">Cargo</span> · 1.x"
            },
            {
              icon:        "H",
              iconTone:    "is-module",
              title:       "tiny_http",
              description: "HTTP bridge on :60828 — ferries OS clipboard/screenshot into JS service layer",
              meta:        "<span class=\"accent\">Cargo</span> · 0.x"
            },
            {
              icon:        "L",
              iconTone:    "is-module",
              title:       "lingua",
              description: "Source-text language detection (Rust side, paired with i18next on the JS side)",
              meta:        "<span class=\"accent\">Cargo</span> · 0.x"
            },
            {
              icon:        "S",
              iconTone:    "is-module",
              title:       "screenshots",
              description: "Cross-platform screen capture (Screenshot window)",
              meta:        "<span class=\"accent\">Cargo</span> · 0.x"
            },
            {
              icon:        "C",
              iconTone:    "is-module",
              title:       "arboard / clipboard",
              description: "OS clipboard read/write (clipboard.rs)",
              meta:        "<span class=\"accent\">Cargo</span> · 0.x"
            },
            {
              icon:        "S",
              iconTone:    "is-module",
              title:       "serde / serde_json",
              description: "Serialization for IPC + config.json + tiny_http payloads",
              meta:        "<span class=\"accent\">Cargo</span> · 1.x"
            },
            {
              icon:        "T",
              iconTone:    "is-module",
              title:       "tokio + reqwest",
              description: "Async runtime + HTTP client for Rust-side engine calls",
              meta:        "<span class=\"accent\">Cargo</span> · 1.x / 0.x"
            }
          ]
        }
      ]
    },

    // ── § 2 · Story documents & scenes ────────────────────────────────
    {
      id:    "section-stories",
      badge: "2",
      title: "Story Documents & Scenes",
      meta:  "6 arch scenes · 6 self-check scenes",
      groups: [
        {
          id:    "stories-arch",
          kind:  "stories",
          icon:  "🏛",
          title: "Architecture Stories (arch/)",
          items: [
            {
              badge: "scene-1",
              title: "Module Location",
              description: "Locate any module — engine, window, hook, or Rust backend module — in the YiPot source tree.",
              meta:    "<span class=\"accent\">arch</span> · 5 verification steps",
              sceneLinks: [
                { label: "scene-1",   href: "../../projects/YiPot/arch/scene-1-module-location/index.md" },
                { label: "scene-2",   href: "../../projects/YiPot/arch/scene-2-data-flow-tracing/index.md" },
                { label: "scene-3",   href: "../../projects/YiPot/arch/scene-3-newcomer-onboarding/index.md" },
                { label: "scene-4",   href: "../../projects/YiPot/arch/scene-4-dependency-change-impact/index.md" },
                { label: "scene-5",   href: "../../projects/YiPot/arch/scene-5-trust-boundary-security-surface/index.md" },
                { label: "scene-6",   href: "../../projects/YiPot/arch/scene-6-ipc-window-lifecycle/index.md" }
              ]
            },
            {
              badge: "scene-2",
              title: "Data Flow Tracing",
              description: "Trace a translate request from clipboard → tiny_http bridge → JS engine → remote API → rendered result.",
              meta:    "<span class=\"accent\">arch</span> · §0–§4 lifecycle",
              sceneLinks: [
                { label: "scene-2",   href: "../../projects/YiPot/arch/scene-2-data-flow-tracing/index.md" }
              ]
            },
            {
              badge: "scene-3",
              title: "Newcomer Onboarding",
              description: "I'm new here; what should I read first? — a guided tour through the YiPot codebase.",
              meta:    "<span class=\"accent\">arch</span> · §0–§4 lifecycle",
              sceneLinks: [
                { label: "scene-3",   href: "../../projects/YiPot/arch/scene-3-newcomer-onboarding/index.md" }
              ]
            },
            {
              badge: "scene-4",
              title: "Dependency Change Impact",
              description: "What breaks if I upgrade Tauri / React / NextUI / a Rust crate? — blast-radius analysis.",
              meta:    "<span class=\"accent\">arch</span> · §0–§4 lifecycle",
              sceneLinks: [
                { label: "scene-4",   href: "../../projects/YiPot/arch/scene-4-dependency-change-impact/index.md" }
              ]
            },
            {
              badge: "scene-5",
              title: "Trust Boundary & Security Surface",
              description: "Where are the trust boundaries between Rust OS layer, tiny_http bridge, and JS service layer — and what is exposed at each?",
              meta:    "<span class=\"accent\">arch</span> · §0–§4 lifecycle",
              sceneLinks: [
                { label: "scene-5",   href: "../../projects/YiPot/arch/scene-5-trust-boundary-security-surface/index.md" }
              ]
            },
            {
              badge: "scene-6",
              title: "IPC & Window Lifecycle",
              description: "Tauri IPC channels, window spawn/teardown, and how appWindow.label dispatches React subtrees.",
              meta:    "<span class=\"accent\">arch</span> · §0–§4 lifecycle",
              sceneLinks: [
                { label: "scene-6",   href: "../../projects/YiPot/arch/scene-6-ipc-window-lifecycle/index.md" }
              ]
            }
          ]
        },
        {
          id:    "stories-test",
          kind:  "stories",
          icon:  "✅",
          title: "Self-Check Stories (test/)",
          items: [
            {
              badge: "scene-1",
              title: "Post-Init Full Self-Check",
              description: "Does the project pass a full self-check after a fresh yry-init run?",
              meta:    "<span class=\"accent\">test</span> · §0–§4 lifecycle",
              sceneLinks: [
                { label: "scene-1",   href: "../../projects/YiPot/test/scene-1-post-init-full-self-check/index.md" },
                { label: "scene-2",   href: "../../projects/YiPot/test/scene-2-pre-commit-incremental-self-check/index.md" },
                { label: "scene-3", href: "../../projects/YiPot/test/scene-3-doc-code-consistency/index.md" },
                { label: "scene-4", href: "../../projects/YiPot/test/scene-4-security-surface-regression/index.md" },
                { label: "scene-5",   href: "../../projects/YiPot/test/scene-5-cross-story-integration-regression/index.md" },
                { label: "scene-6",   href: "../../projects/YiPot/test/scene-6-third-party-framework-service/index.md" }
              ]
            },
            {
              badge: "scene-2",
              title: "Pre-Commit Incremental Self-Check",
              description: "What is the minimum check before committing a change to YiPot?",
              meta:    "<span class=\"accent\">test</span> · §0–§4 lifecycle",
              sceneLinks: [{ label: "scene-2", href: "../../projects/YiPot/test/scene-2-pre-commit-incremental-self-check/index.md" }]
            },
            {
              badge: "scene-3",
              title: "Doc-Code Consistency",
              description: "Do the docs (CLAUDE.md / README.md / data.js / scenes) still match the source code?",
              meta:    "<span class=\"accent\">test</span> · §0–§4 lifecycle",
              sceneLinks: [{ label: "scene-3", href: "../../projects/YiPot/test/scene-3-doc-code-consistency/index.md" }]
            },
            {
              badge: "scene-4",
              title: "Security Surface Regression",
              description: "Has the security surface changed since the last baseline?",
              meta:    "<span class=\"accent\">test</span> · §0–§4 lifecycle",
              sceneLinks: [{ label: "scene-4", href: "../../projects/YiPot/test/scene-4-security-surface-regression/index.md" }]
            },
            {
              badge: "scene-5",
              title: "Cross-Story Integration Regression",
              description: "Do the arch + test story directories still pass cross-story integration checks?",
              meta:    "<span class=\"accent\">test</span> · §0–§4 lifecycle",
              sceneLinks: [{ label: "scene-5", href: "../../projects/YiPot/test/scene-5-cross-story-integration-regression/index.md" }]
            },
            {
              badge: "scene-6",
              title: "Third-Party Framework Service",
              description: "Are Tauri, React, NextUI, and the engine SDKs still healthy?",
              meta:    "<span class=\"accent\">test</span> · §0–§4 lifecycle",
              sceneLinks: [{ label: "scene-6", href: "../../projects/YiPot/test/scene-6-third-party-framework-service/index.md" }]
            }
          ]
        }
      ]
    },

    // ── § 3 · Main source code (grouped by top-level directory) ────────
    {
      id:    "section-source",
      badge: "3",
      title: "Main Source Code",
      meta:  "187 JS/JSX files · 14 Rust modules",
      groups: [
        {
          id:    "src-window",
          kind:  "items",
          icon:  "🪟",
          title: "src/window/ — Window Panels",
          items: [
            {
              icon:        "📄",
              iconTone:    "is-file",
              title:       "Translate Window",
              description: "Main translation window · engine picker · source/target textareas · clipboard round-trip",
              meta:        "<span class=\"accent\">Panel</span> · src/window/Translate/"
            },
            {
              icon:        "📄",
              iconTone:    "is-file",
              title:       "Recognize Window",
              description: "OCR window · image drop · recognize engine picker · text output",
              meta:        "<span class=\"accent\">Panel</span> · src/window/Recognize/"
            },
            {
              icon:        "📄",
              iconTone:    "is-file",
              title:       "Screenshot Window",
              description: "Screenshot capture + region OCR · system_ocr.rs → tesseract.js fallback",
              meta:        "<span class=\"accent\">Panel</span> · src/window/Screenshot/"
            },
            {
              icon:        "📄",
              iconTone:    "is-file",
              title:       "Config Window",
              description: "Settings UI · engine API keys · hotkey binding · persists to config.json",
              meta:        "<span class=\"accent\">Panel</span> · src/window/Config/"
            },
            {
              icon:        "📄",
              iconTone:    "is-file",
              title:       "Updater Window",
              description: "Self-update UI · version probe · updater manifest fetch",
              meta:        "<span class=\"accent\">Panel</span> · src/window/Updater/"
            }
          ]
        },
        {
          id:    "src-services",
          kind:  "items",
          icon:  "🔌",
          title: "src/services/ — Engine Registry",
          items: [
            {
              icon:        "📦",
              iconTone:    "is-dir",
              title:       "translate/ — 21 Engines",
              description: "openai · deepl · google · bing · baidu · alibaba · tencent · volcengine · caiyun · niutrans · transmart · youdao · yandex · lingva · cambridge_dict · ecdict · baidu_field · bing_dict · chatglm · geminipro · ollama",
              meta:        "<span class=\"accent\">Registry</span> · src/services/translate/"
            },
            {
              icon:        "📦",
              iconTone:    "is-dir",
              title:       "recognize/ — 16 Engines",
              description: "tesseract · baidu · baidu_accurate · baidu_img · iflytek · iflytek_intsig · iflytek_latex · tencent · tencent_accurate · tencent_img · volcengine · volcengine_multi_lang · simple_latex · qrcode · system",
              meta:        "<span class=\"accent\">Registry</span> · src/services/recognize/"
            },
            {
              icon:        "📦",
              iconTone:    "is-dir",
              title:       "tts/ + collection/",
              description: "Text-to-speech engines + collection services (engine count varies by config)",
              meta:        "<span class=\"accent\">Registry</span> · src/services/{tts,collection}/"
            },
            {
              icon:        "📄",
              iconTone:    "is-file",
              title:       "Engine contract",
              description: "Each engine dir ships Config.jsx + index.jsx + info.ts — do not inline into the barrel",
              meta:        "<span class=\"accent\">Convention</span> · <engine>/{Config.jsx,index.jsx,info.ts}"
            }
          ]
        },
        {
          id:    "src-shared",
          kind:  "items",
          icon:  "🧩",
          title: "src/ — Shared Frontend",
          items: [
            {
              icon:        "📄",
              iconTone:    "is-file",
              title:       "App.jsx",
              description: "Window dispatch by appWindow.label via windowMap — the Tauri-label router",
              meta:        "<span class=\"accent\">Entry</span> · src/App.jsx"
            },
            {
              icon:        "📄",
              iconTone:    "is-file",
              title:       "main.jsx",
              description: "ReactDOM root · NextUI provider · Jotai provider · i18n init",
              meta:        "<span class=\"accent\">Root</span> · src/main.jsx"
            },
            {
              icon:        "📦",
              iconTone:    "is-dir",
              title:       "components/ + hooks/",
              description: "Shared React components + reusable hooks",
              meta:        "<span class=\"accent\">Shared</span> · src/{components,hooks}/"
            },
            {
              icon:        "📦",
              iconTone:    "is-dir",
              title:       "utils/ + i18n/",
              description: "JS helpers (signing, hash, fetch wrappers) + i18next locale bundles (en_US, es_ES)",
              meta:        "<span class=\"accent\">Shared</span> · src/{utils,i18n}/"
            }
          ]
        },
        {
          id:    "src-tauri",
          kind:  "items",
          icon:  "🦀",
          title: "src-tauri/src/ — Rust Backend",
          items: [
            {
              icon:        "📄",
              iconTone:    "is-file",
              title:       "main.rs",
              description: "Tauri entry · mod declarations · plugin registrations",
              meta:        "<span class=\"accent\">Entry</span> · src-tauri/src/main.rs"
            },
            {
              icon:        "📄",
              iconTone:    "is-file",
              title:       "cmd.rs",
              description: "#[tauri::command] handlers — the JS-callable surface",
              meta:        "<span class=\"accent\">IPC</span> · src-tauri/src/cmd.rs"
            },
            {
              icon:        "📄",
              iconTone:    "is-file",
              title:       "server.rs",
              description: "tiny_http bridge on :60828 — ferries OS clipboard/screenshot into JS",
              meta:        "<span class=\"accent\">Bridge</span> · src-tauri/src/server.rs"
            },
            {
              icon:        "📄",
              iconTone:    "is-file",
              title:       "clipboard.rs + screenshot.rs",
              description: "OS clipboard + screen capture — feeds the bridge",
              meta:        "<span class=\"accent\">OS</span> · src-tauri/src/{clipboard,screenshot}.rs"
            },
            {
              icon:        "📄",
              iconTone:    "is-file",
              title:       "system_ocr.rs + lang_detect.rs",
              description: "System OCR + lingua language detection (paired with i18next on JS side)",
              meta:        "<span class=\"accent\">OS</span> · src-tauri/src/{system_ocr,lang_detect}.rs"
            },
            {
              icon:        "📄",
              iconTone:    "is-file",
              title:       "window.rs + tray.rs + hotkey.rs",
              description: "Window lifecycle · system tray · global shortcut",
              meta:        "<span class=\"accent\">Shell</span> · src-tauri/src/{window,tray,hotkey}.rs"
            },
            {
              icon:        "📄",
              iconTone:    "is-file",
              title:       "config.rs + backup.rs + updater.rs + error.rs",
              description: "config.json I/O · config backup · self-update · error enum",
              meta:        "<span class=\"accent\">Shell</span> · src-tauri/src/{config,backup,updater,error}.rs"
            }
          ]
        },
        {
          id:    "src-config",
          kind:  "items",
          icon:  "⚙️",
          title: "Project Config & Build",
          items: [
            {
              icon:        "📄",
              iconTone:    "is-file",
              title:       "package.json + pnpm-lock.yaml",
              description: "33 runtime + 9 dev deps · pnpm · scripts: dev, build, tauri, preview, updater",
              meta:        "<span class=\"accent\">Manifest</span> · package.json"
            },
            {
              icon:        "📄",
              iconTone:    "is-file",
              title:       "vite.config.js + tailwind.config.cjs + postcss.config.js",
              description: "Vite 5 + plugin-react · Tailwind 3 + NextUI preset · postcss pipeline",
              meta:        "<span class=\"accent\">Build</span> · *.config.{js,cjs}"
            },
            {
              icon:        "📄",
              iconTone:    "is-file",
              title:       "src-tauri/tauri.conf.json + per-OS + per-arch",
              description: "Main Tauri config + tauri.{linux,macos,windows}.conf.json + webview.{x64,x86,arm64}.json",
              meta:        "<span class=\"accent\">Tauri</span> · src-tauri/tauri.*.conf.json"
            },
            {
              icon:        "📄",
              iconTone:    "is-file",
              title:       "src-tauri/Cargo.toml + build.rs",
              description: "Rust manifest (tauri 1.8, tiny_http, lingua, screenshots, ...) + build script",
              meta:        "<span class=\"accent\">Cargo</span> · src-tauri/Cargo.toml"
            },
            {
              icon:        "📄",
              iconTone:    "is-file",
              title:       "updater/*.mjs + patches/",
              description: "Updater manifest scripts + pnpm patch files for transitive deps",
              meta:        "<span class=\"accent\">Tooling</span> · updater/ · patches/"
            }
          ]
        }
      ]
    }
  ],

  footerLinks: [
    { label: "CLAUDE.md",  href: "CLAUDE.md" },
    { label: "README.md",  href: "README.md" },
    { label: "Architecture Dashboard →", href: "../../templates/arch/index.html?project=YiPot" },
    { label: "Test Dashboard →", href: "../../templates/test/index.html?project=YiPot" },
    { label: "Files Report", href: "files/index.html" },
    { label: "APIs Report",  href: "apis/index.html" },
    { label: "Story Report →", href: "story/index.html" },
    { label: "YiDoc Catalog", href: "../../index.html", targetBlank: false }
  ]
};
