/**
 * yry-report-apis · YiPet — Static configuration & runtime analysis
 * ----------------------------------------------------------------------
 * window.REPORT_CONFIG provides static labels and options. Runtime data
 * (the analysis result) lives in window.REPORT_DATA. Regeneration
 * rewrites only window.REPORT_DATA — the labels and options are stable.
 *
 * Design principles:
 *   - Every metric framed from the HTTP request lifecycle
 *     (ingress → processing → egress → contract).
 *   - Labels are technical, precise, and self-contained.
 *   - CSS variable references (--yry-*) are preferred over hardcoded values.
 */
window.REPORT_CONFIG = {
    options: {
        topN: 20,
        theme: 'dark',
        generatedAt: '2026-07-24T14:55:00.000Z',
    },
    constants: {
        filterDebounceMs: 200,
        componentReadyTimeoutMs: 5000,
        csvHeader: 'path,method,handler,handlerFile,line,auth,authMechanism,validationDepth,contentTypes,rateLimited,errorHandling,middleware,statusCodes,responseFormat,errorFormat,paginationStyle,safe,idempotent,handlerLines,deprecated,version',
    },
    labels: {
        title: 'yry-report-apis · Yi Ecosystem',
        footerMethodology: 'Methodology: references/methodology.md · schemas: references/schemas.md',
        sectionSummary:    'Summary',
        sectionEndpoints:  'Endpoints',
        sectionSemantics:  'HTTP Semantics',
        sectionPatterns:   'Patterns',
        sectionSecurity:   'Security',
        sectionHealth:     'Health & Contracts',
        sectionRemediation: 'Remediation',
        summaryTotalEndpoints: 'Total Requests',
        summaryTotalHandlers:  'Total Handlers',
        summaryAuthCoverage:   'Auth Coverage',
        summaryValidationCoverage: 'Validation Coverage',
        colPath:          'Path',
        colMethod:        'Method',
        colSafe:          'Safe',
        colIdempotent:    'Idempotent',
        colHandler:       'Handler',
        colHandlerFile:   'Handler File',
        colLine:          'Line',
        colAuthMechanism: 'Auth Mechanism',
        colValidationDepth: 'Validation',
        colContentTypes:  'Content Types',
        colResponseFormat:'Response Format',
        colErrorFormat:   'Error Format',
        colPagination:    'Pagination',
        colMiddleware:    'Middleware',
        colAuth:          'Auth',
        colRateLimited:   'Rate Limited',
        colErrorHandling: 'Error Handling',
        colStatusCodes:   'Status Codes',
        colLines:         'Handler LOC',
        colComplexity:    'Complexity',
        colRestScore:     'REST Score',
        colVersion:       'Version',
        colResource:      'Resource',
        colMethodCount:   'Methods',
        colIssues:        'Issues',
        colCount:         'Count',
        colPct:           '%',
        colCategory:      'Category',
        colEffort:        'Effort',
        colUplift:        'Uplift',
        colMessage:       'Finding',
        emptyEndpoints:  'No API requests detected in scope.',
        emptySemantics:  'No HTTP semantics data collected.',
        emptyMethods:    'No HTTP method data collected.',
        emptyPatterns:   'No route patterns identified.',
        emptySecurity:   'No security issues detected.',
        emptyHealth:     'No health issues detected.',
        emptyRemediation: 'No remediation items — all clear.',
        filterPlaceholder: 'filter by path, method, or handler…',
        exportJson: 'Export JSON',
        exportCsv:  'Export CSV',
        copyPath: 'Copy',
        semanticsScore:       'Semantics Score',
        semanticsSafeCount:   'Safe Requests',
        semanticsUnsafeCount: 'Unsafe Requests',
        semanticsIdempotentCount: 'Idempotent Requests',
        semanticsMisuseCount: 'Method Misuse',
        semanticsMisuseTable:  'Method Misuse Detected',
        securityAuthCoverage:      'Auth Coverage',
        securityAuthMechanisms:    'Auth Mechanisms',
        securityRateLimit:         'Rate Limit Coverage',
        securityCorsConfigured:    'CORS',
        securityHeadersScore:      'Security Headers',
        securityValidationCoverage:'Input Validation',
        securityMissingAuth:       'Requests Missing Auth',
        securityMissingRateLimit:  'Requests Missing Rate Limit',
        securityMissingValidation: 'Requests Missing Validation',
        healthErrorCoverage:       'Error Handling Coverage',
        healthResponseConsistency: 'Response Consistency Score',
        healthHighComplexity:      'High Complexity Handlers',
        healthNegotiationScore:    'Content Negotiation',
        healthErrorFormatScore:    'Error Format (RFC 7807)',
    },
};

/**
 * Runtime analysis data — YiPet browser extension egress requests.
 *
 * Scope: /Users/ruiyi/Downloads/YrY/YiPet/src
 * Framework: custom fetch wrapper (RequestClient + ApiManager).
 * Target backend: http://localhost:10086 (YiAi RPC) + WeWork webhook.
 *
 * Every endpoint is framed by the HTTP request lifecycle:
 *   ingress → processing → egress → contract
 */
window.REPORT_DATA = {
    scope: '/Users/ruiyi/Downloads/YrY/YiPet/src',
    score: 48,

    summary: {
        totalRequests: 33,
        totalHandlers: 11,
        totalMethods: { POST: 27, GET: 6 },
        authCoverage: 0.73,
        validationDepthCoverage: 0.27,
        errorHandlingCoverage: 0.64,
        deprecatedCount: 0,
        criticalCount: 12,
        maxHandlerLines: 0,
        dominantResponseFormat: 'JSON',
        dominantAuthMechanism: 'API Key (X-Token)',
        semanticsScore: 55,
        contractScore: 30,
        methodMisuseCount: 3,
        paginationCoverage: 0.0,
        rfc7807ComplianceScore: 10,
    },

    /* ── Request inventory ─────────────────────────────────────────────── */
    endpoints: [
        /* ── FaqService (src/api/faq.service.js) — ApiManager-based ──────── */
        { path: '/?method_name=query_documents&cname=faqs', method: 'GET',  auth: true, authMechanism: 'API Key (X-Token)', validationDepth: { body: false, params: false, query: true,  headers: false }, contentTypes: ['application/json'], rateLimited: false, handler: 'faq.getFaqs',         handlerFile: 'src/api/faq.service.js',     line: 32,  middleware: ['token', 'logger'], errorHandling: true,  statusCodes: [200, 500],     responseFormat: 'JSON', errorFormat: 'custom', paginationStyle: 'none',   safe: true,  idempotent: true,  handlerLines: 20, deprecated: false, version: null, hasOpenApiSpec: false },
        { path: '/',                                       method: 'POST', auth: true, authMechanism: 'API Key (X-Token)', validationDepth: { body: true,  params: false, query: false, headers: false }, contentTypes: ['application/json'], rateLimited: false, handler: 'faq.createFaq',       handlerFile: 'src/api/faq.service.js',     line: 72,  middleware: ['token', 'logger'], errorHandling: true,  statusCodes: [200, 400, 500], responseFormat: 'JSON', errorFormat: 'custom', paginationStyle: 'none',   safe: false, idempotent: false, handlerLines: 27, deprecated: false, version: null, hasOpenApiSpec: false },
        { path: '/',                                       method: 'POST', auth: true, authMechanism: 'API Key (X-Token)', validationDepth: { body: true,  params: false, query: false, headers: false }, contentTypes: ['application/json'], rateLimited: false, handler: 'faq.updateFaq',       handlerFile: 'src/api/faq.service.js',     line: 106, middleware: ['token', 'logger'], errorHandling: true,  statusCodes: [200, 400, 500], responseFormat: 'JSON', errorFormat: 'custom', paginationStyle: 'none',   safe: false, idempotent: false, handlerLines: 24, deprecated: false, version: null, hasOpenApiSpec: false },
        { path: '/',                                       method: 'POST', auth: true, authMechanism: 'API Key (X-Token)', validationDepth: { body: false, params: false, query: false, headers: false }, contentTypes: ['application/json'], rateLimited: false, handler: 'faq.deleteFaq',       handlerFile: 'src/api/faq.service.js',     line: 133, middleware: ['token', 'logger'], errorHandling: true,  statusCodes: [200, 400, 500], responseFormat: 'JSON', errorFormat: 'custom', paginationStyle: 'none',   safe: false, idempotent: false, handlerLines: 21, deprecated: false, version: null, hasOpenApiSpec: false },
        { path: '/?method_name=insert_documents',          method: 'POST', auth: true, authMechanism: 'API Key (X-Token)', validationDepth: { body: true,  params: false, query: false, headers: false }, contentTypes: ['application/json'], rateLimited: false, handler: 'faq.saveFaqs',        handlerFile: 'src/api/faq.service.js',     line: 157, middleware: ['token', 'logger'], errorHandling: true,  statusCodes: [200, 400, 500], responseFormat: 'JSON', errorFormat: 'custom', paginationStyle: 'none',   safe: false, idempotent: false, handlerLines: 18, deprecated: false, version: null, hasOpenApiSpec: false },
        { path: '/?method_name=update_documents',          method: 'POST', auth: true, authMechanism: 'API Key (X-Token)', validationDepth: { body: true,  params: false, query: false, headers: false }, contentTypes: ['application/json'], rateLimited: false, handler: 'faq.batchUpdateOrder',handlerFile: 'src/api/faq.service.js',     line: 184, middleware: ['token', 'logger'], errorHandling: true,  statusCodes: [200, 500],     responseFormat: 'JSON', errorFormat: 'custom', paginationStyle: 'none',   safe: false, idempotent: false, handlerLines: 24, deprecated: false, version: null, hasOpenApiSpec: false },
        { path: '/?method_name=query_documents&tags',      method: 'GET',  auth: true, authMechanism: 'API Key (X-Token)', validationDepth: { body: false, params: false, query: true,  headers: false }, contentTypes: ['application/json'], rateLimited: false, handler: 'faq.getFaqsByTags',   handlerFile: 'src/api/faq.service.js',     line: 215, middleware: ['token', 'logger'], errorHandling: true,  statusCodes: [200, 500],     responseFormat: 'JSON', errorFormat: 'custom', paginationStyle: 'none',   safe: true,  idempotent: true,  handlerLines: 19, deprecated: false, version: null, hasOpenApiSpec: false },
        { path: '/?method_name=query_documents&search',    method: 'GET',  auth: true, authMechanism: 'API Key (X-Token)', validationDepth: { body: false, params: false, query: true,  headers: false }, contentTypes: ['application/json'], rateLimited: false, handler: 'faq.searchFaqs',      handlerFile: 'src/api/faq.service.js',     line: 246, middleware: ['token', 'logger'], errorHandling: true,  statusCodes: [200, 500],     responseFormat: 'JSON', errorFormat: 'custom', paginationStyle: 'none',   safe: true,  idempotent: true,  handlerLines: 20, deprecated: false, version: null, hasOpenApiSpec: false },

        /* ── SessionService (src/api/session.service.js) — ApiManager-based ── */
        { path: '/?method_name=query_documents&cname=sessions',    method: 'GET',  auth: true, authMechanism: 'API Key (X-Token)', validationDepth: { body: false, params: false, query: true,  headers: false }, contentTypes: ['application/json'], rateLimited: false, handler: 'session.getSessionsList', handlerFile: 'src/api/session.service.js', line: 44,  middleware: ['token', 'logger'], errorHandling: true,  statusCodes: [200, 500],     responseFormat: 'JSON', errorFormat: 'custom', paginationStyle: 'none',   safe: true,  idempotent: true,  handlerLines: 16, deprecated: false, version: null, hasOpenApiSpec: false },
        { path: '/?method_name=query_documents&key',               method: 'GET',  auth: true, authMechanism: 'API Key (X-Token)', validationDepth: { body: false, params: false, query: true,  headers: false }, contentTypes: ['application/json'], rateLimited: false, handler: 'session.getSession',      handlerFile: 'src/api/session.service.js', line: 69,  middleware: ['token', 'logger'], errorHandling: true,  statusCodes: [200, 400, 500], responseFormat: 'JSON', errorFormat: 'custom', paginationStyle: 'none',   safe: true,  idempotent: true,  handlerLines: 20, deprecated: false, version: null, hasOpenApiSpec: false },
        { path: '/',                                               method: 'POST', auth: true, authMechanism: 'API Key (X-Token)', validationDepth: { body: true,  params: false, query: false, headers: false }, contentTypes: ['application/json'], rateLimited: false, handler: 'session.createSession',   handlerFile: 'src/api/session.service.js', line: 99,  middleware: ['token', 'logger'], errorHandling: false, statusCodes: [200, 400, 500], responseFormat: 'JSON', errorFormat: 'custom', paginationStyle: 'none',   safe: false, idempotent: false, handlerLines: 22, deprecated: false, version: null, hasOpenApiSpec: false },
        { path: '/',                                               method: 'POST', auth: true, authMechanism: 'API Key (X-Token)', validationDepth: { body: true,  params: false, query: false, headers: false }, contentTypes: ['application/json'], rateLimited: false, handler: 'session.saveSession',     handlerFile: 'src/api/session.service.js', line: 135, middleware: ['token', 'logger'], errorHandling: true,  statusCodes: [200, 400, 500], responseFormat: 'JSON', errorFormat: 'custom', paginationStyle: 'none',   safe: false, idempotent: false, handlerLines: 37, deprecated: false, version: null, hasOpenApiSpec: false },
        { path: '/',                                               method: 'POST', auth: true, authMechanism: 'API Key (X-Token)', validationDepth: { body: false, params: false, query: false, headers: false }, contentTypes: ['application/json'], rateLimited: false, handler: 'session.deleteSession',   handlerFile: 'src/api/session.service.js', line: 258, middleware: ['token', 'logger'], errorHandling: true,  statusCodes: [200, 400, 500], responseFormat: 'JSON', errorFormat: 'custom', paginationStyle: 'none',   safe: false, idempotent: false, handlerLines: 20, deprecated: false, version: null, hasOpenApiSpec: false },
        { path: '/?method_name=query_documents&search=sessions',   method: 'GET',  auth: true, authMechanism: 'API Key (X-Token)', validationDepth: { body: false, params: false, query: true,  headers: false }, contentTypes: ['application/json'], rateLimited: false, handler: 'session.searchSessions',  handlerFile: 'src/api/session.service.js', line: 312, middleware: ['token', 'logger'], errorHandling: true,  statusCodes: [200, 500],     responseFormat: 'JSON', errorFormat: 'custom', paginationStyle: 'none',   safe: true,  idempotent: true,  handlerLines: 23, deprecated: false, version: null, hasOpenApiSpec: false },

        /* ── AI chat / prompt RPC calls (src/content/ai/) ───────────────── */
        { path: '/',              method: 'POST', auth: true, authMechanism: 'API Key (X-Token)', validationDepth: { body: true,  params: false, query: false, headers: true }, contentTypes: ['application/json'], rateLimited: false, handler: 'aiApi.sendPrompt',        handlerFile: 'src/content/ai/ai-api.js',     line: 353, middleware: ['token'], errorHandling: true,  statusCodes: [200, 400, 500], responseFormat: 'JSON', errorFormat: 'custom', paginationStyle: 'none', safe: false, idempotent: false, handlerLines: 45, deprecated: false, version: null, hasOpenApiSpec: false },
        { path: '/',              method: 'POST', auth: true, authMechanism: 'API Key (X-Token)', validationDepth: { body: true,  params: false, query: false, headers: true }, contentTypes: ['application/json'], rateLimited: false, handler: 'aiApi.streamChat',        handlerFile: 'src/content/ai/ai-api.js',     line: 524, middleware: ['token'], errorHandling: true,  statusCodes: [200, 400, 500], responseFormat: 'JSON', errorFormat: 'custom', paginationStyle: 'none', safe: false, idempotent: false, handlerLines: 60, deprecated: false, version: null, hasOpenApiSpec: false },
        { path: '/',              method: 'POST', auth: true, authMechanism: 'API Key (X-Token)', validationDepth: { body: true,  params: false, query: false, headers: true }, contentTypes: ['application/json'], rateLimited: false, handler: 'aiApi.completion',        handlerFile: 'src/content/ai/ai-api.js',     line: 615, middleware: ['token'], errorHandling: true,  statusCodes: [200, 400, 500], responseFormat: 'JSON', errorFormat: 'custom', paginationStyle: 'none', safe: false, idempotent: false, handlerLines: 50, deprecated: false, version: null, hasOpenApiSpec: false },
        { path: '/',              method: 'POST', auth: true, authMechanism: 'API Key (X-Token)', validationDepth: { body: true,  params: false, query: false, headers: true }, contentTypes: ['application/json'], rateLimited: false, handler: 'robot.chatService',       handlerFile: 'src/content/ai/robot.js',      line: 399, middleware: ['token'], errorHandling: true,  statusCodes: [200, 400, 500], responseFormat: 'JSON', errorFormat: 'custom', paginationStyle: 'none', safe: false, idempotent: false, handlerLines: 40, deprecated: false, version: null, hasOpenApiSpec: false },
        { path: '/',              method: 'POST', auth: true, authMechanism: 'API Key (X-Token)', validationDepth: { body: true,  params: false, query: false, headers: true }, contentTypes: ['application/json'], rateLimited: false, handler: 'robot.invoke',            handlerFile: 'src/content/ai/robot.js',      line: 472, middleware: ['token'], errorHandling: true,  statusCodes: [200, 400, 500], responseFormat: 'JSON', errorFormat: 'custom', paginationStyle: 'none', safe: false, idempotent: false, handlerLines: 35, deprecated: false, version: null, hasOpenApiSpec: false },
        { path: '/',              method: 'POST', auth: true, authMechanism: 'API Key (X-Token)', validationDepth: { body: true,  params: false, query: false, headers: true }, contentTypes: ['application/json'], rateLimited: false, handler: 'aiPrompt.improve',        handlerFile: 'src/content/ai/ai-prompt.js',  line: 171, middleware: ['token'], errorHandling: true,  statusCodes: [200, 400, 500], responseFormat: 'JSON', errorFormat: 'custom', paginationStyle: 'none', safe: false, idempotent: false, handlerLines: 30, deprecated: false, version: null, hasOpenApiSpec: false },
        { path: '/',              method: 'POST', auth: true, authMechanism: 'API Key (X-Token)', validationDepth: { body: true,  params: false, query: false, headers: true }, contentTypes: ['application/json'], rateLimited: false, handler: 'aiPrompt.generate',       handlerFile: 'src/content/ai/ai-prompt.js',  line: 404, middleware: ['token'], errorHandling: true,  statusCodes: [200, 400, 500], responseFormat: 'JSON', errorFormat: 'custom', paginationStyle: 'none', safe: false, idempotent: false, handlerLines: 30, deprecated: false, version: null, hasOpenApiSpec: false },
        { path: '/',              method: 'POST', auth: true, authMechanism: 'API Key (X-Token)', validationDepth: { body: true,  params: false, query: false, headers: true }, contentTypes: ['application/json'], rateLimited: false, handler: 'aiPrompt.transform',      handlerFile: 'src/content/ai/ai-prompt.js',  line: 599, middleware: ['token'], errorHandling: true,  statusCodes: [200, 400, 500], responseFormat: 'JSON', errorFormat: 'custom', paginationStyle: 'none', safe: false, idempotent: false, handlerLines: 30, deprecated: false, version: null, hasOpenApiSpec: false },
        { path: '/',              method: 'POST', auth: true, authMechanism: 'API Key (X-Token)', validationDepth: { body: true,  params: false, query: false, headers: false }, contentTypes: ['application/json'], rateLimited: false, handler: 'roles.loadRole',            handlerFile: 'src/content/ai/roles.js',        line: 611, middleware: [], errorHandling: true,  statusCodes: [200, 500],       responseFormat: 'JSON', errorFormat: 'custom', paginationStyle: 'none', safe: false, idempotent: false, handlerLines: 35, deprecated: false, version: null, hasOpenApiSpec: false },

        /* ── File operations (src/content/session/) — raw fetch, no auth ── */
        { path: '/rename-file', method: 'POST', auth: false, authMechanism: 'none',          validationDepth: { body: false, params: false, query: false, headers: false }, contentTypes: ['application/json'], rateLimited: false, handler: 'sessionTags.renameFile',  handlerFile: 'src/content/session/session-tags.js',   line: 375, middleware: [], errorHandling: true,  statusCodes: [200, 400, 500], responseFormat: 'JSON', errorFormat: 'custom', paginationStyle: 'none', safe: false, idempotent: false, handlerLines: 25, deprecated: false, version: null, hasOpenApiSpec: false },
        { path: '/',            method: 'POST', auth: false, authMechanism: 'none',          validationDepth: { body: false, params: false, query: false, headers: false }, contentTypes: ['application/json'], rateLimited: false, handler: 'sessionTags.saveTagMeta', handlerFile: 'src/content/session/session-tags.js',   line: 439, middleware: [], errorHandling: false, statusCodes: [200, 500],       responseFormat: 'JSON', errorFormat: 'none',   paginationStyle: 'none', safe: false, idempotent: false, handlerLines: 20, deprecated: false, version: null, hasOpenApiSpec: false },
        { path: '/rename-file', method: 'POST', auth: false, authMechanism: 'none',          validationDepth: { body: false, params: false, query: false, headers: false }, contentTypes: ['application/json'], rateLimited: false, handler: 'sessionEditor.renameFile',handlerFile: 'src/content/session/session-editor.js', line: 382, middleware: [], errorHandling: true,  statusCodes: [200, 400, 500], responseFormat: 'JSON', errorFormat: 'custom', paginationStyle: 'none', safe: false, idempotent: false, handlerLines: 25, deprecated: false, version: null, hasOpenApiSpec: false },
        { path: '/',            method: 'POST', auth: false, authMechanism: 'none',          validationDepth: { body: false, params: false, query: false, headers: false }, contentTypes: ['application/json'], rateLimited: false, handler: 'sessionEditor.saveMeta',  handlerFile: 'src/content/session/session-editor.js', line: 454, middleware: [], errorHandling: false, statusCodes: [200, 500],       responseFormat: 'JSON', errorFormat: 'none',   paginationStyle: 'none', safe: false, idempotent: false, handlerLines: 20, deprecated: false, version: null, hasOpenApiSpec: false },
        { path: '/',            method: 'POST', auth: true, authMechanism: 'API Key (X-Token)', validationDepth: { body: true,  params: false, query: false, headers: true }, contentTypes: ['application/json'], rateLimited: false, handler: 'sessionEditor.callBackend',handlerFile: 'src/content/session/session-editor.js', line: 542, middleware: ['token'], errorHandling: true,  statusCodes: [200, 400, 500], responseFormat: 'JSON', errorFormat: 'custom', paginationStyle: 'none', safe: false, idempotent: false, handlerLines: 30, deprecated: false, version: null, hasOpenApiSpec: false },
        { path: '/',            method: 'POST', auth: false, authMechanism: 'none',          validationDepth: { body: false, params: false, query: false, headers: false }, contentTypes: ['application/json'], rateLimited: false, handler: 'sessionModule.rpc',       handlerFile: 'src/content/session/session-module.js', line: 206, middleware: [], errorHandling: true,  statusCodes: [200, 500],       responseFormat: 'JSON', errorFormat: 'custom', paginationStyle: 'none', safe: false, idempotent: false, handlerLines: 30, deprecated: false, version: null, hasOpenApiSpec: false },
        { path: '/write-file',  method: 'POST', auth: false, authMechanism: 'none',          validationDepth: { body: false, params: false, query: false, headers: false }, contentTypes: ['application/json'], rateLimited: false, handler: 'sessionModule.writeFile', handlerFile: 'src/content/session/session-module.js', line: 554, middleware: [], errorHandling: true,  statusCodes: [200, 400, 500], responseFormat: 'JSON', errorFormat: 'custom', paginationStyle: 'none', safe: false, idempotent: false, handlerLines: 25, deprecated: false, version: null, hasOpenApiSpec: false },
        { path: '/read-file',   method: 'POST', auth: false, authMechanism: 'none',          validationDepth: { body: false, params: false, query: false, headers: false }, contentTypes: ['application/json'], rateLimited: false, handler: 'sessionModule.readFile',  handlerFile: 'src/content/session/session-module.js', line: 651, middleware: [], errorHandling: true,  statusCodes: [200, 400, 500], responseFormat: 'JSON', errorFormat: 'custom', paginationStyle: 'none', safe: false, idempotent: false, handlerLines: 25, deprecated: false, version: null, hasOpenApiSpec: false },
        { path: '/delete-file', method: 'POST', auth: false, authMechanism: 'none',          validationDepth: { body: false, params: false, query: false, headers: false }, contentTypes: ['application/json'], rateLimited: false, handler: 'sessionModule.deleteFile',handlerFile: 'src/content/session/session-module.js', line: 739, middleware: [], errorHandling: true,  statusCodes: [200, 400, 500], responseFormat: 'JSON', errorFormat: 'custom', paginationStyle: 'none', safe: false, idempotent: false, handlerLines: 25, deprecated: false, version: null, hasOpenApiSpec: false },

        /* ── External integration: WeWork webhook ───────────────────────── */
        { path: '/webedhook/msg/send', method: 'POST', auth: false, authMechanism: 'none', validationDepth: { body: true,  params: false, query: false, headers: false }, contentTypes: ['application/json'], rateLimited: false, handler: 'wework.sendMessage',   handlerFile: 'src/background/integrations/wework/wework.service.js', line: 41, middleware: [], errorHandling: true,  statusCodes: [200, 400, 500], responseFormat: 'JSON', errorFormat: 'custom', paginationStyle: 'none', safe: false, idempotent: false, handlerLines: 25, deprecated: false, version: null, hasOpenApiSpec: false },
    ],

    /* ── HTTP Semantics ───────────────────────────────────────────────── */
    semantics: {
        score: 55,
        safeCount: 6,
        unsafeCount: 27,
        idempotentCount: 6,
        nonIdempotentCount: 27,
        methodMisuse: [
            { path: '/read-file',   method: 'POST', handlerFile: 'src/content/session/session-module.js', line: 651, issue: 'POST /read-file — retrieval uses POST instead of GET (verb in path + wrong method)', severity: 'P1' },
            { path: '/rename-file', method: 'POST', handlerFile: 'src/content/session/session-tags.js',   line: 375, issue: 'POST /rename-file — verb in path; RPC-style, non-RESTful', severity: 'P2' },
            { path: '/write-file',  method: 'POST', handlerFile: 'src/content/session/session-module.js', line: 554, issue: 'POST /write-file — verb in path; should be PUT /files/:id per REST', severity: 'P2' },
        ],
        methodCorrectness: [
            { method: 'GET',  total: 6,  correct: 6,  misuse: 0 },
            { method: 'POST', total: 27, correct: 24, misuse: 3 },
        ],
    },

    /* ── Method distribution ─────────────────────────────────────────── */
    methods: [
        { method: 'POST', count: 27, pct: 81.8, safe: false, idempotent: false },
        { method: 'GET',  count: 6,  pct: 18.2, safe: true,  idempotent: true },
    ],

    /* ── Patterns ─────────────────────────────────────────────────────── */
    patterns: [
        { pattern: '/?method_name=query_documents', version: null, resource: 'database',   restScore: 20, issues: ['Verb-in-path (RPC style)', 'No version prefix', 'Query-string method dispatch'], methodCount: 6 },
        { pattern: '/?method_name=create_document', version: null, resource: 'database',   restScore: 20, issues: ['Verb-in-path (RPC style)', 'No version prefix'], methodCount: 3 },
        { pattern: '/?method_name=update_document', version: null, resource: 'database',   restScore: 20, issues: ['Verb-in-path (RPC style)', 'No version prefix'], methodCount: 3 },
        { pattern: '/?method_name=delete_document', version: null, resource: 'database',   restScore: 20, issues: ['Verb-in-path (RPC style)', 'No version prefix'], methodCount: 2 },
        { pattern: '/?method_name=insert_documents',version: null, resource: 'database',   restScore: 20, issues: ['Verb-in-path', 'No version prefix'], methodCount: 1 },
        { pattern: '/?method_name=update_documents',version: null, resource: 'database',   restScore: 20, issues: ['Verb-in-path', 'No version prefix'], methodCount: 1 },
        { pattern: '/ (AI RPC yiaiBaseUrl)',         version: null, resource: 'ai',         restScore: 25, issues: ['Single root endpoint', 'No version prefix', 'Body-based method dispatch'], methodCount: 9 },
        { pattern: '/rename-file',                   version: null, resource: 'files',      restScore: 15, issues: ['Verb in path', 'No version prefix', 'Non-RESTful'], methodCount: 2 },
        { pattern: '/write-file',                    version: null, resource: 'files',      restScore: 15, issues: ['Verb in path', 'No version prefix'], methodCount: 1 },
        { pattern: '/read-file',                     version: null, resource: 'files',      restScore: 15, issues: ['Verb in path', 'No version prefix', 'POST for retrieval'], methodCount: 1 },
        { pattern: '/delete-file',                   version: null, resource: 'files',      restScore: 15, issues: ['Verb in path', 'No version prefix'], methodCount: 1 },
        { pattern: '/webedhook/msg/send',            version: null, resource: 'webhook',    restScore: 30, issues: ['No version prefix', 'External endpoint'], methodCount: 1 },
    ],

    /* ── Security ─────────────────────────────────────────────────────── */
    security: {
        authCoverage: 0.73,
        authMechanisms: { 'API Key (X-Token)': 24, none: 9 },
        endpointsMissingAuth: [
            { path: '/rename-file',   method: 'POST', handlerFile: 'src/content/session/session-tags.js',   line: 375, authMechanism: 'none' },
            { path: '/',              method: 'POST', handlerFile: 'src/content/session/session-tags.js',   line: 439, authMechanism: 'none' },
            { path: '/rename-file',   method: 'POST', handlerFile: 'src/content/session/session-editor.js', line: 382, authMechanism: 'none' },
            { path: '/',              method: 'POST', handlerFile: 'src/content/session/session-editor.js', line: 454, authMechanism: 'none' },
            { path: '/',              method: 'POST', handlerFile: 'src/content/session/session-module.js', line: 206, authMechanism: 'none' },
            { path: '/write-file',    method: 'POST', handlerFile: 'src/content/session/session-module.js', line: 554, authMechanism: 'none' },
            { path: '/read-file',     method: 'POST', handlerFile: 'src/content/session/session-module.js', line: 651, authMechanism: 'none' },
            { path: '/delete-file',   method: 'POST', handlerFile: 'src/content/session/session-module.js', line: 739, authMechanism: 'none' },
            { path: '/webedhook/msg/send', method: 'POST', handlerFile: 'src/background/integrations/wework/wework.service.js', line: 41, authMechanism: 'none' },
        ],
        rateLimitCoverage: 0.0,
        endpointsMissingRateLimit: [
            { path: '/',              method: 'POST', handlerFile: 'src/content/ai/ai-api.js',       line: 353 },
            { path: '/',              method: 'POST', handlerFile: 'src/content/ai/robot.js',        line: 399 },
            { path: '/',              method: 'POST', handlerFile: 'src/content/ai/ai-prompt.js',    line: 171 },
            { path: '/write-file',    method: 'POST', handlerFile: 'src/content/session/session-module.js', line: 554 },
            { path: '/delete-file',   method: 'POST', handlerFile: 'src/content/session/session-module.js', line: 739 },
        ],
        securityHeadersScore: 0,
        corsConfigured: false,
        inputValidationCoverage: 0.27,
        endpointsMissingValidation: [
            { path: '/',            method: 'POST', handlerFile: 'src/content/session/session-module.js', line: 206 },
            { path: '/write-file',  method: 'POST', handlerFile: 'src/content/session/session-module.js', line: 554 },
            { path: '/read-file',   method: 'POST', handlerFile: 'src/content/session/session-module.js', line: 651 },
            { path: '/delete-file', method: 'POST', handlerFile: 'src/content/session/session-module.js', line: 739 },
        ],
    },

    /* ── Health & Contracts ───────────────────────────────────────────── */
    health: {
        errorHandlingCoverage: 0.64,
        endpointsWithoutErrorHandling: [
            { path: '/',              method: 'POST', handlerFile: 'src/api/session.service.js',   line: 99 },
            { path: '/',              method: 'POST', handlerFile: 'src/content/session/session-tags.js',   line: 439 },
            { path: '/',              method: 'POST', handlerFile: 'src/content/session/session-editor.js', line: 454 },
            { path: '/',              method: 'POST', handlerFile: 'src/content/session/session-module.js', line: 206 },
            { path: '/',              method: 'POST', handlerFile: 'src/content/ai/ai-prompt.js',           line: 404 },
            { path: '/',              method: 'POST', handlerFile: 'src/content/ai/roles.js',               line: 611 },
            { path: '/webedhook/msg/send', method: 'POST', handlerFile: 'src/background/integrations/wework/wework.service.js', line: 41 },
        ],
        handlerComplexity: [],
        responseConsistencyScore: 80,
        contentNegotiationScore: 25,
        errorFormatScore: 10,
        statusCodeDistribution: { '200': 33, '400': 12, '500': 18 },
        paginationCoverage: 0.0,
        contractScore: 30,
    },

    /* ── Alerts ───────────────────────────────────────────────────────── */
    alerts: [
        {   severity: 'P0', marker: 'P0', category: 'security',
            file: 'src/content/session/session-module.js', line: 554,
            message: 'POST /write-file — mutation request missing auth',
            metric: 'no auth',
            impact: 'Unauthenticated writes to backend file system; risk of file tampering.',
            effort: 'medium', scoreUplift: 10,
            recommendations: ['Add X-Token header via getAuthHeaders() to every file-op fetch.', 'Verify backend rejects unauthenticated mutations.'],
        },
        {   severity: 'P0', marker: 'P0', category: 'security',
            file: 'src/content/session/session-module.js', line: 739,
            message: 'POST /delete-file — mutation request missing auth',
            metric: 'no auth',
            impact: 'Unauthenticated file deletion; destructive data loss risk.',
            effort: 'medium', scoreUplift: 10,
            recommendations: ['Add X-Token header.', 'Enforce backend auth middleware on /delete-file.'],
        },
        {   severity: 'P0', marker: 'P0', category: 'security',
            file: 'src/content/session/session-module.js', line: 651,
            message: 'POST /read-file — retrieval request missing auth',
            metric: 'no auth',
            impact: 'Unauthenticated file read; risk of data exfiltration.',
            effort: 'low', scoreUplift: 8,
            recommendations: ['Add X-Token header; restrict path resolution server-side.'],
        },
        {   severity: 'P0', marker: 'P0', category: 'validation',
            file: 'src/content/session/session-module.js', line: 554,
            message: 'POST /write-file — mutation request without input validation',
            metric: 'no validation',
            impact: 'Arbitrary target_file / content reaches backend; injection risk.',
            effort: 'medium', scoreUplift: 8,
            recommendations: ['Add zod/joi schema for {target_file, content, is_base64}.', 'Enforce path allowlist on server.'],
        },
        {   severity: 'P0', marker: 'P0', category: 'validation',
            file: 'src/content/session/session-module.js', line: 739,
            message: 'POST /delete-file — mutation request without input validation',
            metric: 'no validation',
            impact: 'Unvalidated file path may enable directory traversal.',
            effort: 'low', scoreUplift: 7,
            recommendations: ['Add schema validation for target file path.', 'Server-side path sanitization.'],
        },
        {   severity: 'P0', marker: 'P0', category: 'validation',
            file: 'src/content/session/session-editor.js', line: 382,
            message: 'POST /rename-file — mutation without auth or validation',
            metric: 'no auth / validation',
            impact: 'File rename via RPC without input checks; arbitrary overwrite risk.',
            effort: 'medium', scoreUplift: 8,
            recommendations: ['Add X-Token header and path validation schema.'],
        },
        {   severity: 'P1', marker: 'P1', category: 'semantics',
            file: 'src/content/session/session-module.js', line: 651,
            message: 'POST /read-file — retrieval uses POST instead of GET',
            metric: 'POST for read',
            impact: 'Violates RFC 7231 — clients/caches treat POST as non-idempotent, cannot cache.',
            effort: 'medium', scoreUplift: 5,
            recommendations: ['Refactor to GET /files/:id with path in URL or query param.'],
        },
        {   severity: 'P1', marker: 'P1', category: 'pattern',
            file: 'src/content/session/session-module.js', line: 554,
            message: 'Verbs in path (/write-file, /read-file, /delete-file, /rename-file) — non-RESTful',
            metric: 'REST score ~15',
            impact: 'RPC-style verbs prevent REST tooling, caching, and documentation generation.',
            effort: 'high', scoreUplift: 7,
            recommendations: ['Refactor to RESTful /api/v1/files/:id with PUT/GET/DELETE.', 'Keep old verbs behind 301 redirects during migration.'],
        },
        {   severity: 'P1', marker: 'P1', category: 'versioning',
            file: 'src/config/pet.config.js', line: 44,
            message: 'All API routes lack /v1/ version prefix',
            metric: 'no version',
            impact: 'Breaking changes affect all consumers without versioning.',
            effort: 'medium', scoreUplift: 6,
            recommendations: ['Add /api/v1/ prefix to the RPC gateway.', 'Version the WeWork webhook integration.'],
        },
        {   severity: 'P1', marker: 'P1', category: 'security',
            file: 'src/content/session/session-module.js', line: 206,
            message: '9 mutation endpoints missing auth — full coverage gap',
            metric: '27% unauthenticated',
            impact: 'Any page in <all_urls> could reach the extension backend and trigger mutations.',
            effort: 'medium', scoreUplift: 8,
            recommendations: ['Centralize auth via a shared fetch wrapper that always attaches X-Token.', 'Reject requests without token at the backend.'],
        },
        {   severity: 'P1', marker: 'P1', category: 'error_handling',
            file: 'src/api/session.service.js', line: 99,
            message: 'createSession — mutation without try/catch on POST',
            metric: 'no error handling',
            impact: 'Network errors propagate unhandled to the caller; stack traces may leak.',
            effort: 'low', scoreUplift: 3,
            recommendations: ['Wrap POST in try/catch; normalize error shape.'],
        },
        {   severity: 'P1', marker: 'P1', category: 'contracts',
            file: 'src/content/ai/ai-prompt.js', line: 171,
            message: 'Error responses not RFC 7807 compliant — custom error format across all AI calls',
            metric: 'error format',
            impact: 'Clients must parse bespoke error shapes; integration fragility.',
            effort: 'medium', scoreUplift: 5,
            recommendations: ['Adopt RFC 7807 Problem Details: {type, title, status, detail}.', 'Standardize across AiManager + all fetch call sites.'],
        },
        {   severity: 'P1', marker: 'P1', category: 'pagination',
            file: 'src/api/session.service.js', line: 44,
            message: 'getSessionsList — unpaginated collection request (limit=10000)',
            metric: 'no pagination',
            impact: 'Response bloat and memory pressure on large session sets.',
            effort: 'medium', scoreUplift: 5,
            recommendations: ['Switch to cursor-based pagination; default limit 100.'],
        },
        {   severity: 'P2', marker: 'P2', category: 'security',
            file: 'src/content/ai/ai-api.js', line: 353,
            message: 'AI RPC endpoints lack rate limiting — DoS risk',
            metric: 'no rate limit',
            impact: 'A misbehaving tab can exhaust backend AI quota.',
            effort: 'medium', scoreUplift: 4,
            recommendations: ['Add client-side throttle (token bucket) in ApiManager interceptor.', 'Backend-side per-token rate limit.'],
        },
        {   severity: 'P2', marker: 'P2', category: 'contracts',
            file: 'src/api/faq.service.js', line: 32,
            message: 'Inconsistent pagination: getSessionsList uses limit param; FAQ collections use no pagination at all',
            metric: 'pagination mix',
            impact: 'Consumers must handle multiple pagination styles.',
            effort: 'low', scoreUplift: 3,
            recommendations: ['Standardize on cursor-based pagination across all collection queries.'],
        },
        {   severity: 'P2', marker: 'P2', category: 'security',
            file: 'src/background/integrations/wework/wework.service.js', line: 41,
            message: 'WeWork webhook endpoint lacks rate limiting and auth hardening',
            metric: 'no rate limit',
            impact: 'Webhook URL leak enables spamming the corp WeWork channel.',
            effort: 'medium', scoreUplift: 3,
            recommendations: ['Persist webhook URL in chrome.storage; rotate periodically.', 'Add client-side dedupe + throttle.'],
        },
        {   severity: 'P2', marker: 'P2', category: 'contracts',
            file: 'src/content/ai/ai-api.js', line: 353,
            message: 'No Content-Type negotiation on AI RPC — all calls assume application/json',
            metric: 'no negotiation',
            impact: 'Future endpoints that return streaming text or binary must be handled ad-hoc.',
            effort: 'low', scoreUplift: 2,
            recommendations: ['Respect Accept header in the response interceptor.', 'Return 415 for unsupported Content-Type on the backend.'],
        },
        {   severity: 'P2', marker: 'P2', category: 'pattern',
            file: 'src/api/faq.service.js', line: 133,
            message: 'Database RPC uses POST for delete operations (POST /?method_name=delete_document)',
            metric: 'POST for delete',
            impact: 'HTTP DELETE semantics would be more discoverable and cache-safe.',
            effort: 'high', scoreUplift: 3,
            recommendations: ['Expose DELETE /api/v1/faqs/:id and /api/v1/sessions/:id over RPC gateway.'],
        },
    ],

    records: [],
};

/* ── Enrichment fallback: category defaults for alert enrichment ──────── */
(function () {
    var byCategory = {
        security: {
            risk: 'Unauthenticated requests expose sensitive data and enable unauthorized mutations.',
            blastRadius: 'request path + user data',
            estimatedHours: 4,
            acceptance: ['All routes in handler have auth middleware.', 'Integration test verifies 401 for unauthenticated requests.'],
            firstStep: 'List all routes in the handler and verify each has auth middleware.',
            tooling: [{ name: 'eslint-plugin-security', hint: 'detect missing auth patterns' }],
            preventiveControls: ['CI: lint rule blocks routes without auth.', 'Code review checklist: verify auth on new routes.'],
            rollbackPlan: 'Revert middleware addition; no API contract change.',
        },
        validation: {
            risk: 'Untrusted input reaches business logic — injection, corruption, crashes.',
            blastRadius: 'request body → downstream services',
            estimatedHours: 3,
            acceptance: ['Input schema added for the request.', 'Invalid input returns 400 with structured error.'],
            firstStep: 'Add input schema for the request using the framework validation library.',
            tooling: [{ name: 'zod', hint: 'TypeScript-first schema validation' }, { name: 'joi', hint: 'declarative request validation' }],
            preventiveControls: ['CI: require validation on all POST/PUT/PATCH requests.', 'OpenAPI schema enforcement.'],
            rollbackPlan: 'Revert validation addition; remove the schema import.',
        },
        error_handling: {
            risk: 'Unhandled errors leak stack traces or crash the process.',
            blastRadius: 'single request → cascading failure',
            estimatedHours: 2,
            acceptance: ['Handler wrapped in try/catch or error middleware added.', 'Error responses are structured JSON.'],
            firstStep: 'Wrap handler body in try/catch or add error middleware.',
            tooling: [{ name: 'express-async-errors', hint: 'auto-catch async errors in Express' }],
            preventiveControls: ['CI: lint rule requires try/catch in route handlers.', 'Shared error middleware as base template.'],
            rollbackPlan: 'Remove error wrapper; original behavior restored.',
        },
        deprecation: {
            risk: 'Callers depend on removed or unsupported APIs.',
            blastRadius: 'all consumers of the request',
            estimatedHours: 8,
            acceptance: ['Deprecation header + sunset date added.', 'Consumers notified via changelog.', 'Migration path documented.'],
            firstStep: 'Add Deprecation header with sunset date; announce in changelog.',
            tooling: [{ name: 'OpenAPI', hint: 'mark requests as deprecated in spec' }],
            preventiveControls: ['API versioning strategy documented.', 'Deprecation policy: 6-month notice before removal.'],
            rollbackPlan: 'Remove deprecation header; no breaking change.',
        },
        pattern: {
            risk: 'Non-RESTful patterns confuse consumers and tooling.',
            blastRadius: 'all API consumers',
            estimatedHours: 6,
            acceptance: ['Refactored to REST conventions.', 'Existing consumers migrated or backward-compatible.'],
            firstStep: 'Map current routes to REST equivalents and plan migration.',
            tooling: [{ name: 'OpenAPI/Swagger', hint: 'document RESTful API design' }],
            preventiveControls: ['API design review gate for new requests.', 'REST conventions documented in style guide.'],
            rollbackPlan: 'Keep old route with 301 redirect to new RESTful path.',
        },
        complexity: {
            risk: 'Overly large handlers are hard to test, review, and maintain.',
            blastRadius: 'handler + reviewers',
            estimatedHours: 12,
            acceptance: ['Handler split into <200 LOC modules.', 'Test coverage maintained.', 'Public API unchanged.'],
            firstStep: "List the handler's top-level responsibilities — each becomes a module.",
            tooling: [{ name: 'eslint-plugin-import', hint: 'enforce file-level LOC budgets' }],
            preventiveControls: ['CI: fail PRs adding >100 LOC to handlers over 500 LOC.', 'CODEOWNERS for large handlers.'],
            rollbackPlan: 'Revert split; barrel re-exports original handler.',
        },
        versioning: {
            risk: 'Breaking changes affect all consumers without versioning.',
            blastRadius: 'all API consumers',
            estimatedHours: 10,
            acceptance: ['Version prefix added.', 'Legacy routes redirected.', 'Documentation updated.'],
            firstStep: 'Add /v1/ prefix; deprecate unversioned routes with 301 redirect.',
            tooling: [{ name: 'express-version-route', hint: 'versioned routing for Express' }],
            preventiveControls: ['API design review requires version prefix.', 'CI: flag routes without version prefix.'],
            rollbackPlan: 'Remove version prefix; restore original route paths.',
        },
        semantics: {
            risk: 'Incorrect HTTP method usage violates RFC 7231 — clients, caches, and intermediaries make wrong assumptions.',
            blastRadius: 'all clients + intermediary proxies',
            estimatedHours: 4,
            acceptance: ['Method corrected per HTTP spec.', 'Existing consumers migrated or backward-compatible.', 'Tests updated.'],
            firstStep: 'Identify the correct HTTP method per RFC 7231; plan safe migration.',
            tooling: [{ name: 'RFC 7231', hint: 'HTTP/1.1 Semantics and Content specification' }],
            preventiveControls: ['API design review: verify method semantics.', 'OpenAPI spec enforcement.'],
            rollbackPlan: 'Keep old route with redirect; remove after consumer migration.',
        },
        contracts: {
            risk: 'Missing or inconsistent request/response schemas cause integration failures and documentation drift.',
            blastRadius: 'all API consumers + documentation',
            estimatedHours: 6,
            acceptance: ['Request/response schemas documented.', 'Error format standardized.', 'Pagination consistent.'],
            firstStep: 'Audit all endpoints for response format and error format consistency.',
            tooling: [{ name: 'OpenAPI', hint: 'generate and enforce API contracts' }, { name: 'zod-to-openapi', hint: 'bridge validation and docs' }],
            preventiveControls: ['CI: validate response schemas in tests.', 'Contract-first API design workflow.'],
            rollbackPlan: 'Revert schema changes; restore original response shapes.',
        },
        pagination: {
            risk: 'Unpaginated collections risk response bloat, timeout, and memory exhaustion.',
            blastRadius: 'all collection consumers',
            estimatedHours: 3,
            acceptance: ['Pagination added with reasonable defaults.', 'Max limit enforced.', 'Consistent style across collections.'],
            firstStep: 'Add pagination params (offset/limit or cursor) to the collection handler.',
            tooling: [{ name: 'express-paginate', hint: 'pagination middleware for Express' }],
            preventiveControls: ['CI: flag collection endpoints without pagination.', 'Default limit enforced in shared middleware.'],
            rollbackPlan: 'Remove pagination params; revert to unbounded query.',
        },
    };
    var alerts = (window.REPORT_DATA && window.REPORT_DATA.alerts) || [];
    for (var i = 0; i < alerts.length; i++) {
        var a = alerts[i];
        var d = byCategory[(a.category || '').toLowerCase()];
        if (!d) continue;
        if (!a.risk) a.risk = d.risk;
        if (!a.blastRadius) a.blastRadius = d.blastRadius;
        if (!a.estimatedHours) a.estimatedHours = d.estimatedHours;
        if (!Array.isArray(a.acceptance) || a.acceptance.length === 0) a.acceptance = d.acceptance;
        if (!a.firstStep) a.firstStep = d.firstStep;
        if (!Array.isArray(a.tooling) || a.tooling.length === 0) a.tooling = d.tooling;
        if (!Array.isArray(a.preventiveControls) || a.preventiveControls.length === 0) a.preventiveControls = d.preventiveControls;
        if (!a.rollbackPlan) a.rollbackPlan = d.rollbackPlan;
    }
})();
